[package]
edition.workspace = true
license.workspace = true
name = "codepilotx-plugin"
version.workspace = true

[lib]
doctest = false
name = "codepilotx_plugin"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
codepilotx-config = { workspace = true }
codepilotx-protocol = { workspace = true }
codepilotx-utils-absolute-path = { workspace = true }
codepilotx-utils-plugins = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
