[package]
edition.workspace = true
license.workspace = true
name = "codepilotx-prompts"
version.workspace = true

[lib]
doctest = false
name = "codepilotx_prompts"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
codepilotx-context-fragments = { workspace = true }
codepilotx-git-utils = { workspace = true }
codepilotx-execpolicy = { workspace = true }
codepilotx-protocol = { workspace = true }
codepilotx-utils-absolute-path = { workspace = true }
codepilotx-utils-template = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
