import type {
  ThemeComponentDefinition,
  ThemeComponentCategory,
} from './themeTokenDebuggerModel.js'

export const DROPDOWN_COMPONENT: ThemeComponentDefinition = {
  id: 'dropdown',
  label: '下拉选单 (Dropdown / Popover)',
  category: 'primitives',
  description: '控制触发器及弹出菜单表面的 14 个独立状态语义 Token',
  slots: [
    // 触发器组
    {
      id: 'trigger-background',
      label: '触发器背景',
      group: '触发器 (Trigger)',
      valueType: 'color',
      cssProperty: 'background-color',
      targetToken: '--color-token-dropdown-trigger-background',
      description: '触发器常态背景颜色',
    },
    {
      id: 'trigger-foreground',
      label: '触发器文字',
      group: '触发器 (Trigger)',
      valueType: 'color',
      cssProperty: 'color',
      targetToken: '--color-token-dropdown-trigger-foreground',
      description: '触发器文字及图标前景色',
      contrastAgainst: '--color-token-dropdown-trigger-background',
    },
    {
      id: 'trigger-border',
      label: '触发器边框',
      group: '触发器 (Trigger)',
      valueType: 'color',
      cssProperty: 'border-color',
      targetToken: '--color-token-dropdown-trigger-border',
      description: '触发器常态边框颜色',
    },
    {
      id: 'trigger-hover-background',
      label: '触发器 Hover',
      group: '触发器 (Trigger)',
      valueType: 'color',
      cssProperty: 'background-color',
      targetToken: '--color-token-dropdown-trigger-hover-background',
      description: '触发器悬停背景颜色',
    },
    {
      id: 'trigger-open-background',
      label: '触发器 Open',
      group: '触发器 (Trigger)',
      valueType: 'color',
      cssProperty: 'background-color',
      targetToken: '--color-token-dropdown-trigger-open-background',
      description: '触发器展开状态背景颜色',
    },
    {
      id: 'trigger-disabled-foreground',
      label: '触发器 Disabled',
      group: '触发器 (Trigger)',
      valueType: 'color',
      cssProperty: 'color',
      targetToken: '--color-token-dropdown-trigger-disabled-foreground',
      description: '触发器禁用文字颜色',
      contrastAgainst: '--color-token-dropdown-trigger-background',
    },
    // 菜单组
    {
      id: 'surface-background',
      label: '菜单背景',
      group: '菜单表面 (Surface)',
      valueType: 'color',
      cssProperty: 'background-color',
      targetToken: '--color-token-dropdown-background',
      description: '弹出菜单表面背景颜色',
    },
    {
      id: 'surface-foreground',
      label: '菜单文字',
      group: '菜单表面 (Surface)',
      valueType: 'color',
      cssProperty: 'color',
      targetToken: '--color-token-dropdown-foreground',
      description: '弹出菜单项常规文字颜色',
      contrastAgainst: '--color-token-dropdown-background',
    },
    {
      id: 'surface-border',
      label: '菜单边框',
      group: '菜单表面 (Surface)',
      valueType: 'color',
      cssProperty: 'border-color',
      targetToken: '--color-token-dropdown-border',
      description: '弹出菜单表面外边框颜色',
    },
    {
      id: 'surface-item-hover-background',
      label: '菜单项 Hover',
      group: '菜单表面 (Surface)',
      valueType: 'color',
      cssProperty: 'background-color',
      targetToken: '--color-token-dropdown-item-hover-background',
      description: '菜单项悬停背景颜色',
      contrastAgainst: '--color-token-dropdown-foreground',
    },
    {
      id: 'surface-item-selected-background',
      label: '菜单项 Selected',
      group: '菜单表面 (Surface)',
      valueType: 'color',
      cssProperty: 'background-color',
      targetToken: '--color-token-dropdown-item-selected-background',
      description: '菜单项选中状态背景颜色',
      contrastAgainst: '--color-token-dropdown-foreground',
    },
    {
      id: 'surface-item-pressed-background',
      label: '菜单项 Pressed',
      group: '菜单表面 (Surface)',
      valueType: 'color',
      cssProperty: 'background-color',
      targetToken: '--color-token-dropdown-item-pressed-background',
      description: '菜单项按下状态背景颜色',
    },
    {
      id: 'surface-item-disabled-foreground',
      label: '菜单项 Disabled',
      group: '菜单表面 (Surface)',
      valueType: 'color',
      cssProperty: 'color',
      targetToken: '--color-token-dropdown-item-disabled-foreground',
      description: '菜单项禁用文字颜色',
      contrastAgainst: '--color-token-dropdown-background',
    },
    {
      id: 'focus-border',
      label: 'Focus（触发器与菜单共用）',
      group: '菜单表面 (Surface)',
      valueType: 'color',
      cssProperty: 'outline-color',
      targetToken: '--color-token-dropdown-focus-border',
      description: '触发器与弹出菜单项键盘聚焦指示边框颜色',
    },
  ],
  contrastChecks: [
    {
      label: '触发器文字 / 背景',
      foregroundToken: '--color-token-dropdown-trigger-foreground',
      backgroundToken: '--color-token-dropdown-trigger-background',
    },
    {
      label: '菜单文字 / 背景',
      foregroundToken: '--color-token-dropdown-foreground',
      backgroundToken: '--color-token-dropdown-background',
    },
    {
      label: '菜单文字 / 悬停',
      foregroundToken: '--color-token-dropdown-foreground',
      backgroundToken: '--color-token-dropdown-item-hover-background',
    },
    {
      label: '菜单文字 / 选中',
      foregroundToken: '--color-token-dropdown-foreground',
      backgroundToken: '--color-token-dropdown-item-selected-background',
    },
    {
      label: '禁用文字 / 菜单背景',
      foregroundToken: '--color-token-dropdown-item-disabled-foreground',
      backgroundToken: '--color-token-dropdown-background',
    },
  ],
}

export const BUTTON_COMPONENT: ThemeComponentDefinition = {
  id: 'button',
  label: '按钮 (Button / IconButton)',
  category: 'primitives',
  description: '控制按钮及图标按钮的背景、边框、按压、圆角与尺寸阶梯',
  slots: [
    {
      id: 'button-background',
      label: '默认背景',
      group: '色彩与状态 (Colors & States)',
      valueType: 'color',
      cssProperty: 'background-color',
      targetToken: '--color-token-button-background',
      description: '标准按钮中性背景颜色',
    },
    {
      id: 'button-foreground',
      label: '文字与图标',
      group: '色彩与状态 (Colors & States)',
      valueType: 'color',
      cssProperty: 'color',
      targetToken: '--color-token-button-foreground',
      description: '标准按钮前景色',
      contrastAgainst: '--color-token-button-background',
    },
    {
      id: 'button-border',
      label: '默认边框',
      group: '色彩与状态 (Colors & States)',
      valueType: 'color',
      cssProperty: 'border-color',
      targetToken: '--color-token-button-border',
      description: '标准按钮外边框颜色',
    },
    {
      id: 'button-hover-background',
      label: '次级悬停背景',
      group: '色彩与状态 (Colors & States)',
      valueType: 'color',
      cssProperty: 'background-color',
      targetToken: '--color-token-button-secondary-hover-background',
      description: '次级与中性按钮 Hover 背景色',
    },
    {
      id: 'button-pressed',
      label: '按下状态 (Pressed)',
      group: '色彩与状态 (Colors & States)',
      valueType: 'color',
      cssProperty: 'background-color',
      targetToken: '--color-token-button-pressed',
      description: '按钮激活按压时的覆盖遮罩色',
    },
    {
      id: 'button-radius-md',
      label: '默认圆角 (MD)',
      group: '几何尺寸 (Geometry)',
      valueType: 'radius',
      cssProperty: 'border-radius',
      targetToken: '--button-radius-md',
      description: '标准按钮圆角大小',
    },
    {
      id: 'button-radius-lg',
      label: '大尺寸圆角 (LG)',
      group: '几何尺寸 (Geometry)',
      valueType: 'radius',
      cssProperty: 'border-radius',
      targetToken: '--button-radius-lg',
      description: '大按钮圆角大小',
    },
    {
      id: 'button-size-compact',
      label: '紧凑高度 (Compact)',
      group: '几何尺寸 (Geometry)',
      valueType: 'dimension',
      cssProperty: 'height',
      targetToken: '--button-size-compact',
      description: '紧凑型按钮高度 (24px)',
    },
    {
      id: 'button-size-toolbar',
      label: '工具栏高度 (Toolbar)',
      group: '几何尺寸 (Geometry)',
      valueType: 'dimension',
      cssProperty: 'height',
      targetToken: '--button-size-toolbar',
      description: '工具栏动作按钮高度 (28px)',
    },
    {
      id: 'button-size-large',
      label: '大尺寸高度 (Large)',
      group: '几何尺寸 (Geometry)',
      valueType: 'dimension',
      cssProperty: 'height',
      targetToken: '--button-size-large',
      description: '大尺寸按钮高度 (36px)',
    },
  ],
  contrastChecks: [
    {
      label: '按钮文字 / 背景',
      foregroundToken: '--color-token-button-foreground',
      backgroundToken: '--color-token-button-background',
    },
  ],
}

export const INPUT_COMPONENT: ThemeComponentDefinition = {
  id: 'input',
  label: '输入框 (Input / SearchInput)',
  category: 'primitives',
  description: '控制单行/多行输入框、搜索框及校验状态的视觉样式',
  slots: [
    {
      id: 'input-background',
      label: '输入框背景',
      group: '常态与焦点 (Normal & Focus)',
      valueType: 'color',
      cssProperty: 'background-color',
      targetToken: '--color-token-input-background',
      description: '输入框与搜索框默认底色',
    },
    {
      id: 'input-foreground',
      label: '输入文字',
      group: '常态与焦点 (Normal & Focus)',
      valueType: 'color',
      cssProperty: 'color',
      targetToken: '--color-token-input-foreground',
      description: '输入框录入文本颜色',
      contrastAgainst: '--color-token-input-background',
    },
    {
      id: 'input-border',
      label: '输入框边框',
      group: '常态与焦点 (Normal & Focus)',
      valueType: 'color',
      cssProperty: 'border-color',
      targetToken: '--color-token-input-border',
      description: '常态边框颜色',
    },
    {
      id: 'input-placeholder-foreground',
      label: '占位符文字',
      group: '常态与焦点 (Normal & Focus)',
      valueType: 'color',
      cssProperty: 'color',
      targetToken: '--color-token-input-placeholder-foreground',
      description: 'Placeholder 提示文字颜色',
      contrastAgainst: '--color-token-input-background',
    },
    {
      id: 'focus-border',
      label: '焦点边框',
      group: '常态与焦点 (Normal & Focus)',
      valueType: 'color',
      cssProperty: 'outline-color',
      targetToken: '--color-token-focus-border',
      description: '聚焦时外环指示色',
    },
    {
      id: 'radius-input',
      label: '输入框圆角',
      group: '常态与焦点 (Normal & Focus)',
      valueType: 'radius',
      cssProperty: 'border-radius',
      targetToken: '--radius-input',
      description: '输入框标准圆角大小',
    },
    {
      id: 'input-validation-error-background',
      label: '错误背景',
      group: '校验状态 (Validation)',
      valueType: 'color',
      cssProperty: 'background-color',
      targetToken: '--color-token-input-validation-error-background',
      description: '输入校验失败底色',
    },
    {
      id: 'input-validation-error-border',
      label: '错误边框',
      group: '校验状态 (Validation)',
      valueType: 'color',
      cssProperty: 'border-color',
      targetToken: '--color-token-input-validation-error-border',
      description: '输入校验失败指示边框',
    },
    {
      id: 'input-validation-warning-background',
      label: '警告背景',
      group: '校验状态 (Validation)',
      valueType: 'color',
      cssProperty: 'background-color',
      targetToken: '--color-token-input-validation-warning-background',
      description: '输入校验警告底色',
    },
    {
      id: 'input-validation-warning-border',
      label: '警告边框',
      group: '校验状态 (Validation)',
      valueType: 'color',
      cssProperty: 'border-color',
      targetToken: '--color-token-input-validation-warning-border',
      description: '输入校验警告指示边框',
    },
  ],
  contrastChecks: [
    {
      label: '输入文字 / 输入背景',
      foregroundToken: '--color-token-input-foreground',
      backgroundToken: '--color-token-input-background',
    },
    {
      label: '占位提示 / 输入背景',
      foregroundToken: '--color-token-input-placeholder-foreground',
      backgroundToken: '--color-token-input-background',
    },
  ],
}

export const SWITCH_SEGMENTED_COMPONENT: ThemeComponentDefinition = {
  id: 'switch-segmented',
  label: '开关与分段 (Switch & Segments)',
  category: 'primitives',
  description: '控制 ToggleSwitch 滑块与 SegmentedControl 分段控件样式',
  slots: [
    {
      id: 'radio-active-foreground',
      label: '选中项前景色',
      group: '分段控件 (SegmentedControl)',
      valueType: 'color',
      cssProperty: 'color',
      targetToken: '--color-token-radio-active-foreground',
      description: '分段项选中激活时文字颜色',
    },
    {
      id: 'radio-inactive-border',
      label: '分段边框',
      group: '分段控件 (SegmentedControl)',
      valueType: 'color',
      cssProperty: 'border-color',
      targetToken: '--color-token-radio-inactive-border',
      description: '分段控件外框及分隔线颜色',
    },
    {
      id: 'radius-pill',
      label: '胶囊全圆角',
      group: '分段控件 (SegmentedControl)',
      valueType: 'radius',
      cssProperty: 'border-radius',
      targetToken: '--radius-pill',
      description: '胶囊控件全圆角',
    },
    {
      id: 'shadow-control-sm',
      label: '微阴影 (Control SM)',
      group: '开关控件 (ToggleSwitch)',
      valueType: 'shadow',
      cssProperty: 'box-shadow',
      targetToken: '--shadow-control-sm',
      description: '开关滑块与分段滑块微投影',
    },
    {
      id: 'control-thumb-fill',
      label: '滑块填充色',
      group: '开关控件 (ToggleSwitch)',
      valueType: 'color',
      cssProperty: 'background-color',
      targetToken: '--control-thumb-fill',
      description: '开关滑块实体颜色',
    },
  ],
}

export const TOOLTIP_SCROLL_CHIP_COMPONENT: ThemeComponentDefinition = {
  id: 'tooltip-scroll-chip',
  label: '浮层气泡、滚动条与胶囊 (Tooltip & Chips)',
  category: 'primitives',
  description: '控制气泡提示 (Tooltip)、滚动条滑块及标签胶囊 (MetaChip)',
  slots: [
    {
      id: 'tooltip-surface-background',
      label: 'Tooltip 背景',
      group: '浮层气泡 (Tooltip)',
      valueType: 'color',
      cssProperty: 'background-color',
      targetToken: '--tooltip-surface-background',
      description: 'Tooltip 浮层气泡专用背景填充',
    },
    {
      id: 'tooltip-surface-border',
      label: 'Tooltip 边框',
      group: '浮层气泡 (Tooltip)',
      valueType: 'border',
      cssProperty: 'border',
      targetToken: '--tooltip-surface-border',
      description: 'Tooltip 浮层边框契约',
    },
    {
      id: 'tooltip-surface-shadow',
      label: 'Tooltip 阴影',
      group: '浮层气泡 (Tooltip)',
      valueType: 'shadow',
      cssProperty: 'box-shadow',
      targetToken: '--tooltip-surface-shadow',
      description: 'Tooltip 与浮层专用投影',
    },
    {
      id: 'tooltip-surface-radius',
      label: 'Tooltip 圆角',
      group: '浮层气泡 (Tooltip)',
      valueType: 'radius',
      cssProperty: 'border-radius',
      targetToken: '--tooltip-surface-radius',
      description: 'Tooltip 标准圆角 (16px)',
    },
    {
      id: 'scrollbar-slider-background',
      label: '滚动滑块常态',
      group: '滚动条 (ScrollArea)',
      valueType: 'color',
      cssProperty: 'background-color',
      targetToken: '--color-token-scrollbar-slider-background',
      description: '滚动条滑块默认颜色',
    },
    {
      id: 'scrollbar-slider-hover-background',
      label: '滚动滑块 Hover',
      group: '滚动条 (ScrollArea)',
      valueType: 'color',
      cssProperty: 'background-color',
      targetToken: '--color-token-scrollbar-slider-hover-background',
      description: '滚动条滑块悬停高亮颜色',
    },
    {
      id: 'scrollbar-slider-active-background',
      label: '滚动滑块 Active',
      group: '滚动条 (ScrollArea)',
      valueType: 'color',
      cssProperty: 'background-color',
      targetToken: '--color-token-scrollbar-slider-active-background',
      description: '滚动条拖拽按压颜色',
    },
  ],
}

export const SURFACES_COMPONENT: ThemeComponentDefinition = {
  id: 'surfaces',
  label: '容器与五层表面 (Card & 5 Surfaces)',
  category: 'containers',
  description: '系统的 5 层全局核心表面体系 (Underlay, Canvas, Panel, Raised, Floating)',
  slots: [
    {
      id: 'layer-underlay-fill',
      label: '底图层 (Underlay)',
      group: '表面填充体系 (Fills)',
      valueType: 'color',
      cssProperty: 'background-color',
      targetToken: '--layer-underlay-fill',
      description: '最底层衬底填充色（通常对应侧边栏底色）',
    },
    {
      id: 'layer-canvas-fill',
      label: '画布层 (Canvas)',
      group: '表面填充体系 (Fills)',
      valueType: 'color',
      cssProperty: 'background-color',
      targetToken: '--layer-canvas-fill',
      description: '主内容视口画布填充色',
    },
    {
      id: 'layer-panel-fill',
      label: '面板层 (Panel)',
      group: '表面填充体系 (Fills)',
      valueType: 'color',
      cssProperty: 'background-color',
      targetToken: '--layer-panel-fill',
      description: '工作区边栏与停靠面板填充色',
    },
    {
      id: 'layer-raised-fill',
      label: '抬升层 (Raised)',
      group: '表面填充体系 (Fills)',
      valueType: 'color',
      cssProperty: 'background-color',
      targetToken: '--layer-raised-fill',
      description: '悬浮卡片与次级抬升表面填充色',
    },
    {
      id: 'layer-floating-fill',
      label: '顶浮层 (Floating)',
      group: '表面填充体系 (Fills)',
      valueType: 'color',
      cssProperty: 'background-color',
      targetToken: '--layer-floating-fill',
      description: '模态对话框与弹出菜单填充色',
    },
    {
      id: 'layer-edge',
      label: '标准分界线 (Layer Edge)',
      group: '边框与投影 (Edges & Shadows)',
      valueType: 'border',
      cssProperty: 'border',
      targetToken: '--layer-edge',
      description: '标准表面分界线条契约',
    },
    {
      id: 'layer-edge-strong',
      label: '高对比分界线 (Edge Strong)',
      group: '边框与投影 (Edges & Shadows)',
      valueType: 'border',
      cssProperty: 'border',
      targetToken: '--layer-edge-strong',
      description: '强调层次分界线条契约',
    },
    {
      id: 'radius-card',
      label: '卡片圆角 (Radius Card)',
      group: '边框与投影 (Edges & Shadows)',
      valueType: 'radius',
      cssProperty: 'border-radius',
      targetToken: '--radius-card',
      description: '标准卡片圆角 (12px)',
    },
    {
      id: 'radius-panel',
      label: '面板圆角 (Radius Panel)',
      group: '边框与投影 (Edges & Shadows)',
      valueType: 'radius',
      cssProperty: 'border-radius',
      targetToken: '--radius-panel',
      description: '面板圆角 (16px)',
    },
    {
      id: 'shadow-floating',
      label: '顶浮层投影 (Shadow Floating)',
      group: '边框与投影 (Edges & Shadows)',
      valueType: 'shadow',
      cssProperty: 'box-shadow',
      targetToken: '--shadow-floating',
      description: '标准深浮层大投影',
    },
    {
      id: 'shadow-raised',
      label: '抬升层投影 (Shadow Raised)',
      group: '边框与投影 (Edges & Shadows)',
      valueType: 'shadow',
      cssProperty: 'box-shadow',
      targetToken: '--shadow-raised',
      description: '卡片抬升微投影',
    },
  ],
}

export const MODAL_COMPONENT: ThemeComponentDefinition = {
  id: 'modal',
  label: '对话框与浮层 (Modal & Dialog)',
  category: 'containers',
  description: '控制模态遮罩、弹窗表面专属别名、边框、浮层投影及动作栏样式',
  slots: [
    {
      id: 'modal-surface-background',
      label: '弹窗表面背景',
      group: '浮层视觉 (Modal Surface)',
      valueType: 'color',
      cssProperty: 'background-color',
      targetToken: '--modal-surface-background',
      description: '对话框主表面背景填充（专属别名）',
    },
    {
      id: 'modal-surface-border',
      label: '弹窗边框',
      group: '浮层视觉 (Modal Surface)',
      valueType: 'border',
      cssProperty: 'border',
      targetToken: '--modal-surface-border',
      description: '对话框外边框线条契约（专属别名）',
    },
    {
      id: 'modal-surface-shadow',
      label: '弹窗投影',
      group: '浮层视觉 (Modal Surface)',
      valueType: 'shadow',
      cssProperty: 'box-shadow',
      targetToken: '--modal-surface-shadow',
      description: '模态对话框高阶深浮层投影（专属别名）',
    },
    {
      id: 'modal-surface-radius',
      label: '弹窗圆角',
      group: '浮层视觉 (Modal Surface)',
      valueType: 'radius',
      cssProperty: 'border-radius',
      targetToken: '--modal-surface-radius',
      description: '对话框外围圆角（专属别名）',
    },
    {
      id: 'preformat-background',
      label: '详情胶囊背景',
      group: '内容与辅助 (Content & Meta)',
      valueType: 'color',
      cssProperty: 'background-color',
      targetToken: '--color-token-text-preformat-background',
      description: '对话框参数标签与预格式化块底色',
    },
  ],
}

export const SIDEBAR_DOCK_COMPONENT: ThemeComponentDefinition = {
  id: 'sidebar-dock',
  label: '侧边栏与右侧栏 (Sidebar & RightDock)',
  category: 'layout',
  description: '控制主界面左侧导航边栏与右侧停靠面板的专属语义别名',
  slots: [
    // Left Sidebar 专属别名
    {
      id: 'sidebar-background',
      label: '左侧边栏背景',
      group: '侧边栏 (Left Sidebar)',
      valueType: 'color',
      cssProperty: 'background-color',
      targetToken: '--sidebar-background',
      description: '左侧导航与会话列表底色（专属别名）',
    },
    {
      id: 'sidebar-border',
      label: '边栏分界边框',
      group: '侧边栏 (Left Sidebar)',
      valueType: 'border',
      cssProperty: 'border',
      targetToken: '--sidebar-border',
      description: '左侧边栏分界边框（默认 0 无边框）',
    },
    {
      id: 'sidebar-item-hover-background',
      label: '会话项 Hover',
      group: '侧边栏 (Left Sidebar)',
      valueType: 'color',
      cssProperty: 'background-color',
      targetToken: '--sidebar-item-hover-background',
      description: '会话条目鼠标悬停背景色（专属别名）',
    },
    {
      id: 'sidebar-item-active-background',
      label: '会话项 Active',
      group: '侧边栏 (Left Sidebar)',
      valueType: 'color',
      cssProperty: 'background-color',
      targetToken: '--sidebar-item-active-background',
      description: '活动会话条目选中背景色（专属别名）',
    },
    {
      id: 'sidebar-item-radius',
      label: '会话条目圆角',
      group: '侧边栏 (Left Sidebar)',
      valueType: 'radius',
      cssProperty: 'border-radius',
      targetToken: '--sidebar-item-radius',
      description: '左侧栏条目圆角（专属别名）',
    },
    // Right Dock 专属别名
    {
      id: 'right-dock-background',
      label: '右侧栏底色',
      group: '右侧停靠栏 (RightDock)',
      valueType: 'color',
      cssProperty: 'background-color',
      targetToken: '--right-dock-background',
      description: '右侧停靠面板及空状态底色（专属别名）',
    },
    {
      id: 'right-dock-border-color',
      label: '右侧栏分界边框颜色',
      group: '右侧停靠栏 (RightDock)',
      valueType: 'color',
      cssProperty: 'border-color',
      targetToken: '--right-dock-border-color',
      description: '右侧栏左边框颜色（专属别名）',
    },
    {
      id: 'right-dock-tab-active-background',
      label: '标签激活背景',
      group: '右侧停靠栏 (RightDock)',
      valueType: 'color',
      cssProperty: 'background-color',
      targetToken: '--right-dock-tab-active-background',
      description: '右侧栏活动标签背景色（专属别名）',
    },
    {
      id: 'right-dock-tab-hover-background',
      label: '标签悬停背景',
      group: '右侧停靠栏 (RightDock)',
      valueType: 'color',
      cssProperty: 'background-color',
      targetToken: '--right-dock-tab-hover-background',
      description: '右侧栏标签悬停背景色（专属别名）',
    },
    {
      id: 'right-dock-tab-radius',
      label: '标签圆角',
      group: '右侧停靠栏 (RightDock)',
      valueType: 'radius',
      cssProperty: 'border-radius',
      targetToken: '--right-dock-tab-radius',
      description: '右侧栏标签圆角（专属别名）',
    },
    {
      id: 'tab-strip-height',
      label: '标签栏高度',
      group: '右侧停靠栏 (RightDock)',
      valueType: 'dimension',
      cssProperty: 'height',
      targetToken: '--workbench-tab-strip-height',
      description: '顶部标签栏固定高度 (46px)',
    },
  ],
  contrastChecks: [
    {
      label: '侧栏文字 / 侧栏背景',
      foregroundToken: '--color-token-foreground',
      backgroundToken: '--sidebar-background',
    },
  ],
}

export const WORKBENCH_COMPONENT: ThemeComponentDefinition = {
  id: 'workbench',
  label: '工作台面板与标签 (Workbench)',
  category: 'layout',
  description: '控制核心工作台面板 (WorkbenchPanel)、标签栏及状态指示器',
  slots: [
    {
      id: 'panel-background',
      label: '面板背景',
      group: '工作台面板 (Workbench Panel)',
      valueType: 'color',
      cssProperty: 'background-color',
      targetToken: '--color-token-panel-background',
      description: '工作台主面板背景填充',
    },
    {
      id: 'main-surface-primary',
      label: '主内容表面',
      group: '工作台面板 (Workbench Panel)',
      valueType: 'color',
      cssProperty: 'background-color',
      targetToken: '--color-token-main-surface-primary',
      description: '主编辑区表面底色',
    },
    {
      id: 'active-tab-selection',
      label: '激活标签背景',
      group: '标签栏 (Tab Strip)',
      valueType: 'color',
      cssProperty: 'background-color',
      targetToken: '--color-token-list-active-selection-background',
      description: '当前激活标签背景色',
    },
    {
      id: 'tab-strip-height',
      label: '标签栏高度',
      group: '标签栏 (Tab Strip)',
      valueType: 'dimension',
      cssProperty: 'height',
      targetToken: '--workbench-tab-strip-height',
      description: '工作台标签栏高度 (46px)',
    },
  ],
}

export const MENUBAR_COMPONENT: ThemeComponentDefinition = {
  id: 'menubar',
  label: '顶部菜单栏 (MenuBar)',
  category: 'layout',
  description: '控制窗口标题栏与应用程序顶部菜单条视觉',
  slots: [
    {
      id: 'menubar-height',
      label: '菜单栏高度',
      group: '菜单栏 (MenuBar)',
      valueType: 'dimension',
      cssProperty: 'height',
      targetToken: '--application-menubar-height',
      description: '窗口顶部菜单栏高度 (36px)',
    },
    {
      id: 'menubar-selection-background',
      label: '菜单选中背景',
      group: '菜单栏 (MenuBar)',
      valueType: 'color',
      cssProperty: 'background-color',
      targetToken: '--color-token-menubar-selection-background',
      description: '顶部菜单展开悬停选中背景色',
    },
    {
      id: 'menubar-selection-foreground',
      label: '菜单选中文字',
      group: '菜单栏 (MenuBar)',
      valueType: 'color',
      cssProperty: 'color',
      targetToken: '--color-token-menubar-selection-foreground',
      description: '顶部菜单展开选中文字颜色',
      contrastAgainst: '--color-token-menubar-selection-background',
    },
  ],
}

export const COMPOSER_COMPONENT: ThemeComponentDefinition = {
  id: 'composer',
  label: '消息输入台 (Composer)',
  category: 'features',
  description: '控制会话输入卡片、工具栏、发送区及安全边距',
  slots: [
    {
      id: 'floating-composer-h',
      label: '浮动输入台基准高度',
      group: '布局与间距 (Layout)',
      valueType: 'dimension',
      cssProperty: 'height',
      targetToken: '--floating-composer-h',
      description: '输入台默认浮动基准高度',
    },
    {
      id: 'layout-composer-safe-pad',
      label: '底部安全内边距',
      group: '布局与间距 (Layout)',
      valueType: 'dimension',
      cssProperty: 'padding-bottom',
      targetToken: '--layout-composer-safe-pad',
      description: '滚动区域避让输入台的安全高度',
    },
    {
      id: 'composer-background',
      label: '输入框底色',
      group: '色彩 (Colors)',
      valueType: 'color',
      cssProperty: 'background-color',
      targetToken: '--color-token-input-background',
      description: 'Composer 输入卡片底色',
    },
    {
      id: 'toolbar-hover-background',
      label: '工具按钮悬停色',
      group: '色彩 (Colors)',
      valueType: 'color',
      cssProperty: 'background-color',
      targetToken: '--color-token-toolbar-hover-background',
      description: 'Composer 底部动作按钮 Hover 背景色',
    },
  ],
}

export const TERMINAL_COMPONENT: ThemeComponentDefinition = {
  id: 'terminal',
  label: '集成终端 (Terminal)',
  category: 'features',
  description: '控制集成终端背景、边框及 16 色 ANSI 调色板',
  slots: [
    {
      id: 'terminal-background',
      label: '终端背景',
      group: '基础外观 (Base)',
      valueType: 'color',
      cssProperty: 'background-color',
      targetToken: '--color-token-terminal-background',
      description: '终端面板主背景色',
    },
    {
      id: 'terminal-foreground',
      label: '终端文字',
      group: '基础外观 (Base)',
      valueType: 'color',
      cssProperty: 'color',
      targetToken: '--color-token-terminal-foreground',
      description: '终端控制台前景色',
      contrastAgainst: '--color-token-terminal-background',
    },
    {
      id: 'terminal-border',
      label: '终端边框',
      group: '基础外观 (Base)',
      valueType: 'color',
      cssProperty: 'border-color',
      targetToken: '--color-token-terminal-border',
      description: '终端窗格分割边框',
    },
    {
      id: 'terminal-ansi-blue',
      label: 'ANSI 蓝色',
      group: 'ANSI 调色板 (ANSI Palette)',
      valueType: 'color',
      cssProperty: 'color',
      targetToken: '--color-token-terminal-ansi-blue',
      description: '标准 ANSI 蓝色',
    },
    {
      id: 'terminal-ansi-green',
      label: 'ANSI 绿色',
      group: 'ANSI 调色板 (ANSI Palette)',
      valueType: 'color',
      cssProperty: 'color',
      targetToken: '--color-token-terminal-ansi-green',
      description: '标准 ANSI 绿色',
    },
    {
      id: 'terminal-ansi-red',
      label: 'ANSI 红色',
      group: 'ANSI 调色板 (ANSI Palette)',
      valueType: 'color',
      cssProperty: 'color',
      targetToken: '--color-token-terminal-ansi-red',
      description: '标准 ANSI 红色',
    },
    {
      id: 'terminal-ansi-yellow',
      label: 'ANSI 黄色',
      group: 'ANSI 调色板 (ANSI Palette)',
      valueType: 'color',
      cssProperty: 'color',
      targetToken: '--color-token-terminal-ansi-yellow',
      description: '标准 ANSI 黄色',
    },
  ],
  contrastChecks: [
    {
      label: '终端文字 / 终端背景',
      foregroundToken: '--color-token-terminal-foreground',
      backgroundToken: '--color-token-terminal-background',
    },
  ],
}

export const REVIEW_DIFF_COMPONENT: ThemeComponentDefinition = {
  id: 'review-diff',
  label: '代码审查差异 (Review Diff)',
  category: 'features',
  description: '控制 Diff 比较视图行级新增/删除背景与文字装饰色',
  slots: [
    {
      id: 'diff-inserted-line-background',
      label: '新增行背景',
      group: '差异高亮 (Diff Highlights)',
      valueType: 'color',
      cssProperty: 'background-color',
      targetToken: '--color-token-diff-editor-inserted-line-background',
      description: 'Git Diff 增加行行级背景色',
    },
    {
      id: 'diff-inserted-text-background',
      label: '新增文字块背景',
      group: '差异高亮 (Diff Highlights)',
      valueType: 'color',
      cssProperty: 'background-color',
      targetToken: '--color-token-diff-editor-inserted-text-background',
      description: '行内具体增加字符强调背景色',
    },
    {
      id: 'diff-removed-line-background',
      label: '删除行背景',
      group: '差异高亮 (Diff Highlights)',
      valueType: 'color',
      cssProperty: 'background-color',
      targetToken: '--color-token-diff-editor-removed-line-background',
      description: 'Git Diff 删除行行级背景色',
    },
    {
      id: 'diff-removed-text-background',
      label: '删除文字块背景',
      group: '差异高亮 (Diff Highlights)',
      valueType: 'color',
      cssProperty: 'background-color',
      targetToken: '--color-token-diff-editor-removed-text-background',
      description: '行内具体删除字符强调背景色',
    },
    {
      id: 'diff-surface',
      label: '差异底板表面',
      group: '差异高亮 (Diff Highlights)',
      valueType: 'color',
      cssProperty: 'background-color',
      targetToken: '--color-token-diff-surface',
      description: 'Diff 窗格衬底背景色',
    },
  ],
}

export const THEME_COMPONENTS: readonly ThemeComponentDefinition[] = [
  DROPDOWN_COMPONENT,
  BUTTON_COMPONENT,
  INPUT_COMPONENT,
  SWITCH_SEGMENTED_COMPONENT,
  TOOLTIP_SCROLL_CHIP_COMPONENT,
  SURFACES_COMPONENT,
  MODAL_COMPONENT,
  SIDEBAR_DOCK_COMPONENT,
  WORKBENCH_COMPONENT,
  MENUBAR_COMPONENT,
  COMPOSER_COMPONENT,
  TERMINAL_COMPONENT,
  REVIEW_DIFF_COMPONENT,
]

export const CATEGORY_LABELS: Record<ThemeComponentCategory, string> = {
  primitives: '基础控件 (Primitives)',
  containers: '容器与表面 (Containers)',
  layout: '外壳布局 (Layout)',
  features: '特色工作台 (Features)',
}

export function getThemeComponent(id: string): ThemeComponentDefinition | undefined {
  return THEME_COMPONENTS.find(component => component.id === id)
}

export function getComponentsByCategory(category: ThemeComponentCategory): ThemeComponentDefinition[] {
  return THEME_COMPONENTS.filter(component => component.category === category)
}
