[package]
name = "codepilotx-utils-sandbox-summary"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
codepilotx-core = { workspace = true }
codepilotx-model-provider-info = { workspace = true }
codepilotx-protocol = { workspace = true }
codepilotx-utils-absolute-path = { workspace = true }

[dev-dependencies]
codepilotx-utils-absolute-path = { workspace = true }
pretty_assertions = { workspace = true }

[lib]
doctest = false
