import type { PerformanceBudget } from './metrics.js'

export const rendererBudgets: readonly PerformanceBudget[] = [
  { scenario: 'sidebar-resize', metric: 'frameP95Ms', max: 20 },
  { scenario: 'sidebar-resize', metric: 'writesDuringDrag', max: 0 },
  { scenario: 'sidebar-resize', metric: 'writesAfterDrop', min: 1, max: 1 },
  { scenario: 'review-live-resize', metric: 'frameP95Ms', max: 20 },
  { scenario: 'review-live-resize', metric: 'maxLongTaskMs', max: 50 },
  { scenario: 'review-live-resize', metric: 'liveWidthChanged', min: 1, max: 1 },
  {
    scenario: 'review-live-resize',
    metric: 'stressTicksDuringDrag',
    min: 5,
    max: 1_000,
  },
  {
    scenario: 'review-live-resize',
    metric: 'appendedSessionEventsDuringDrag',
    min: 15,
    max: 3_000,
  },
  {
    scenario: 'review-live-resize',
    metric: 'canonicalUpdatesDuringDrag',
    min: 5,
    max: 1_000,
  },
  { scenario: 'review-live-resize', metric: 'runningSessions', min: 3, max: 3 },
  { scenario: 'review-live-resize', metric: 'writesDuringDrag', max: 0 },
  {
    scenario: 'review-live-resize',
    metric: 'writesAfterDrop',
    min: 1,
    max: 1,
  },
  {
    scenario: 'review-file-tree-live-resize',
    metric: 'frameP95Ms',
    max: 20,
  },
  {
    scenario: 'review-file-tree-live-resize',
    metric: 'maxLongTaskMs',
    max: 50,
  },
  {
    scenario: 'review-file-tree-live-resize',
    metric: 'diffWidthShiftDuringDrag',
    max: -48,
  },
  {
    scenario: 'review-file-tree-live-resize',
    metric: 'liveTreeWidthChanged',
    min: 1,
    max: 1,
  },
  {
    scenario: 'review-file-tree-live-resize',
    metric: 'committedWidthChangedDuringDrag',
    max: 0,
  },
  {
    scenario: 'review-file-tree-live-resize',
    metric: 'committedWidthChangedAfterDrop',
    min: 1,
    max: 1,
  },
  {
    scenario: 'review-file-tree-live-resize',
    metric: 'stressTicksDuringDrag',
    min: 5,
    max: 1_000,
  },
  {
    scenario: 'concurrent-session-updates',
    metric: 'frameP95Ms',
    max: 20,
  },
  {
    scenario: 'concurrent-session-updates',
    metric: 'maxLongTaskMs',
    max: 50,
  },
  {
    scenario: 'concurrent-session-updates',
    metric: 'stressTicks',
    min: 20,
    max: 1_000,
  },
  {
    scenario: 'concurrent-session-updates',
    metric: 'appendedSessionEvents',
    min: 60,
    max: 3_000,
  },
  {
    scenario: 'concurrent-session-updates',
    metric: 'runningSessions',
    min: 3,
    max: 3,
  },
  {
    scenario: 'review-file-tree-live-resize',
    metric: 'appendedSessionEventsDuringDrag',
    min: 15,
    max: 3_000,
  },
  {
    scenario: 'review-file-tree-live-resize',
    metric: 'canonicalUpdatesDuringDrag',
    min: 5,
    max: 1_000,
  },
  {
    scenario: 'review-file-tree-live-resize',
    metric: 'runningSessions',
    min: 3,
    max: 3,
  },
  { scenario: 'selector', metric: 'selectorP95Ms', max: 12 },
  { scenario: 'selector', metric: 'growthFactor', max: 6 },
  { scenario: 'timeline-scroll', metric: 'frameP95Ms', max: 34 },
  { scenario: 'timeline-scroll', metric: 'maxLongTaskMs', max: 200 },
  { scenario: 'timeline-scroll', metric: 'mountedTurns', max: 80 },
  { scenario: 'cold-switch', metric: 'readyMs', max: 400 },
  { scenario: 'cold-switch', metric: 'staleVisibleMs', max: 100 },
  { scenario: 'cached-switch', metric: 'cachedContentMs', max: 100 },
  { scenario: 'cached-switch', metric: 'readyMs', max: 300 },
  { scenario: 'composer-input', metric: 'inputToPaintP95Ms', max: 50 },
  { scenario: 'composer-input', metric: 'relativeDegradationPercent', max: 10 },
  { scenario: 'sidebar-dnd', metric: 'moveMs', max: 80 },
  { scenario: 'sidebar-dnd', metric: 'dropReadyMs', max: 250 },
  { scenario: 'memory-stability', metric: 'heapRegressionScore', max: 0 },
] as const

export const electronBudgets: readonly PerformanceBudget[] = [
  { scenario: 'cold-start', metric: 'readyMs', max: 8_000 },
  { scenario: 'warm-start', metric: 'readyMs', max: 5_000 },
  { scenario: 'timeline-scroll', metric: 'frameP95Ms', max: 40 },
  { scenario: 'timeline-scroll', metric: 'maxLongTaskMs', max: 300 },
  { scenario: 'cold-switch', metric: 'readyMs', max: 800 },
  { scenario: 'sidebar-dnd', metric: 'dropReadyMs', max: 400 },
  { scenario: 'composer-input', metric: 'inputToPaintP95Ms', max: 75 },
  { scenario: 'memory-stability', metric: 'memoryRegressionScore', max: 0 },
] as const
