export const CODEPILOTX_CONFIG_DIR_ENV = 'CODEPILOTX_CONFIG_DIR'
export const LEGACY_CLAUDE_CONFIG_DIR_ENV = 'CLAUDE_CONFIG_DIR'
export const CODEPILOTX_CONFIG_DIR_NAME = '.codepilotx'
export const LEGACY_CLAUDE_CONFIG_DIR_NAME = '.claude'
