[package]
edition.workspace = true
license.workspace = true
name = "codepilotx-core-api"
version.workspace = true

[lib]
doctest = false
name = "codepilotx_core_api"
path = "src/lib.rs"
test = false

[lints]
workspace = true

[dependencies]
codepilotx-app-server-protocol = { workspace = true }
codepilotx-arg0 = { workspace = true }
codepilotx-analytics = { workspace = true }
codepilotx-config = { workspace = true }
codepilotx-core = { workspace = true }
codepilotx-extension-api = { workspace = true }
codepilotx-home = { workspace = true }
codepilotx-exec-server = { workspace = true }
codepilotx-features = { workspace = true }
codepilotx-login = { workspace = true }
codepilotx-model-provider-info = { workspace = true }
codepilotx-models-manager = { workspace = true }
codepilotx-protocol = { workspace = true }
codepilotx-utils-absolute-path = { workspace = true }
