[package]
edition.workspace = true
license.workspace = true
name = "codepilotx-memories-read"
version.workspace = true

[lib]
name = "codepilotx_memories_read"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true

[dependencies]
codepilotx-protocol = { workspace = true }
codepilotx-shell-command = { workspace = true }
codepilotx-utils-absolute-path = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
