[package]
edition.workspace = true
license.workspace = true
name = "codepilotx-context-fragments"
version.workspace = true

[lib]
name = "codepilotx_context_fragments"
path = "src/lib.rs"
test = false
doctest = false

[lints]
workspace = true

[dependencies]
codepilotx-protocol = { workspace = true }
codepilotx-utils-string = { workspace = true }
