declare module "@ai-sdk/amazon-bedrock" { export const createAmazonBedrock: import("./types").ProviderFactory }
declare module "@ai-sdk/amazon-bedrock/mantle" { export const createBedrockMantle: import("./types").ProviderFactory }
declare module "@ai-sdk/anthropic" { export const createAnthropic: import("./types").ProviderFactory }
declare module "@ai-sdk/azure" { export const createAzure: import("./types").ProviderFactory }
declare module "@ai-sdk/google" { export const createGoogleGenerativeAI: import("./types").ProviderFactory }
declare module "@ai-sdk/google-vertex" { export const createVertex: import("./types").ProviderFactory }
declare module "@ai-sdk/google-vertex/anthropic" { export const createVertexAnthropic: import("./types").ProviderFactory }
declare module "@ai-sdk/openai" { export const createOpenAI: import("./types").ProviderFactory }
declare module "@ai-sdk/openai-compatible" { export const createOpenAICompatible: import("./types").ProviderFactory }
declare module "@openrouter/ai-sdk-provider" { export const createOpenRouter: import("./types").ProviderFactory }
declare module "@ai-sdk/xai" { export const createXai: import("./types").ProviderFactory }
declare module "@ai-sdk/mistral" { export const createMistral: import("./types").ProviderFactory }
declare module "@ai-sdk/groq" { export const createGroq: import("./types").ProviderFactory }
declare module "@ai-sdk/deepinfra" { export const createDeepInfra: import("./types").ProviderFactory }
declare module "@ai-sdk/cerebras" { export const createCerebras: import("./types").ProviderFactory }
declare module "@ai-sdk/cohere" { export const createCohere: import("./types").ProviderFactory }
declare module "@ai-sdk/gateway" { export const createGateway: import("./types").ProviderFactory }
declare module "@ai-sdk/togetherai" { export const createTogetherAI: import("./types").ProviderFactory }
declare module "@ai-sdk/perplexity" { export const createPerplexity: import("./types").ProviderFactory }
declare module "@ai-sdk/vercel" { export const createVercel: import("./types").ProviderFactory }
declare module "@ai-sdk/alibaba" { export const createAlibaba: import("./types").ProviderFactory }
declare module "gitlab-ai-provider" { export const createGitLab: import("./types").ProviderFactory }
declare module "venice-ai-sdk-provider" { export const createVenice: import("./types").ProviderFactory }
