import type { AgentEventMethod, AgentRpcMethod } from "@codepilotx/shared/thread"

export type MigrationStatus = "keep" | "rename" | "replace" | "remove"

export type MigrationEntry =
  | {
    readonly status: "keep" | "rename" | "replace"
    readonly target: string
  }
  | {
    readonly status: "remove"
    readonly reason: string
  }

export const V2MethodMigrationManifest = {
  initialize: { status: "keep", target: "initialize" },
  shutdown: { status: "keep", target: "shutdown" },
  "desktop/settings/get": { status: "remove", reason: "Desktop settings move to typed Electron IPC." },
  "desktop/settings/save": { status: "remove", reason: "Desktop settings move to typed Electron IPC." },
  "project/list": { status: "keep", target: "project/list" },
  "project/open": { status: "keep", target: "project/open" },
  "project/updateSettings": { status: "rename", target: "project/settings/update" },
  "workspace/file/list": { status: "keep", target: "workspace/file/list" },
  "workspace/file/read": { status: "keep", target: "workspace/file/read" },
  "workspace/file/save": { status: "keep", target: "workspace/file/save" },
  "workspace/file/watch": { status: "keep", target: "workspace/file/watch" },
  "workspace/file/unwatch": { status: "keep", target: "workspace/file/unwatch" },
  "thread/list": { status: "keep", target: "thread/list" },
  "thread/create": { status: "keep", target: "thread/create" },
  "thread/read": { status: "keep", target: "thread/read" },
  "prompt/preview": { status: "keep", target: "prompt/preview" },
  "prompt/refresh": { status: "keep", target: "prompt/refresh" },
  "thread/compact": { status: "keep", target: "thread/compact" },
  "thread/update": { status: "keep", target: "thread/update" },
  "thread/settings/update": { status: "keep", target: "thread/settings/update" },
  "thread/delete": { status: "keep", target: "thread/delete" },
  "turn/start": { status: "keep", target: "turn/start" },
  "turn/interrupt": { status: "keep", target: "turn/interrupt" },
  "turn/resume": { status: "keep", target: "turn/resume" },
  "queue/update": { status: "keep", target: "queue/update" },
  "queue/remove": { status: "keep", target: "queue/remove" },
  "queue/reorder": { status: "keep", target: "queue/reorder" },
  "queue/steer": { status: "keep", target: "queue/steer" },
  "queue/resume": { status: "keep", target: "queue/resume" },
  "turn/submitPlanDecision": { status: "replace", target: "plan/request" },
  "approval/respond": { status: "replace", target: "approval/request" },
  "hook/trust/respond": { status: "replace", target: "hookTrust/request" },
  "sandbox/status": { status: "keep", target: "sandbox/status" },
  "sandbox/install": { status: "keep", target: "sandbox/install" },
  "sandbox/repair": { status: "keep", target: "sandbox/repair" },
  "sandbox/uninstall": { status: "keep", target: "sandbox/uninstall" },
  "question/respond": { status: "replace", target: "question/request" },
  "attachment/import": { status: "keep", target: "attachment/import" },
  "attachment/read": { status: "keep", target: "attachment/read" },
  "memory/list": { status: "keep", target: "memory/list" },
  "memory/read": { status: "keep", target: "memory/read" },
  "memory/save": { status: "keep", target: "memory/save" },
  "memory/delete": { status: "keep", target: "memory/delete" },
  "memory/reset": { status: "keep", target: "memory/reset" },
  "subagent/list": { status: "keep", target: "subagent/list" },
  "subagent/read": { status: "keep", target: "subagent/read" },
  "subagent/send": { status: "keep", target: "subagent/send" },
  "subagent/stop": { status: "keep", target: "subagent/stop" },
  "subagent/retry": { status: "keep", target: "subagent/retry" },
  "subagent/worktree/diff": { status: "keep", target: "subagent/worktree/diff" },
  "subagent/worktree/apply": { status: "keep", target: "subagent/worktree/apply" },
  "subagent/worktree/discard": { status: "keep", target: "subagent/worktree/discard" },
  "subagent/workspace/restore": { status: "keep", target: "subagent/workspace/restore" },
  "model/list": { status: "keep", target: "model/list" },
  "provider/list": { status: "keep", target: "provider/list" },
  "model/refresh": { status: "keep", target: "model/refresh" },
  "model/setDefault": { status: "keep", target: "model/setDefault" },
  "model/setReviewer": { status: "keep", target: "model/setReviewer" },
  "provider/test": { status: "keep", target: "provider/test" },
  "provider/updateSettings": { status: "keep", target: "provider/updateSettings" },
  "integration/list": { status: "keep", target: "integration/list" },
  "integration/connect": { status: "keep", target: "integration/connect" },
  "integration/authorize": { status: "keep", target: "integration/authorize" },
  "integration/authorizeComplete": { status: "keep", target: "integration/authorizeComplete" },
  "integration/authorizeStatus": { status: "keep", target: "integration/authorizeStatus" },
  "integration/disconnect": { status: "keep", target: "integration/disconnect" },
} as const satisfies Record<AgentRpcMethod, MigrationEntry>

export const V2EventMigrationManifest = {
  "workspace/file/changed": { status: "keep", target: "workspace/file/changed" },
  "thread/created": { status: "keep", target: "thread/created" },
  "thread/snapshot": { status: "remove", reason: "Snapshots are returned by thread/read with a stream position." },
  "thread/updated": { status: "keep", target: "thread/updated" },
  "thread/settings/updated": { status: "keep", target: "thread/settings/updated" },
  "thread/prompt-settings/updated": { status: "keep", target: "thread/prompt-settings/updated" },
  "thread/deleted": { status: "keep", target: "thread/deleted" },
  "turn/queued": { status: "keep", target: "turn/queued" },
  "turn/started": { status: "keep", target: "turn/started" },
  "turn/statusChanged": { status: "keep", target: "turn/statusChanged" },
  "turn/completed": { status: "keep", target: "turn/completed" },
  "turn/failed": { status: "keep", target: "turn/failed" },
  "turn/interrupted": { status: "keep", target: "turn/interrupted" },
  "agent/upserted": { status: "keep", target: "agent/upserted" },
  "subagent/created": { status: "keep", target: "subagent/created" },
  "subagent/updated": { status: "keep", target: "subagent/updated" },
  "subagent/workspaceUpdated": { status: "keep", target: "subagent/workspaceUpdated" },
  "item/started": { status: "keep", target: "item/started" },
  "item/completed": { status: "keep", target: "item/completed" },
  "item/agentMessage/delta": { status: "keep", target: "item/agentMessage/delta" },
  "reasoning/textDelta": { status: "keep", target: "reasoning/textDelta" },
  "reasoning/summaryPartAdded": { status: "keep", target: "reasoning/summaryPartAdded" },
  "reasoning/summaryTextDelta": { status: "keep", target: "reasoning/summaryTextDelta" },
  "plan/delta": { status: "keep", target: "plan/delta" },
  "plan/ready": { status: "keep", target: "plan/ready" },
  "plan/decision": { status: "keep", target: "plan/decision" },
  "tool/callStarted": { status: "keep", target: "tool/callStarted" },
  "tool/outputDelta": { status: "keep", target: "tool/outputDelta" },
  "tool/callCompleted": { status: "keep", target: "tool/callCompleted" },
  "tool/error": { status: "keep", target: "tool/error" },
  "approval/requested": { status: "keep", target: "approval/requested" },
  "approval/cancelled": { status: "keep", target: "approval/cancelled" },
  "question/requested": { status: "keep", target: "question/requested" },
  "serverRequest/resolved": { status: "rename", target: "interaction/resolved" },
  "context/compacted": { status: "keep", target: "context/compacted" },
  "context/recoveryRequired": { status: "keep", target: "context/recoveryRequired" },
  "hook/trust/requested": { status: "keep", target: "hook/trust/requested" },
  "hook/trust/resolved": { status: "keep", target: "hook/trust/resolved" },
  "queue/updated": { status: "keep", target: "queue/updated" },
  "catalog/updated": { status: "keep", target: "catalog/updated" },
  "integration/updated": { status: "keep", target: "integration/updated" },
  "integration/authorizationCompleted": { status: "keep", target: "integration/authorizationCompleted" },
  "integration/authorizationFailed": { status: "keep", target: "integration/authorizationFailed" },
  heartbeat: { status: "remove", reason: "Liveness uses WebSocket ping/pong and subscription notifications." },
} as const satisfies Record<AgentEventMethod, MigrationEntry>

export const V2MigrationManifest = {
  methods: V2MethodMigrationManifest,
  events: V2EventMigrationManifest,
} as const
