import type { DesktopApi } from './types.js'

export type DesktopApiMethod = Exclude<
  keyof DesktopApi,
  'onAgentEvent' | 'onWorkflowEvent' | 'onUiCommand' | 'onUpdateStatusChange'
>

export const DESKTOP_API_METHODS = [
  'getAuthStatus',
  'getRuntimeStatus',
  'diagnoseDesktopToolchain',
  'reinstallDesktopToolchain',
  'deleteDesktopToolchain',
  'getDesktopSettings',
  'saveDesktopSettings',
  'listProjectMemories',
  'readProjectMemory',
  'saveProjectMemory',
  'deleteProjectMemory',
  'resetProjectMemory',
  'listProjectMemoryRecalls',
  'getBrowserState',
  'openBrowser',
  'navigateBrowser',
  'reloadBrowser',
  'goBackBrowser',
  'goForwardBrowser',
  'closeBrowser',
  'setBrowserBounds',
  'clearBrowserAllowedSites',
  'listBuiltinPlugins',
  'setBuiltinPluginEnabled',
  'listSkillsCatalog',
  'installSkill',
  'listSlashCommands',
  'listMcpServers',
  'saveMcpServer',
  'removeMcpServer',
  'setMcpServerEnabled',
  'listOpenTargets',
  'openPathWithDefaultTarget',
  'listModelProviders',
  'getModelProviderState',
  'fetchProviderModels',
  'fetchProviderBalance',
  'saveModelProvider',
  'saveProviderApiKey',
  'deleteProviderApiKey',
  'getCopilotAuthStatus',
  'startCopilotLogin',
  'pollCopilotLogin',
  'cancelCopilotLogin',
  'getGithubAuthStatus',
  'startGithubLogin',
  'pollGithubLogin',
  'logoutGithub',
  'listGithubRepositories',
  'getGithubProfileOverview',
  'setGithubUserStatus',
  'clearGithubUserStatus',
  'cloneGithubRepository',
  'chooseWorkspace',
  'openWorkspace',
  'getWorkspaceContext',
  'checkoutWorkspaceBranch',
  'getWorkspaceGitStatus',
  'createWorkspaceBranch',
  'commitWorkspaceChanges',
  'pushWorkspaceBranch',
  'discardWorkspaceChanges',
  'createPullRequest',
  'getWorkspaceReviewDiff',
  'applyWorkspaceReviewOperation',
  'listWorkspaceFiles',
  'readWorkspaceFile',
  'readOptionalWorkspaceFile',
  'chooseComposerFiles',
  'readComposerFiles',
  'getWorkspaceDiff',
  'getThemeSettings',
  'saveThemeSettings',
  'createSession',
  'listSessions',
  'getSession',
  'getActiveSessionId',
  'setActiveSession',
  'updateSessionMetadata',
  'saveSessionReviewComment',
  'resolveSessionReviewComment',
  'deleteSessionReviewComment',
  'setSessionPermissionMode',
  'setSessionPlanModeActive',
  'setSessionLocalRouterMode',
  'readWorkflowEventLog',
  'openConfigFile',
  'openExternalURL',
  'sendUserMessage',
  'respondToPermission',
  'interruptSession',
  'disposeSession',
  'minimizeWindow',
  'toggleWindowMaximized',
  'closeWindow',
  'isWindowMaximized',
  'newWindow',
  'openDevTools',
  'closeDevTools',
  'openSettings',
  'logOut',
  'exitApp',
  'checkForUpdates',
  'downloadUpdate',
  'quitAndInstall',
  'listDebugBuiltinTools',
  'runDebugToolProbe',
  'cancelDebugToolProbe',
] as const satisfies readonly DesktopApiMethod[]

export function desktopApiChannel(method: DesktopApiMethod): string {
  return `desktop:${method}`
}

export const DESKTOP_AGENT_EVENT_CHANNEL = 'desktop:agent-event'
export const DESKTOP_WORKFLOW_EVENT_CHANNEL = 'desktop:workflow-event'
export const DESKTOP_UI_COMMAND_CHANNEL = 'desktop:ui-command'
export const DESKTOP_UPDATE_STATUS_CHANNEL = 'desktop:update-status'
