import {
  TASKBOARD_COMMENT_MAX_LENGTH,
  TASKBOARD_DESCRIPTION_MAX_LENGTH,
  TASKBOARD_LABEL_MAX_LENGTH,
  TASKBOARD_LABELS_PER_TASK_MAX,
  TASKBOARD_TITLE_MAX_LENGTH,
  TaskboardCommentSchema,
  TaskboardLabelSchema,
  TaskboardPrioritySchema,
  TaskboardBlockerSchema,
  TaskboardPlanItemSchema,
  TaskboardPlanningRootSchema,
  TaskboardPlanningSnapshotSchema,
  TaskboardStatusSchema,
  TaskboardTaskDetailsSchema,
  TaskboardTaskSummarySchema,
  TaskboardThreadRoleSchema,
  TaskboardWorkflowDatePresetSchema,
  TaskboardWorkflowDateSchema,
  TaskboardWorkflowSortSchema,
  TaskboardWorkflowStartModeSchema,
  TaskboardWorkflowStatusSchema,
  TaskboardWorkflowTaskDetailsSchema,
  TaskboardWorkflowTaskSummarySchema,
  TaskboardWorkflowThreadCandidateSchema,
  TaskboardWorkflowThreadLookupSchema,
  TaskboardWorkflowTransitionActionSchema,
  TaskContextChangeSchema,
  TaskContextEntrySchema,
  TaskContextEvidenceSchema,
  TaskContextProposalSchema,
  TaskContextSectionSchema,
  TaskContextSnapshotSchema,
} from "@codepilotx/shared/taskboard"
import { Schema } from "effect"
import { defineMethod, type MethodMap } from "../wire/definition"
import {
  CursorSchema,
  LimitSchema,
  NonEmptyStringSchema,
  OpaqueIDSchema,
  SequenceSchema,
  TimestampSchema,
} from "../wire/primitives"
const TaskTitleSchema = Schema.String.check(Schema.isMinLength(1), Schema.isMaxLength(TASKBOARD_TITLE_MAX_LENGTH))
const BlockerTextSchema = Schema.String.check(Schema.isMinLength(1), Schema.isMaxLength(TASKBOARD_COMMENT_MAX_LENGTH))
const TaskDescriptionSchema = Schema.String.check(Schema.isMaxLength(TASKBOARD_DESCRIPTION_MAX_LENGTH))
const TaskCommentBodySchema = Schema.String.check(Schema.isMinLength(1), Schema.isMaxLength(TASKBOARD_COMMENT_MAX_LENGTH))
const TaskLabelNameSchema = Schema.String.check(Schema.isMinLength(1), Schema.isMaxLength(TASKBOARD_LABEL_MAX_LENGTH))
const TaskLabelIdsSchema = Schema.Array(OpaqueIDSchema).check(Schema.isMaxLength(TASKBOARD_LABELS_PER_TASK_MAX))
const ExpectedVersionSchema = Schema.Int.check(Schema.isGreaterThanOrEqualTo(1))
const NonNegativeIntSchema = Schema.Int.check(Schema.isGreaterThanOrEqualTo(0))

export const TaskboardStartExecutionSchema = Schema.Union([
  Schema.Struct({ kind: Schema.Literal("local") }),
  Schema.Struct({ kind: Schema.Literal("existing_worktree"), worktreeId: OpaqueIDSchema }),
  Schema.Struct({
    kind: Schema.Literal("new_worktree"),
    startingState: Schema.Union([
      Schema.Struct({ type: Schema.Literal("branch"), branchName: NonEmptyStringSchema }),
      Schema.Struct({ type: Schema.Literal("working_tree") }),
    ]),
  }),
])
export type TaskboardStartExecution = typeof TaskboardStartExecutionSchema.Type

export const TaskboardStartOperationStatusSchema = Schema.Literals([
  "running",
  "awaiting_setup_decision",
  "completed",
  "failed",
  "rollback_failed",
])
export const TaskboardStartOperationStepSchema = Schema.Literals([
  "preflight",
  "prepare_worktree",
  "create_thread",
  "link",
  "complete",
])
export const TaskboardStartOperationSchema = Schema.Struct({
  operationId: OpaqueIDSchema,
  taskId: OpaqueIDSchema,
  projectId: OpaqueIDSchema,
  threadId: Schema.NullOr(OpaqueIDSchema),
  worktreeId: Schema.NullOr(OpaqueIDSchema),
  execution: TaskboardStartExecutionSchema,
  status: TaskboardStartOperationStatusSchema,
  step: TaskboardStartOperationStepSchema,
  revision: ExpectedVersionSchema,
  errorCode: Schema.NullOr(NonEmptyStringSchema),
  warnings: Schema.Array(NonEmptyStringSchema),
  startupInstruction: Schema.NullOr(Schema.String),
  createdAt: TimestampSchema,
  updatedAt: TimestampSchema,
  completedAt: Schema.NullOr(TimestampSchema),
})
export type TaskboardStartOperation = typeof TaskboardStartOperationSchema.Type

const TaskboardErrors = [
  "PROJECT_NOT_FOUND",
  "PROJECT_REMOVED",
  "THREAD_NOT_FOUND",
  "WORKTREE_NOT_FOUND",
  "WORKTREE_NOT_READY",
  "WORKTREE_SETUP_REQUIRED",
  "TASKBOARD_TASK_NOT_FOUND",
  "TASKBOARD_COMMENT_NOT_FOUND",
  "TASKBOARD_LABEL_NOT_FOUND",
  "TASKBOARD_OPERATION_NOT_FOUND",
  "TASKBOARD_START_OPERATION_NOT_FOUND",
  "TASKBOARD_THREAD_ALREADY_LINKED",
  "TASKBOARD_PRIMARY_EXISTS",
  "TASKBOARD_CONTEXT_REQUIRED",
  "OPERATION_ID_CONFLICT",
  "PERMISSION_DENIED",
  "CONFLICT",
  "INVALID_REQUEST",
  "ROLLBACK_FAILED",
  "INTERNAL_ERROR",
] as const

const TaskResultSchema = Schema.Struct({ task: TaskboardTaskDetailsSchema })
const OperationIdField = { operationId: OpaqueIDSchema } as const
const ExpectedVersionField = { expectedVersion: ExpectedVersionSchema } as const
const WorkflowTaskResultSchema = Schema.Struct({ task: TaskboardWorkflowTaskDetailsSchema })
const WorkflowThreadLinkInputSchema = Schema.Struct({
  threadId: OpaqueIDSchema,
  role: TaskboardThreadRoleSchema,
})
const ContextReadResultSchema = Schema.Struct({ snapshot: TaskContextSnapshotSchema, entries: Schema.Array(TaskContextEntrySchema), evidence: Schema.Array(TaskContextEvidenceSchema) })
const ContextErrors = [...TaskboardErrors, "TASKBOARD_CONTEXT_REVISION_CONFLICT", "TASKBOARD_CONTEXT_FROZEN", "TASKBOARD_PROPOSAL_STALE", "TASKBOARD_PROPOSAL_NOT_FOUND", "TASKBOARD_AI_MODEL_UNAVAILABLE"] as const
const PlanningErrors = [
  ...TaskboardErrors,
  "TASKBOARD_PLAN_NOT_FOUND",
  "TASKBOARD_PLAN_VERSION_CONFLICT",
  "TASKBOARD_PLAN_INVALID_PARENT",
  "TASKBOARD_PLAN_CYCLE",
  "TASKBOARD_PLAN_CONDITION_UNMET",
  "TASKBOARD_BLOCKER_NOT_FOUND",
] as const
const TaskboardStartErrors = [...TaskboardErrors, "TASKBOARD_PLAN_CONDITION_UNMET"] as const

const PlanningStepInputSchema = Schema.Struct({
  clientId: NonEmptyStringSchema,
  kind: Schema.Literal("step"),
  title: TaskTitleSchema,
  description: Schema.optional(TaskDescriptionSchema),
  position: Schema.optional(Schema.Number),
})
const PlanningTaskInputSchema = Schema.Struct({
  clientId: NonEmptyStringSchema,
  kind: Schema.Literal("task"),
  title: TaskTitleSchema,
  description: Schema.optional(TaskDescriptionSchema),
  status: Schema.optional(TaskboardWorkflowStatusSchema),
  priority: Schema.optional(TaskboardPrioritySchema),
  labelIds: Schema.optional(TaskLabelIdsSchema),
  startDate: Schema.optional(Schema.NullOr(TaskboardWorkflowDateSchema)),
  dueDate: Schema.optional(Schema.NullOr(TaskboardWorkflowDateSchema)),
  position: Schema.optional(Schema.Number),
})
const PlanningApplyItemSchema = Schema.Union([PlanningStepInputSchema, PlanningTaskInputSchema])
const PlanningDependencyInputSchema = Schema.Struct({
  dependentClientId: NonEmptyStringSchema,
  prerequisiteClientId: NonEmptyStringSchema,
})
const PlanningSnapshotResultSchema = Schema.Struct({ snapshot: TaskboardPlanningSnapshotSchema })

export const TaskboardRpcMethods = {
  "taskboard/context/read": defineMethod({
    params: Schema.Struct({ taskId: OpaqueIDSchema, sections: Schema.optional(Schema.Array(TaskContextSectionSchema)), includeEvidence: Schema.optional(Schema.Boolean), includeUnverified: Schema.optional(Schema.Boolean), includeAncestors: Schema.optional(Schema.Boolean), limit: Schema.optional(LimitSchema), offset: Schema.optional(NonNegativeIntSchema) }),
    result: ContextReadResultSchema, errors: ContextErrors, capability: "taskboard.context.v1", mutation: false, exactParams: true, exactResult: true,
  }),
  "taskboard/context/update": defineMethod({
    params: Schema.Struct({ taskId: OpaqueIDSchema, expectedContextRevision: ExpectedVersionSchema, changes: Schema.Array(TaskContextChangeSchema).check(Schema.isMinLength(1), Schema.isMaxLength(10)) }),
    result: Schema.Struct({ snapshot: TaskContextSnapshotSchema }), errors: ContextErrors, capability: "taskboard.context.v1", mutation: true, exactParams: true, exactResult: true,
  }),
  "taskboard/context/ai-preview": defineMethod({
    params: Schema.Struct({ taskId: OpaqueIDSchema }), result: Schema.Struct({ proposal: TaskContextProposalSchema }), errors: ContextErrors, capability: "taskboard.context.v1", mutation: true, exactParams: true, exactResult: true,
  }),
  "taskboard/context/ai-apply": defineMethod({
    params: Schema.Struct({ proposalId: OpaqueIDSchema }), result: Schema.Struct({ proposal: TaskContextProposalSchema, snapshot: TaskContextSnapshotSchema }), errors: ContextErrors, capability: "taskboard.context.v1", mutation: true, exactParams: true, exactResult: true,
  }),
  "taskboard/context/ai-discard": defineMethod({
    params: Schema.Struct({ proposalId: OpaqueIDSchema }), result: Schema.Struct({ proposal: TaskContextProposalSchema }), errors: ContextErrors, capability: "taskboard.context.v1", mutation: true, exactParams: true, exactResult: true,
  }),
  "taskboard/context/promotion-status": defineMethod({
    params: Schema.Struct({ taskId: OpaqueIDSchema }), result: Schema.Struct({ promotion: Schema.NullOr(Schema.Struct({ id: OpaqueIDSchema, taskId: OpaqueIDSchema, contextRevision: ExpectedVersionSchema, status: Schema.Literals(["pending", "running", "completed", "failed", "retryable"]), error: Schema.NullOr(Schema.String), createdAt: TimestampSchema, startedAt: Schema.NullOr(TimestampSchema), finishedAt: Schema.NullOr(TimestampSchema), updatedAt: TimestampSchema })) }), errors: ContextErrors, capability: "taskboard.context.v1", mutation: false, exactParams: true, exactResult: true,
  }),
  "taskboard/planning/roots": defineMethod({
    params: Schema.Struct({
      projectId: Schema.optional(OpaqueIDSchema),
      statuses: Schema.optional(Schema.Array(TaskboardWorkflowStatusSchema)),
      priorities: Schema.optional(Schema.Array(TaskboardPrioritySchema)),
      labelIds: Schema.optional(Schema.Array(OpaqueIDSchema)),
      query: Schema.optional(Schema.String),
      archived: Schema.optional(Schema.Boolean),
      unread: Schema.optional(Schema.Boolean),
      datePreset: Schema.optional(TaskboardWorkflowDatePresetSchema),
      today: Schema.optional(TaskboardWorkflowDateSchema),
      sort: Schema.optional(TaskboardWorkflowSortSchema),
      cursor: Schema.optional(CursorSchema),
      limit: Schema.optional(LimitSchema),
    }),
    result: Schema.Struct({
      roots: Schema.Array(TaskboardPlanningRootSchema),
      unreadCount: NonNegativeIntSchema,
      nextCursor: Schema.NullOr(CursorSchema),
    }),
    errors: PlanningErrors,
    capability: "taskboard.planning.v1",
    mutation: false,
    exactParams: true,
    exactResult: true,
  }),
  "taskboard/planning/read": defineMethod({
    params: Schema.Struct({ taskId: OpaqueIDSchema }),
    result: PlanningSnapshotResultSchema,
    errors: PlanningErrors,
    capability: "taskboard.planning.v1",
    mutation: false,
    exactParams: true,
    exactResult: true,
  }),
  "taskboard/planning/apply": defineMethod({
    params: Schema.Struct({
      parentTaskId: OpaqueIDSchema,
      expectedVersion: ExpectedVersionSchema,
      operationId: OpaqueIDSchema,
      items: Schema.Array(PlanningApplyItemSchema),
      dependencies: Schema.optional(Schema.Array(PlanningDependencyInputSchema)),
    }),
    result: PlanningSnapshotResultSchema,
    errors: PlanningErrors,
    capability: "taskboard.planning.v1",
    mutation: true,
    exactParams: true,
    exactResult: true,
  }),
  "taskboard/planning/step/update": defineMethod({
    params: Schema.Struct({
      operationId: OpaqueIDSchema,
      itemId: OpaqueIDSchema,
      expectedVersion: ExpectedVersionSchema,
      patch: Schema.Struct({
        title: Schema.optional(TaskTitleSchema),
        description: Schema.optional(TaskDescriptionSchema),
        status: Schema.optional(Schema.Literals(["todo", "done", "skipped"])),
        skipReason: Schema.optional(Schema.NullOr(NonEmptyStringSchema)),
      }),
    }),
    result: PlanningSnapshotResultSchema,
    errors: PlanningErrors,
    capability: "taskboard.planning.v1",
    mutation: true,
    exactParams: true,
    exactResult: true,
  }),
  "taskboard/planning/step/promote": defineMethod({
    params: Schema.Struct({
      operationId: OpaqueIDSchema,
      itemId: OpaqueIDSchema,
      expectedVersion: ExpectedVersionSchema,
      task: Schema.Struct({
        status: Schema.optional(TaskboardWorkflowStatusSchema),
        priority: Schema.optional(TaskboardPrioritySchema),
        labelIds: Schema.optional(TaskLabelIdsSchema),
        startDate: Schema.optional(Schema.NullOr(TaskboardWorkflowDateSchema)),
        dueDate: Schema.optional(Schema.NullOr(TaskboardWorkflowDateSchema)),
      }),
    }),
    result: PlanningSnapshotResultSchema,
    errors: PlanningErrors,
    capability: "taskboard.planning.v1",
    mutation: true,
    exactParams: true,
    exactResult: true,
  }),
  "taskboard/planning/item/reorder": defineMethod({
    params: Schema.Struct({
      operationId: OpaqueIDSchema,
      itemId: OpaqueIDSchema,
      expectedVersion: ExpectedVersionSchema,
      beforeItemId: Schema.optional(Schema.NullOr(OpaqueIDSchema)),
      afterItemId: Schema.optional(Schema.NullOr(OpaqueIDSchema)),
    }),
    result: PlanningSnapshotResultSchema,
    errors: PlanningErrors,
    capability: "taskboard.planning.v1",
    mutation: true,
    exactParams: true,
    exactResult: true,
  }),
  "taskboard/planning/child/reparent": defineMethod({
    params: Schema.Struct({
      operationId: OpaqueIDSchema,
      childTaskId: OpaqueIDSchema,
      expectedVersion: ExpectedVersionSchema,
      parentTaskId: Schema.NullOr(OpaqueIDSchema),
      beforeItemId: Schema.optional(Schema.NullOr(OpaqueIDSchema)),
      afterItemId: Schema.optional(Schema.NullOr(OpaqueIDSchema)),
    }),
    result: Schema.Struct({
      childTaskId: OpaqueIDSchema,
      parentTaskId: Schema.NullOr(OpaqueIDSchema),
    }),
    errors: PlanningErrors,
    capability: "taskboard.planning.v1",
    mutation: true,
    exactParams: true,
    exactResult: true,
  }),
  "taskboard/planning/dependencies/set": defineMethod({
    params: Schema.Struct({
      operationId: OpaqueIDSchema,
      itemId: OpaqueIDSchema,
      expectedVersion: ExpectedVersionSchema,
      prerequisiteItemIds: Schema.Array(OpaqueIDSchema),
    }),
    result: PlanningSnapshotResultSchema,
    errors: PlanningErrors,
    capability: "taskboard.planning.v1",
    mutation: true,
    exactParams: true,
    exactResult: true,
  }),
  "taskboard/planning/blocker/create": defineMethod({
    params: Schema.Struct({
      operationId: OpaqueIDSchema,
      taskId: OpaqueIDSchema,
      planItemId: Schema.optional(Schema.NullOr(OpaqueIDSchema)),
      reason: BlockerTextSchema,
      sourceThreadId: Schema.optional(Schema.NullOr(OpaqueIDSchema)),
      sourceTurnId: Schema.optional(Schema.NullOr(OpaqueIDSchema)),
    }),
    result: Schema.Struct({ blocker: TaskboardBlockerSchema }),
    errors: PlanningErrors,
    capability: "taskboard.planning.v1",
    mutation: true,
    exactParams: true,
    exactResult: true,
  }),
  "taskboard/planning/blocker/resolve": defineMethod({
    params: Schema.Struct({
      operationId: OpaqueIDSchema,
      blockerId: OpaqueIDSchema,
      expectedVersion: ExpectedVersionSchema,
      resolution: BlockerTextSchema,
    }),
    result: Schema.Struct({ blocker: TaskboardBlockerSchema }),
    errors: PlanningErrors,
    capability: "taskboard.planning.v1",
    mutation: true,
    exactParams: true,
    exactResult: true,
  }),
  "taskboard/planning/attention/mark-read": defineMethod({
    params: Schema.Struct({
      operationId: OpaqueIDSchema,
      taskId: OpaqueIDSchema,
      itemId: Schema.optional(OpaqueIDSchema),
      expectedReadyNotifiedAt: Schema.optional(TimestampSchema),
    }),
    result: PlanningSnapshotResultSchema,
    errors: PlanningErrors,
    capability: "taskboard.planning.v1",
    mutation: true,
    exactParams: true,
    exactResult: true,
  }),
  "taskboard/planning/archive-tree": defineMethod({
    params: Schema.Struct({
      operationId: OpaqueIDSchema,
      rootTaskId: OpaqueIDSchema,
      expectedVersion: ExpectedVersionSchema,
      includeLinkedThreads: Schema.optional(Schema.Boolean),
    }),
    result: Schema.Struct({ batchId: OpaqueIDSchema, taskIds: Schema.Array(OpaqueIDSchema) }),
    errors: PlanningErrors,
    capability: "taskboard.planning.v1",
    mutation: true,
    exactParams: true,
    exactResult: true,
  }),
  "taskboard/planning/restore-tree": defineMethod({
    params: Schema.Struct({ operationId: OpaqueIDSchema, rootTaskId: OpaqueIDSchema }),
    result: Schema.Struct({ batchId: OpaqueIDSchema, taskIds: Schema.Array(OpaqueIDSchema) }),
    errors: PlanningErrors,
    capability: "taskboard.planning.v1",
    mutation: true,
    exactParams: true,
    exactResult: true,
  }),
  "taskboard/planning/delete-tree": defineMethod({
    params: Schema.Struct({ operationId: OpaqueIDSchema, rootTaskId: OpaqueIDSchema }),
    result: Schema.Struct({ deletedTaskIds: Schema.Array(OpaqueIDSchema) }),
    errors: PlanningErrors,
    capability: "taskboard.planning.v1",
    mutation: true,
    exactParams: true,
    exactResult: true,
  }),
  "taskboard/task/list": defineMethod({
    params: Schema.Struct({
      projectId: Schema.optional(OpaqueIDSchema),
      statuses: Schema.optional(Schema.Array(TaskboardStatusSchema)),
      priorities: Schema.optional(Schema.Array(TaskboardPrioritySchema)),
      labelIds: Schema.optional(Schema.Array(OpaqueIDSchema)),
      query: Schema.optional(Schema.String),
      archived: Schema.optional(Schema.Boolean),
      cursor: Schema.optional(CursorSchema),
      limit: Schema.optional(LimitSchema),
    }),
    result: Schema.Struct({
      tasks: Schema.Array(TaskboardTaskSummarySchema),
      nextCursor: Schema.NullOr(CursorSchema),
    }),
    errors: TaskboardErrors,
    capability: "taskboard.v1",
    mutation: false,
    exactParams: true,
    exactResult: true,
  }),
  "taskboard/task/read": defineMethod({
    params: Schema.Struct({ taskId: OpaqueIDSchema }),
    result: TaskResultSchema,
    errors: TaskboardErrors,
    capability: "taskboard.v1",
    mutation: false,
    exactParams: true,
    exactResult: true,
  }),
  "taskboard/task/create": defineMethod({
    params: Schema.Struct({
      projectId: OpaqueIDSchema,
      title: TaskTitleSchema,
      description: Schema.optional(TaskDescriptionSchema),
      status: Schema.optional(TaskboardStatusSchema),
      priority: Schema.optional(TaskboardPrioritySchema),
      labelIds: Schema.optional(TaskLabelIdsSchema),
      ...OperationIdField,
    }),
    result: TaskResultSchema,
    errors: TaskboardErrors,
    capability: "taskboard.v1",
    mutation: true,
    exactParams: true,
    exactResult: true,
  }),
  "taskboard/task/update": defineMethod({
    params: Schema.Struct({
      taskId: OpaqueIDSchema,
      patch: Schema.Struct({
        title: Schema.optional(TaskTitleSchema),
        description: Schema.optional(TaskDescriptionSchema),
        status: Schema.optional(TaskboardStatusSchema),
        priority: Schema.optional(TaskboardPrioritySchema),
        labelIds: Schema.optional(TaskLabelIdsSchema),
      }),
      ...ExpectedVersionField,
      ...OperationIdField,
    }),
    result: TaskResultSchema,
    errors: TaskboardErrors,
    capability: "taskboard.v1",
    mutation: true,
    exactParams: true,
    exactResult: true,
  }),
  "taskboard/task/move": defineMethod({
    params: Schema.Struct({
      taskId: OpaqueIDSchema,
      status: TaskboardStatusSchema,
      beforeTaskId: Schema.optional(Schema.NullOr(OpaqueIDSchema)),
      afterTaskId: Schema.optional(Schema.NullOr(OpaqueIDSchema)),
      ...ExpectedVersionField,
      ...OperationIdField,
    }),
    result: TaskResultSchema,
    errors: TaskboardErrors,
    capability: "taskboard.v1",
    mutation: true,
    exactParams: true,
    exactResult: true,
  }),
  "taskboard/task/archive": defineMethod({
    params: Schema.Struct({ taskId: OpaqueIDSchema, ...ExpectedVersionField, ...OperationIdField }),
    result: TaskResultSchema,
    errors: TaskboardErrors,
    capability: "taskboard.v1",
    mutation: true,
    exactParams: true,
    exactResult: true,
  }),
  "taskboard/task/restore": defineMethod({
    params: Schema.Struct({ taskId: OpaqueIDSchema, ...ExpectedVersionField, ...OperationIdField }),
    result: TaskResultSchema,
    errors: TaskboardErrors,
    capability: "taskboard.v1",
    mutation: true,
    exactParams: true,
    exactResult: true,
  }),
  "taskboard/task/delete": defineMethod({
    params: Schema.Struct({ taskId: OpaqueIDSchema, ...ExpectedVersionField, ...OperationIdField }),
    result: Schema.Struct({ deleted: Schema.Literal(true), taskId: OpaqueIDSchema }),
    errors: TaskboardErrors,
    capability: "taskboard.v1",
    mutation: true,
    exactParams: true,
    exactResult: true,
  }),
  "taskboard/thread/link": defineMethod({
    params: Schema.Struct({
      taskId: OpaqueIDSchema,
      threadId: OpaqueIDSchema,
      role: TaskboardThreadRoleSchema,
      ...ExpectedVersionField,
      ...OperationIdField,
    }),
    result: TaskResultSchema,
    errors: TaskboardErrors,
    capability: "taskboard.v1",
    mutation: true,
    exactParams: true,
    exactResult: true,
  }),
  "taskboard/thread/unlink": defineMethod({
    params: Schema.Struct({ taskId: OpaqueIDSchema, threadId: OpaqueIDSchema, ...ExpectedVersionField, ...OperationIdField }),
    result: TaskResultSchema,
    errors: TaskboardErrors,
    capability: "taskboard.v1",
    mutation: true,
    exactParams: true,
    exactResult: true,
  }),
  "taskboard/thread/set-primary": defineMethod({
    params: Schema.Struct({ taskId: OpaqueIDSchema, threadId: OpaqueIDSchema, ...ExpectedVersionField, ...OperationIdField }),
    result: TaskResultSchema,
    errors: TaskboardErrors,
    capability: "taskboard.v1",
    mutation: true,
    exactParams: true,
    exactResult: true,
  }),
  "taskboard/comment/create": defineMethod({
    params: Schema.Struct({ taskId: OpaqueIDSchema, body: TaskCommentBodySchema, ...ExpectedVersionField, ...OperationIdField }),
    result: Schema.Struct({ task: TaskboardTaskDetailsSchema, comment: TaskboardCommentSchema }),
    errors: TaskboardErrors,
    capability: "taskboard.v1",
    mutation: true,
    exactParams: true,
    exactResult: true,
  }),
  "taskboard/comment/update": defineMethod({
    params: Schema.Struct({ commentId: OpaqueIDSchema, body: TaskCommentBodySchema, ...ExpectedVersionField, ...OperationIdField }),
    result: Schema.Struct({ task: TaskboardTaskDetailsSchema, comment: TaskboardCommentSchema }),
    errors: TaskboardErrors,
    capability: "taskboard.v1",
    mutation: true,
    exactParams: true,
    exactResult: true,
  }),
  "taskboard/comment/delete": defineMethod({
    params: Schema.Struct({ commentId: OpaqueIDSchema, ...ExpectedVersionField, ...OperationIdField }),
    result: Schema.Struct({ task: TaskboardTaskDetailsSchema, comment: TaskboardCommentSchema }),
    errors: TaskboardErrors,
    capability: "taskboard.v1",
    mutation: true,
    exactParams: true,
    exactResult: true,
  }),
  "taskboard/label/list": defineMethod({
    params: Schema.Struct({ projectId: OpaqueIDSchema }),
    result: Schema.Struct({ labels: Schema.Array(TaskboardLabelSchema) }),
    errors: TaskboardErrors,
    capability: "taskboard.v1",
    mutation: false,
    exactParams: true,
    exactResult: true,
  }),
  "taskboard/label/create": defineMethod({
    params: Schema.Struct({ projectId: OpaqueIDSchema, name: TaskLabelNameSchema, ...OperationIdField }),
    result: Schema.Struct({ label: TaskboardLabelSchema }),
    errors: TaskboardErrors,
    capability: "taskboard.v1",
    mutation: true,
    exactParams: true,
    exactResult: true,
  }),
  "taskboard/label/update": defineMethod({
    params: Schema.Struct({ labelId: OpaqueIDSchema, name: TaskLabelNameSchema, ...ExpectedVersionField, ...OperationIdField }),
    result: Schema.Struct({ label: TaskboardLabelSchema }),
    errors: TaskboardErrors,
    capability: "taskboard.v1",
    mutation: true,
    exactParams: true,
    exactResult: true,
  }),
  "taskboard/label/delete": defineMethod({
    params: Schema.Struct({ labelId: OpaqueIDSchema, ...ExpectedVersionField, ...OperationIdField }),
    result: Schema.Struct({ deleted: Schema.Literal(true), labelId: OpaqueIDSchema }),
    errors: TaskboardErrors,
    capability: "taskboard.v1",
    mutation: true,
    exactParams: true,
    exactResult: true,
  }),
  "taskboard/task/start": defineMethod({
    params: Schema.Struct({
      taskId: OpaqueIDSchema,
      execution: TaskboardStartExecutionSchema,
      operationId: OpaqueIDSchema,
    }),
    result: Schema.Struct({ operation: TaskboardStartOperationSchema }),
    errors: TaskboardStartErrors,
    capability: "taskboard.v1",
    mutation: true,
    exactParams: true,
    exactResult: true,
  }),
  "taskboard/task/start/status": defineMethod({
    params: Schema.Struct({ operationId: OpaqueIDSchema, afterRevision: Schema.optional(SequenceSchema) }),
    result: Schema.Struct({ operation: TaskboardStartOperationSchema, changed: Schema.Boolean }),
    errors: TaskboardErrors,
    capability: "taskboard.v1",
    mutation: false,
    exactParams: true,
    exactResult: true,
  }),
  "taskboard/task/start/retry-setup": defineMethod({
    params: Schema.Struct({ operationId: OpaqueIDSchema, revision: ExpectedVersionSchema }),
    result: Schema.Struct({ operation: TaskboardStartOperationSchema }),
    errors: TaskboardStartErrors,
    capability: "taskboard.v1",
    mutation: true,
    exactParams: true,
    exactResult: true,
  }),
  "taskboard/task/start/continue-without-setup": defineMethod({
    params: Schema.Struct({ operationId: OpaqueIDSchema, revision: ExpectedVersionSchema }),
    result: Schema.Struct({ operation: TaskboardStartOperationSchema }),
    errors: TaskboardStartErrors,
    capability: "taskboard.v1",
    mutation: true,
    exactParams: true,
    exactResult: true,
  }),
  "taskboard/workflow/list": defineMethod({
    params: Schema.Struct({
      projectId: Schema.optional(OpaqueIDSchema),
      statuses: Schema.optional(Schema.Array(TaskboardWorkflowStatusSchema)),
      priorities: Schema.optional(Schema.Array(TaskboardPrioritySchema)),
      labelIds: Schema.optional(Schema.Array(OpaqueIDSchema)),
      query: Schema.optional(Schema.String),
      archived: Schema.optional(Schema.Boolean),
      unread: Schema.optional(Schema.Boolean),
      datePreset: Schema.optional(TaskboardWorkflowDatePresetSchema),
      today: Schema.optional(TaskboardWorkflowDateSchema),
      sort: Schema.optional(TaskboardWorkflowSortSchema),
      cursor: Schema.optional(CursorSchema),
      limit: Schema.optional(LimitSchema),
    }),
    result: Schema.Struct({
      tasks: Schema.Array(TaskboardWorkflowTaskSummarySchema),
      unreadCount: NonNegativeIntSchema,
      nextCursor: Schema.NullOr(CursorSchema),
    }),
    errors: TaskboardErrors,
    capability: "taskboard.workflow.v1",
    mutation: false,
    exactParams: true,
    exactResult: true,
  }),
  "taskboard/workflow/read": defineMethod({
    params: Schema.Struct({ taskId: OpaqueIDSchema }),
    result: WorkflowTaskResultSchema,
    errors: TaskboardErrors,
    capability: "taskboard.workflow.v1",
    mutation: false,
    exactParams: true,
    exactResult: true,
  }),
  "taskboard/workflow/create": defineMethod({
    params: Schema.Struct({
      operationId: OpaqueIDSchema,
      projectId: OpaqueIDSchema,
      title: TaskTitleSchema,
      description: Schema.optional(TaskDescriptionSchema),
      status: Schema.optional(TaskboardWorkflowStatusSchema),
      priority: Schema.optional(TaskboardPrioritySchema),
      labelIds: Schema.optional(TaskLabelIdsSchema),
      startDate: Schema.optional(Schema.NullOr(TaskboardWorkflowDateSchema)),
      dueDate: Schema.optional(Schema.NullOr(TaskboardWorkflowDateSchema)),
      threadLinks: Schema.optional(Schema.Array(WorkflowThreadLinkInputSchema)),
    }),
    result: WorkflowTaskResultSchema,
    errors: TaskboardErrors,
    capability: "taskboard.workflow.v1",
    mutation: true,
    exactParams: true,
    exactResult: true,
  }),
  "taskboard/workflow/update": defineMethod({
    params: Schema.Struct({
      operationId: OpaqueIDSchema,
      taskId: OpaqueIDSchema,
      expectedVersion: ExpectedVersionSchema,
      patch: Schema.Struct({
        title: Schema.optional(TaskTitleSchema),
        description: Schema.optional(TaskDescriptionSchema),
        priority: Schema.optional(TaskboardPrioritySchema),
        labelIds: Schema.optional(TaskLabelIdsSchema),
        startDate: Schema.optional(Schema.NullOr(TaskboardWorkflowDateSchema)),
        dueDate: Schema.optional(Schema.NullOr(TaskboardWorkflowDateSchema)),
      }),
    }),
    result: WorkflowTaskResultSchema,
    errors: TaskboardErrors,
    capability: "taskboard.workflow.v1",
    mutation: true,
    exactParams: true,
    exactResult: true,
  }),
  "taskboard/workflow/move": defineMethod({
    params: Schema.Struct({
      operationId: OpaqueIDSchema,
      taskId: OpaqueIDSchema,
      expectedVersion: ExpectedVersionSchema,
      status: TaskboardWorkflowStatusSchema,
      beforeTaskId: Schema.optional(Schema.NullOr(OpaqueIDSchema)),
      afterTaskId: Schema.optional(Schema.NullOr(OpaqueIDSchema)),
      note: Schema.optional(TaskCommentBodySchema),
    }),
    result: WorkflowTaskResultSchema,
    errors: TaskboardErrors,
    capability: "taskboard.workflow.v1",
    mutation: true,
    exactParams: true,
    exactResult: true,
  }),
  "taskboard/workflow/transition": defineMethod({
    params: Schema.Struct({
      operationId: OpaqueIDSchema,
      taskId: OpaqueIDSchema,
      expectedVersion: ExpectedVersionSchema,
      action: TaskboardWorkflowTransitionActionSchema,
      note: Schema.optional(TaskCommentBodySchema),
    }),
    result: WorkflowTaskResultSchema,
    errors: TaskboardErrors,
    capability: "taskboard.workflow.v1",
    mutation: true,
    exactParams: true,
    exactResult: true,
  }),
  "taskboard/workflow/mark-read": defineMethod({
    params: Schema.Struct({
      operationId: OpaqueIDSchema,
      taskId: OpaqueIDSchema,
      expectedUnreadAt: Schema.optional(TimestampSchema),
    }),
    result: WorkflowTaskResultSchema,
    errors: TaskboardErrors,
    capability: "taskboard.workflow.v1",
    mutation: true,
    exactParams: true,
    exactResult: true,
  }),
  "taskboard/workflow/thread-candidates": defineMethod({
    params: Schema.Struct({
      projectId: OpaqueIDSchema,
      query: Schema.optional(Schema.String),
      cursor: Schema.optional(CursorSchema),
      limit: Schema.optional(LimitSchema),
    }),
    result: Schema.Struct({
      threads: Schema.Array(TaskboardWorkflowThreadCandidateSchema),
      nextCursor: Schema.NullOr(CursorSchema),
    }),
    errors: TaskboardErrors,
    capability: "taskboard.workflow.v1",
    mutation: false,
    exactParams: true,
    exactResult: true,
  }),
  "taskboard/workflow/find-by-thread": defineMethod({
    params: Schema.Struct({
      threadId: OpaqueIDSchema,
      projectId: Schema.optional(OpaqueIDSchema),
    }),
    result: Schema.Struct({ lookup: TaskboardWorkflowThreadLookupSchema }),
    errors: TaskboardErrors,
    capability: "taskboard.workflow.v1",
    mutation: false,
    exactParams: true,
    exactResult: true,
  }),
  "taskboard/workflow/link-threads": defineMethod({
    params: Schema.Struct({
      operationId: OpaqueIDSchema,
      taskId: OpaqueIDSchema,
      expectedVersion: ExpectedVersionSchema,
      links: Schema.Array(WorkflowThreadLinkInputSchema),
    }),
    result: WorkflowTaskResultSchema,
    errors: TaskboardErrors,
    capability: "taskboard.workflow.v1",
    mutation: true,
    exactParams: true,
    exactResult: true,
  }),
  "taskboard/workflow/start": defineMethod({
    params: Schema.Struct({
      operationId: OpaqueIDSchema,
      taskId: OpaqueIDSchema,
      expectedVersion: ExpectedVersionSchema,
      execution: TaskboardStartExecutionSchema,
      mode: TaskboardWorkflowStartModeSchema,
      authorizeBacklog: Schema.optional(Schema.Boolean),
    }),
    result: Schema.Struct({ operation: TaskboardStartOperationSchema }),
    errors: TaskboardStartErrors,
    capability: "taskboard.workflow.v1",
    mutation: true,
    exactParams: true,
    exactResult: true,
  }),
} as const satisfies MethodMap

export type TaskboardRpcMethodMap = typeof TaskboardRpcMethods
