// Generated by scripts/generate-codex-themes.ts from raycast-dark-dE50Z_et.js.
// Do not edit this file manually.
import type { ThemeRegistration } from 'shiki'

const theme = {
  "chromeTheme": {
    "accent": "#ff6363",
    "fonts": {
      "code": "\"Jetbrains Mono\"",
      "ui": "Inter"
    },
    "ink": "#fefefe",
    "opaqueWindows": false,
    "surface": "#101010"
  },
  "colors": {
    "activityBar.background": "#0a0a0a",
    "activityBar.foreground": "#FFFFFFcc",
    "activityBarBadge.background": "#4FA3F8",
    "activityBarBadge.foreground": "#FFFFFF",
    "breadcrumb.focusForeground": "#FFFFFFcc",
    "breadcrumb.foreground": "#FFFFFF66",
    "button.background": "#4FA3F8",
    "button.foreground": "#FFFFFF",
    "commandCenter.background": "#151515",
    "commandCenter.border": "#FFFFFF14",
    "commandCenter.foreground": "#FFFFFF99",
    "diffEditor.insertedLineBackground": "#59D4990D",
    "diffEditor.insertedTextBackground": "#59D49915",
    "diffEditor.removedLineBackground": "#FF63630D",
    "diffEditor.removedTextBackground": "#FF636315",
    "dropdown.background": "#101010",
    "dropdown.listBackground": "#101010",
    "editor.background": "#141414",
    "editor.findMatchBackground": "#FF92174d",
    "editor.findMatchHighlightBackground": "#FF921726",
    "editor.foreground": "#FFFFFF",
    "editor.lineHighlightBackground": "#202020",
    "editor.lineHighlightBorder": "#202020",
    "editor.selectionBackground": "#323232",
    "editor.wordHighlightBackground": "#FFFFFF14",
    "editorBracketHighlight.foreground1": "#C4935A",
    "editorBracketHighlight.foreground2": "#9484BD",
    "editorBracketHighlight.foreground3": "#6AAAB5",
    "editorBracketHighlight.foreground4": "#C4935A",
    "editorBracketHighlight.foreground5": "#9484BD",
    "editorBracketHighlight.foreground6": "#6AAAB5",
    "editorBracketHighlight.unexpectedBracket.foreground": "#FF6363",
    "editorBracketMatch.background": "#FFFFFF14",
    "editorBracketMatch.border": "#FFFFFF33",
    "editorCursor.foreground": "#4FA3F8",
    "editorError.foreground": "#FF6363",
    "editorGroupHeader.tabsBackground": "#101010",
    "editorGroupHeader.tabsBorder": "#161616",
    "editorGutter.addedBackground": "#59D499",
    "editorGutter.deletedBackground": "#FF6363",
    "editorGutter.modifiedBackground": "#FFC531",
    "editorIndentGuide.activeBackground": "#FFFFFF1f",
    "editorIndentGuide.background": "#FFFFFF0d",
    "editorInfo.foreground": "#56C2FF",
    "editorLineNumber.activeForeground": "#FFFFFF99",
    "editorLineNumber.foreground": "#FFFFFF33",
    "editorOverviewRuler.errorForeground": "#FF6363",
    "editorOverviewRuler.infoForeground": "#56C2FF",
    "editorOverviewRuler.warningForeground": "#FF9217",
    "editorWarning.foreground": "#FF9217",
    "editorWhitespace.foreground": "#FFFFFF14",
    "editorWidget.background": "#101010",
    "editorWidget.border": "#FFFFFF14",
    "focusBorder": "#282828",
    "gitDecoration.addedResourceForeground": "#59D499",
    "gitDecoration.conflictingResourceForeground": "#FF9217",
    "gitDecoration.deletedResourceForeground": "#FF6363",
    "gitDecoration.ignoredResourceForeground": "#FFFFFF33",
    "gitDecoration.modifiedResourceForeground": "#FFC531",
    "gitDecoration.untrackedResourceForeground": "#59D499",
    "input.background": "#151515",
    "input.border": "#FFFFFF1f",
    "input.foreground": "#FFFFFF",
    "input.placeholderForeground": "#FFFFFF66",
    "list.activeSelectionBackground": "#FFFFFF1f",
    "list.activeSelectionForeground": "#FFFFFF",
    "list.focusBackground": "#181818",
    "list.highlightForeground": "#4FA3F8",
    "list.hoverBackground": "#FFFFFF14",
    "list.inactiveSelectionBackground": "#FFFFFF14",
    "minimap.background": "#121212",
    "minimap.findMatchHighlight": "#FF921766",
    "minimap.selectionHighlight": "#FFFFFF33",
    "notifications.background": "#101010",
    "notifications.border": "#FFFFFF14",
    "panel.background": "#141414",
    "panel.border": "#FFFFFF14",
    "panelTitle.activeBorder": "#4FA3F8",
    "panelTitle.activeForeground": "#FFFFFFcc",
    "panelTitle.inactiveForeground": "#FFFFFF66",
    "peekView.border": "#4FA3F8",
    "peekViewEditor.background": "#101010",
    "peekViewResult.background": "#101010",
    "peekViewTitle.background": "#101010",
    "quickInput.background": "#101010",
    "quickInput.foreground": "#FFFFFF",
    "scrollbarSlider.activeBackground": "#FFFFFF2e",
    "scrollbarSlider.background": "#FFFFFF0f",
    "scrollbarSlider.hoverBackground": "#FFFFFF1f",
    "sideBar.background": "#101010",
    "sideBar.foreground": "#FFFFFF99",
    "sideBarTitle.foreground": "#FFFFFFcc",
    "statusBar.background": "#141414",
    "statusBar.debuggingBackground": "#FF6363",
    "statusBar.debuggingForeground": "#FFFFFF",
    "statusBar.foreground": "#FFFFFF99",
    "tab.activeBackground": "#141414",
    "tab.activeForeground": "#FFFFFF",
    "tab.border": "#161616",
    "tab.inactiveBackground": "#101010",
    "tab.inactiveForeground": "#FFFFFF80",
    "terminal.ansiBlack": "#000000",
    "terminal.ansiBlue": "#56C2FF",
    "terminal.ansiBrightBlack": "#FFFFFF66",
    "terminal.ansiBrightBlue": "#56C2FF",
    "terminal.ansiBrightCyan": "#56C2FF",
    "terminal.ansiBrightGreen": "#59D499",
    "terminal.ansiBrightMagenta": "#CF2F98",
    "terminal.ansiBrightRed": "#FF6363",
    "terminal.ansiBrightWhite": "#FFFFFF",
    "terminal.ansiBrightYellow": "#FFC531",
    "terminal.ansiCyan": "#56C2FF",
    "terminal.ansiGreen": "#59D499",
    "terminal.ansiMagenta": "#CF2F98",
    "terminal.ansiRed": "#FF6363",
    "terminal.ansiWhite": "#FFFFFF",
    "terminal.ansiYellow": "#FFC531",
    "terminal.background": "#141414",
    "terminal.foreground": "#FFFFFFcc",
    "titleBar.activeBackground": "#101010",
    "titleBar.activeForeground": "#FFFFFFcc",
    "titleBar.inactiveBackground": "#101010",
    "titleBar.inactiveForeground": "#FFFFFF66",
    "widget.shadow": "#00000066"
  },
  "name": "raycast-dark",
  "tokenColors": [
    {
      "scope": [
        "keyword.operator.accessor",
        "meta.group.braces.round.function.arguments",
        "meta.template.expression",
        "markup.fenced_code meta.embedded.block"
      ],
      "settings": {
        "foreground": "#FFFFFF"
      }
    },
    {
      "scope": "emphasis",
      "settings": {
        "fontStyle": "italic"
      }
    },
    {
      "scope": [
        "strong",
        "markup.heading.markdown",
        "markup.bold.markdown"
      ],
      "settings": {
        "fontStyle": "bold"
      }
    },
    {
      "scope": [
        "markup.italic.markdown"
      ],
      "settings": {
        "fontStyle": "italic"
      }
    },
    {
      "scope": "meta.link.inline.markdown",
      "settings": {
        "fontStyle": "underline",
        "foreground": "#4FA3F8"
      }
    },
    {
      "scope": [
        "string",
        "markup.fenced_code",
        "markup.inline",
        "string.quoted.docstring.multi.python"
      ],
      "settings": {
        "foreground": "#FF6363"
      }
    },
    {
      "scope": [
        "comment",
        "string.quoted.docstring.multi"
      ],
      "settings": {
        "foreground": "#666666"
      }
    },
    {
      "scope": [
        "constant.numeric",
        "constant.language",
        "constant.other.placeholder",
        "constant.character.format.placeholder",
        "variable.language.this",
        "variable.other.object",
        "variable.other.class",
        "variable.other.constant",
        "meta.property-name",
        "meta.property-value",
        "support"
      ],
      "settings": {
        "foreground": "#FFFFFF"
      }
    },
    {
      "scope": [
        "keyword",
        "storage.modifier",
        "storage.type",
        "storage.control.clojure",
        "entity.name.function.clojure",
        "entity.name.tag.yaml",
        "support.function.node",
        "support.type.property-name.json",
        "punctuation.separator.key-value",
        "punctuation.definition.template-expression"
      ],
      "settings": {
        "foreground": "#999999"
      }
    },
    {
      "scope": "variable.parameter.function",
      "settings": {
        "fontStyle": "italic",
        "foreground": "#CCCCCC"
      }
    },
    {
      "scope": [
        "support.function",
        "entity.name.type",
        "entity.other.inherited-class",
        "meta.function-call",
        "meta.instance.constructor",
        "entity.other.attribute-name",
        "entity.name.function",
        "constant.keyword.clojure"
      ],
      "settings": {
        "foreground": "#FF9217"
      }
    },
    {
      "scope": [
        "entity.name.tag",
        "support.class.component",
        "string.quoted",
        "string.regexp",
        "string.interpolated",
        "string.template",
        "string.unquoted.plain.out.yaml",
        "keyword.other.template"
      ],
      "settings": {
        "foreground": "#FF6363"
      }
    },
    {
      "scope": [
        "punctuation.definition.arguments",
        "punctuation.definition.dict",
        "punctuation.separator",
        "meta.function-call.arguments"
      ],
      "settings": {
        "foreground": "#999999"
      }
    },
    {
      "scope": [
        "markup.underline.link",
        "punctuation.definition.metadata.markdown"
      ],
      "settings": {
        "foreground": "#4FA3F8"
      }
    },
    {
      "scope": [
        "beginning.punctuation.definition.list.markdown"
      ],
      "settings": {
        "foreground": "#FF6363"
      }
    },
    {
      "scope": [
        "punctuation.definition.string.begin.markdown",
        "punctuation.definition.string.end.markdown",
        "string.other.link.title.markdown",
        "string.other.link.description.markdown"
      ],
      "settings": {
        "foreground": "#999999"
      }
    },
    {
      "scope": [
        "constant.numeric.decimal",
        "constant.language.boolean",
        "meta.var.exp.ts"
      ],
      "settings": {
        "foreground": "#FFFFFF"
      }
    },
    {
      "scope": [
        "support.variable.property"
      ],
      "settings": {
        "foreground": "#CCCCCC"
      }
    },
    {
      "scope": [
        "markup.inserted"
      ],
      "settings": {
        "foreground": "#59D499"
      }
    },
    {
      "scope": [
        "markup.deleted"
      ],
      "settings": {
        "foreground": "#FF6363"
      }
    },
    {
      "scope": [
        "markup.changed"
      ],
      "settings": {
        "foreground": "#FFC531"
      }
    }
  ],
  "type": "dark"
} as unknown as ThemeRegistration

export default theme
export const codexThemeSlug = "raycast-dark"
