// Generated by scripts/generate-codex-themes.ts from github-dark-default-75yHMRve.js, github-dark-default-BkV7rhaE.js, monokai-D3ByoViL.js, monokai-D3MspIcN.js, solarized-light-Cmik230K.js, solarized-light-THCCzuZK.js.
// Do not edit this file manually.
import type { ThemeRegistration } from 'shiki'

export const themes = {
  "github-dark-default": {
    "colors": {
      "activityBar.activeBorder": "#f78166",
      "activityBar.background": "#0d1117",
      "activityBar.border": "#30363d",
      "activityBar.foreground": "#e6edf3",
      "activityBar.inactiveForeground": "#7d8590",
      "activityBarBadge.background": "#1f6feb",
      "activityBarBadge.foreground": "#ffffff",
      "badge.background": "#1f6feb",
      "badge.foreground": "#ffffff",
      "breadcrumb.activeSelectionForeground": "#7d8590",
      "breadcrumb.focusForeground": "#e6edf3",
      "breadcrumb.foreground": "#7d8590",
      "breadcrumbPicker.background": "#161b22",
      "button.background": "#238636",
      "button.foreground": "#ffffff",
      "button.hoverBackground": "#2ea043",
      "button.secondaryBackground": "#282e33",
      "button.secondaryForeground": "#c9d1d9",
      "button.secondaryHoverBackground": "#30363d",
      "checkbox.background": "#161b22",
      "checkbox.border": "#30363d",
      "debugConsole.errorForeground": "#ffa198",
      "debugConsole.infoForeground": "#8b949e",
      "debugConsole.sourceForeground": "#e3b341",
      "debugConsole.warningForeground": "#d29922",
      "debugConsoleInputIcon.foreground": "#bc8cff",
      "debugIcon.breakpointForeground": "#f85149",
      "debugTokenExpression.boolean": "#56d364",
      "debugTokenExpression.error": "#ffa198",
      "debugTokenExpression.name": "#79c0ff",
      "debugTokenExpression.number": "#56d364",
      "debugTokenExpression.string": "#a5d6ff",
      "debugTokenExpression.value": "#a5d6ff",
      "debugToolBar.background": "#161b22",
      "descriptionForeground": "#7d8590",
      "diffEditor.insertedLineBackground": "#23863626",
      "diffEditor.insertedTextBackground": "#3fb9504d",
      "diffEditor.removedLineBackground": "#da363326",
      "diffEditor.removedTextBackground": "#ff7b724d",
      "dropdown.background": "#161b22",
      "dropdown.border": "#30363d",
      "dropdown.foreground": "#e6edf3",
      "dropdown.listBackground": "#161b22",
      "editor.background": "#0d1117",
      "editor.findMatchBackground": "#9e6a03",
      "editor.findMatchHighlightBackground": "#f2cc6080",
      "editor.focusedStackFrameHighlightBackground": "#2ea04366",
      "editor.foldBackground": "#6e76811a",
      "editor.foreground": "#e6edf3",
      "editor.lineHighlightBackground": "#6e76811a",
      "editor.linkedEditingBackground": "#2f81f712",
      "editor.selectionHighlightBackground": "#3fb95040",
      "editor.stackFrameHighlightBackground": "#bb800966",
      "editor.wordHighlightBackground": "#6e768180",
      "editor.wordHighlightBorder": "#6e768199",
      "editor.wordHighlightStrongBackground": "#6e76814d",
      "editor.wordHighlightStrongBorder": "#6e768199",
      "editorBracketHighlight.foreground1": "#79c0ff",
      "editorBracketHighlight.foreground2": "#56d364",
      "editorBracketHighlight.foreground3": "#e3b341",
      "editorBracketHighlight.foreground4": "#ffa198",
      "editorBracketHighlight.foreground5": "#ff9bce",
      "editorBracketHighlight.foreground6": "#d2a8ff",
      "editorBracketHighlight.unexpectedBracket.foreground": "#7d8590",
      "editorBracketMatch.background": "#3fb95040",
      "editorBracketMatch.border": "#3fb95099",
      "editorCursor.foreground": "#2f81f7",
      "editorGroup.border": "#30363d",
      "editorGroupHeader.tabsBackground": "#010409",
      "editorGroupHeader.tabsBorder": "#30363d",
      "editorGutter.addedBackground": "#2ea04366",
      "editorGutter.deletedBackground": "#f8514966",
      "editorGutter.modifiedBackground": "#bb800966",
      "editorIndentGuide.activeBackground": "#e6edf33d",
      "editorIndentGuide.background": "#e6edf31f",
      "editorInlayHint.background": "#8b949e33",
      "editorInlayHint.foreground": "#7d8590",
      "editorInlayHint.paramBackground": "#8b949e33",
      "editorInlayHint.paramForeground": "#7d8590",
      "editorInlayHint.typeBackground": "#8b949e33",
      "editorInlayHint.typeForeground": "#7d8590",
      "editorLineNumber.activeForeground": "#e6edf3",
      "editorLineNumber.foreground": "#6e7681",
      "editorOverviewRuler.border": "#010409",
      "editorWhitespace.foreground": "#484f58",
      "editorWidget.background": "#161b22",
      "errorForeground": "#f85149",
      "focusBorder": "#1f6feb",
      "foreground": "#e6edf3",
      "gitDecoration.addedResourceForeground": "#3fb950",
      "gitDecoration.conflictingResourceForeground": "#db6d28",
      "gitDecoration.deletedResourceForeground": "#f85149",
      "gitDecoration.ignoredResourceForeground": "#6e7681",
      "gitDecoration.modifiedResourceForeground": "#d29922",
      "gitDecoration.submoduleResourceForeground": "#7d8590",
      "gitDecoration.untrackedResourceForeground": "#3fb950",
      "icon.foreground": "#7d8590",
      "input.background": "#0d1117",
      "input.border": "#30363d",
      "input.foreground": "#e6edf3",
      "input.placeholderForeground": "#6e7681",
      "keybindingLabel.foreground": "#e6edf3",
      "list.activeSelectionBackground": "#6e768166",
      "list.activeSelectionForeground": "#e6edf3",
      "list.focusBackground": "#388bfd26",
      "list.focusForeground": "#e6edf3",
      "list.highlightForeground": "#2f81f7",
      "list.hoverBackground": "#6e76811a",
      "list.hoverForeground": "#e6edf3",
      "list.inactiveFocusBackground": "#388bfd26",
      "list.inactiveSelectionBackground": "#6e768166",
      "list.inactiveSelectionForeground": "#e6edf3",
      "minimapSlider.activeBackground": "#8b949e47",
      "minimapSlider.background": "#8b949e33",
      "minimapSlider.hoverBackground": "#8b949e3d",
      "notificationCenterHeader.background": "#161b22",
      "notificationCenterHeader.foreground": "#7d8590",
      "notifications.background": "#161b22",
      "notifications.border": "#30363d",
      "notifications.foreground": "#e6edf3",
      "notificationsErrorIcon.foreground": "#f85149",
      "notificationsInfoIcon.foreground": "#2f81f7",
      "notificationsWarningIcon.foreground": "#d29922",
      "panel.background": "#010409",
      "panel.border": "#30363d",
      "panelInput.border": "#30363d",
      "panelTitle.activeBorder": "#f78166",
      "panelTitle.activeForeground": "#e6edf3",
      "panelTitle.inactiveForeground": "#7d8590",
      "peekViewEditor.background": "#6e76811a",
      "peekViewEditor.matchHighlightBackground": "#bb800966",
      "peekViewResult.background": "#0d1117",
      "peekViewResult.matchHighlightBackground": "#bb800966",
      "pickerGroup.border": "#30363d",
      "pickerGroup.foreground": "#7d8590",
      "progressBar.background": "#1f6feb",
      "quickInput.background": "#161b22",
      "quickInput.foreground": "#e6edf3",
      "scrollbar.shadow": "#484f5833",
      "scrollbarSlider.activeBackground": "#8b949e47",
      "scrollbarSlider.background": "#8b949e33",
      "scrollbarSlider.hoverBackground": "#8b949e3d",
      "settings.headerForeground": "#e6edf3",
      "settings.modifiedItemIndicator": "#bb800966",
      "sideBar.background": "#010409",
      "sideBar.border": "#30363d",
      "sideBar.foreground": "#e6edf3",
      "sideBarSectionHeader.background": "#010409",
      "sideBarSectionHeader.border": "#30363d",
      "sideBarSectionHeader.foreground": "#e6edf3",
      "sideBarTitle.foreground": "#e6edf3",
      "statusBar.background": "#0d1117",
      "statusBar.border": "#30363d",
      "statusBar.debuggingBackground": "#da3633",
      "statusBar.debuggingForeground": "#ffffff",
      "statusBar.focusBorder": "#1f6feb80",
      "statusBar.foreground": "#7d8590",
      "statusBar.noFolderBackground": "#0d1117",
      "statusBarItem.activeBackground": "#e6edf31f",
      "statusBarItem.focusBorder": "#1f6feb",
      "statusBarItem.hoverBackground": "#e6edf314",
      "statusBarItem.prominentBackground": "#6e768166",
      "statusBarItem.remoteBackground": "#30363d",
      "statusBarItem.remoteForeground": "#e6edf3",
      "symbolIcon.arrayForeground": "#f0883e",
      "symbolIcon.booleanForeground": "#58a6ff",
      "symbolIcon.classForeground": "#f0883e",
      "symbolIcon.colorForeground": "#79c0ff",
      "symbolIcon.constantForeground": [
        "#aff5b4",
        "#7ee787",
        "#56d364",
        "#3fb950",
        "#2ea043",
        "#238636",
        "#196c2e",
        "#0f5323",
        "#033a16",
        "#04260f"
      ],
      "symbolIcon.constructorForeground": "#d2a8ff",
      "symbolIcon.enumeratorForeground": "#f0883e",
      "symbolIcon.enumeratorMemberForeground": "#58a6ff",
      "symbolIcon.eventForeground": "#6e7681",
      "symbolIcon.fieldForeground": "#f0883e",
      "symbolIcon.fileForeground": "#d29922",
      "symbolIcon.folderForeground": "#d29922",
      "symbolIcon.functionForeground": "#bc8cff",
      "symbolIcon.interfaceForeground": "#f0883e",
      "symbolIcon.keyForeground": "#58a6ff",
      "symbolIcon.keywordForeground": "#ff7b72",
      "symbolIcon.methodForeground": "#bc8cff",
      "symbolIcon.moduleForeground": "#ff7b72",
      "symbolIcon.namespaceForeground": "#ff7b72",
      "symbolIcon.nullForeground": "#58a6ff",
      "symbolIcon.numberForeground": "#3fb950",
      "symbolIcon.objectForeground": "#f0883e",
      "symbolIcon.operatorForeground": "#79c0ff",
      "symbolIcon.packageForeground": "#f0883e",
      "symbolIcon.propertyForeground": "#f0883e",
      "symbolIcon.referenceForeground": "#58a6ff",
      "symbolIcon.snippetForeground": "#58a6ff",
      "symbolIcon.stringForeground": "#79c0ff",
      "symbolIcon.structForeground": "#f0883e",
      "symbolIcon.textForeground": "#79c0ff",
      "symbolIcon.typeParameterForeground": "#79c0ff",
      "symbolIcon.unitForeground": "#58a6ff",
      "symbolIcon.variableForeground": "#f0883e",
      "tab.activeBackground": "#0d1117",
      "tab.activeBorder": "#0d1117",
      "tab.activeBorderTop": "#f78166",
      "tab.activeForeground": "#e6edf3",
      "tab.border": "#30363d",
      "tab.hoverBackground": "#0d1117",
      "tab.inactiveBackground": "#010409",
      "tab.inactiveForeground": "#7d8590",
      "tab.unfocusedActiveBorder": "#0d1117",
      "tab.unfocusedActiveBorderTop": "#30363d",
      "tab.unfocusedHoverBackground": "#6e76811a",
      "terminal.ansiBlack": "#484f58",
      "terminal.ansiBlue": "#58a6ff",
      "terminal.ansiBrightBlack": "#6e7681",
      "terminal.ansiBrightBlue": "#79c0ff",
      "terminal.ansiBrightCyan": "#56d4dd",
      "terminal.ansiBrightGreen": "#56d364",
      "terminal.ansiBrightMagenta": "#d2a8ff",
      "terminal.ansiBrightRed": "#ffa198",
      "terminal.ansiBrightWhite": "#ffffff",
      "terminal.ansiBrightYellow": "#e3b341",
      "terminal.ansiCyan": "#39c5cf",
      "terminal.ansiGreen": "#3fb950",
      "terminal.ansiMagenta": "#bc8cff",
      "terminal.ansiRed": "#ff7b72",
      "terminal.ansiWhite": "#b1bac4",
      "terminal.ansiYellow": "#d29922",
      "terminal.foreground": "#e6edf3",
      "textBlockQuote.background": "#010409",
      "textBlockQuote.border": "#30363d",
      "textCodeBlock.background": "#6e768166",
      "textLink.activeForeground": "#2f81f7",
      "textLink.foreground": "#2f81f7",
      "textPreformat.background": "#6e768166",
      "textPreformat.foreground": "#7d8590",
      "textSeparator.foreground": "#21262d",
      "titleBar.activeBackground": "#0d1117",
      "titleBar.activeForeground": "#7d8590",
      "titleBar.border": "#30363d",
      "titleBar.inactiveBackground": "#010409",
      "titleBar.inactiveForeground": "#7d8590",
      "tree.indentGuidesStroke": "#21262d",
      "welcomePage.buttonBackground": "#21262d",
      "welcomePage.buttonHoverBackground": "#30363d"
    },
    "name": "github-dark-default",
    "semanticHighlighting": true,
    "tokenColors": [
      {
        "scope": [
          "comment",
          "punctuation.definition.comment",
          "string.comment"
        ],
        "settings": {
          "foreground": "#8b949e"
        }
      },
      {
        "scope": [
          "constant.other.placeholder",
          "constant.character"
        ],
        "settings": {
          "foreground": "#ff7b72"
        }
      },
      {
        "scope": [
          "constant",
          "entity.name.constant",
          "variable.other.constant",
          "variable.other.enummember",
          "variable.language",
          "entity"
        ],
        "settings": {
          "foreground": "#79c0ff"
        }
      },
      {
        "scope": [
          "entity.name",
          "meta.export.default",
          "meta.definition.variable"
        ],
        "settings": {
          "foreground": "#ffa657"
        }
      },
      {
        "scope": [
          "variable.parameter.function",
          "meta.jsx.children",
          "meta.block",
          "meta.tag.attributes",
          "entity.name.constant",
          "meta.object.member",
          "meta.embedded.expression"
        ],
        "settings": {
          "foreground": "#e6edf3"
        }
      },
      {
        "scope": "entity.name.function",
        "settings": {
          "foreground": "#d2a8ff"
        }
      },
      {
        "scope": [
          "entity.name.tag",
          "support.class.component"
        ],
        "settings": {
          "foreground": "#7ee787"
        }
      },
      {
        "scope": "keyword",
        "settings": {
          "foreground": "#ff7b72"
        }
      },
      {
        "scope": [
          "storage",
          "storage.type"
        ],
        "settings": {
          "foreground": "#ff7b72"
        }
      },
      {
        "scope": [
          "storage.modifier.package",
          "storage.modifier.import",
          "storage.type.java"
        ],
        "settings": {
          "foreground": "#e6edf3"
        }
      },
      {
        "scope": [
          "string",
          "string punctuation.section.embedded source"
        ],
        "settings": {
          "foreground": "#a5d6ff"
        }
      },
      {
        "scope": "support",
        "settings": {
          "foreground": "#79c0ff"
        }
      },
      {
        "scope": "meta.property-name",
        "settings": {
          "foreground": "#79c0ff"
        }
      },
      {
        "scope": "variable",
        "settings": {
          "foreground": "#ffa657"
        }
      },
      {
        "scope": "variable.other",
        "settings": {
          "foreground": "#e6edf3"
        }
      },
      {
        "scope": "invalid.broken",
        "settings": {
          "fontStyle": "italic",
          "foreground": "#ffa198"
        }
      },
      {
        "scope": "invalid.deprecated",
        "settings": {
          "fontStyle": "italic",
          "foreground": "#ffa198"
        }
      },
      {
        "scope": "invalid.illegal",
        "settings": {
          "fontStyle": "italic",
          "foreground": "#ffa198"
        }
      },
      {
        "scope": "invalid.unimplemented",
        "settings": {
          "fontStyle": "italic",
          "foreground": "#ffa198"
        }
      },
      {
        "scope": "carriage-return",
        "settings": {
          "background": "#ff7b72",
          "content": "^M",
          "fontStyle": "italic underline",
          "foreground": "#f0f6fc"
        }
      },
      {
        "scope": "message.error",
        "settings": {
          "foreground": "#ffa198"
        }
      },
      {
        "scope": "string variable",
        "settings": {
          "foreground": "#79c0ff"
        }
      },
      {
        "scope": [
          "source.regexp",
          "string.regexp"
        ],
        "settings": {
          "foreground": "#a5d6ff"
        }
      },
      {
        "scope": [
          "string.regexp.character-class",
          "string.regexp constant.character.escape",
          "string.regexp source.ruby.embedded",
          "string.regexp string.regexp.arbitrary-repitition"
        ],
        "settings": {
          "foreground": "#a5d6ff"
        }
      },
      {
        "scope": "string.regexp constant.character.escape",
        "settings": {
          "fontStyle": "bold",
          "foreground": "#7ee787"
        }
      },
      {
        "scope": "support.constant",
        "settings": {
          "foreground": "#79c0ff"
        }
      },
      {
        "scope": "support.variable",
        "settings": {
          "foreground": "#79c0ff"
        }
      },
      {
        "scope": "support.type.property-name.json",
        "settings": {
          "foreground": "#7ee787"
        }
      },
      {
        "scope": "meta.module-reference",
        "settings": {
          "foreground": "#79c0ff"
        }
      },
      {
        "scope": "punctuation.definition.list.begin.markdown",
        "settings": {
          "foreground": "#ffa657"
        }
      },
      {
        "scope": [
          "markup.heading",
          "markup.heading entity.name"
        ],
        "settings": {
          "fontStyle": "bold",
          "foreground": "#79c0ff"
        }
      },
      {
        "scope": "markup.quote",
        "settings": {
          "foreground": "#7ee787"
        }
      },
      {
        "scope": "markup.italic",
        "settings": {
          "fontStyle": "italic",
          "foreground": "#e6edf3"
        }
      },
      {
        "scope": "markup.bold",
        "settings": {
          "fontStyle": "bold",
          "foreground": "#e6edf3"
        }
      },
      {
        "scope": [
          "markup.underline"
        ],
        "settings": {
          "fontStyle": "underline"
        }
      },
      {
        "scope": [
          "markup.strikethrough"
        ],
        "settings": {
          "fontStyle": "strikethrough"
        }
      },
      {
        "scope": "markup.inline.raw",
        "settings": {
          "foreground": "#79c0ff"
        }
      },
      {
        "scope": [
          "markup.deleted",
          "meta.diff.header.from-file",
          "punctuation.definition.deleted"
        ],
        "settings": {
          "background": "#490202",
          "foreground": "#ffa198"
        }
      },
      {
        "scope": [
          "punctuation.section.embedded"
        ],
        "settings": {
          "foreground": "#ff7b72"
        }
      },
      {
        "scope": [
          "markup.inserted",
          "meta.diff.header.to-file",
          "punctuation.definition.inserted"
        ],
        "settings": {
          "background": "#04260f",
          "foreground": "#7ee787"
        }
      },
      {
        "scope": [
          "markup.changed",
          "punctuation.definition.changed"
        ],
        "settings": {
          "background": "#5a1e02",
          "foreground": "#ffa657"
        }
      },
      {
        "scope": [
          "markup.ignored",
          "markup.untracked"
        ],
        "settings": {
          "background": "#79c0ff",
          "foreground": "#161b22"
        }
      },
      {
        "scope": "meta.diff.range",
        "settings": {
          "fontStyle": "bold",
          "foreground": "#d2a8ff"
        }
      },
      {
        "scope": "meta.diff.header",
        "settings": {
          "foreground": "#79c0ff"
        }
      },
      {
        "scope": "meta.separator",
        "settings": {
          "fontStyle": "bold",
          "foreground": "#79c0ff"
        }
      },
      {
        "scope": "meta.output",
        "settings": {
          "foreground": "#79c0ff"
        }
      },
      {
        "scope": [
          "brackethighlighter.tag",
          "brackethighlighter.curly",
          "brackethighlighter.round",
          "brackethighlighter.square",
          "brackethighlighter.angle",
          "brackethighlighter.quote"
        ],
        "settings": {
          "foreground": "#8b949e"
        }
      },
      {
        "scope": "brackethighlighter.unmatched",
        "settings": {
          "foreground": "#ffa198"
        }
      },
      {
        "scope": [
          "constant.other.reference.link",
          "string.other.link"
        ],
        "settings": {
          "foreground": "#a5d6ff"
        }
      }
    ],
    "type": "dark"
  },
  "monokai": {
    "colors": {
      "activityBar.background": "#272822",
      "activityBar.foreground": "#f8f8f2",
      "badge.background": "#75715E",
      "badge.foreground": "#f8f8f2",
      "button.background": "#75715E",
      "debugToolBar.background": "#1e1f1c",
      "diffEditor.insertedTextBackground": "#4b661680",
      "diffEditor.removedTextBackground": "#90274A70",
      "dropdown.background": "#414339",
      "dropdown.listBackground": "#1e1f1c",
      "editor.background": "#272822",
      "editor.foreground": "#f8f8f2",
      "editor.lineHighlightBackground": "#3e3d32",
      "editor.selectionBackground": "#878b9180",
      "editor.selectionHighlightBackground": "#575b6180",
      "editor.wordHighlightBackground": "#4a4a7680",
      "editor.wordHighlightStrongBackground": "#6a6a9680",
      "editorCursor.foreground": "#f8f8f0",
      "editorGroup.border": "#34352f",
      "editorGroup.dropBackground": "#41433980",
      "editorGroupHeader.tabsBackground": "#1e1f1c",
      "editorHoverWidget.background": "#414339",
      "editorHoverWidget.border": "#75715E",
      "editorIndentGuide.activeBackground": "#767771",
      "editorIndentGuide.background": "#464741",
      "editorLineNumber.activeForeground": "#c2c2bf",
      "editorLineNumber.foreground": "#90908a",
      "editorSuggestWidget.background": "#272822",
      "editorSuggestWidget.border": "#75715E",
      "editorWhitespace.foreground": "#464741",
      "editorWidget.background": "#1e1f1c",
      "focusBorder": "#99947c",
      "input.background": "#414339",
      "inputOption.activeBorder": "#75715E",
      "inputValidation.errorBackground": "#90274A",
      "inputValidation.errorBorder": "#f92672",
      "inputValidation.infoBackground": "#546190",
      "inputValidation.infoBorder": "#819aff",
      "inputValidation.warningBackground": "#848528",
      "inputValidation.warningBorder": "#e2e22e",
      "list.activeSelectionBackground": "#75715E",
      "list.dropBackground": "#414339",
      "list.highlightForeground": "#f8f8f2",
      "list.hoverBackground": "#3e3d32",
      "list.inactiveSelectionBackground": "#414339",
      "menu.background": "#1e1f1c",
      "menu.foreground": "#cccccc",
      "minimap.selectionHighlight": "#878b9180",
      "panel.border": "#414339",
      "panelTitle.activeBorder": "#75715E",
      "panelTitle.activeForeground": "#f8f8f2",
      "panelTitle.inactiveForeground": "#75715E",
      "peekView.border": "#75715E",
      "peekViewEditor.background": "#272822",
      "peekViewEditor.matchHighlightBackground": "#75715E",
      "peekViewResult.background": "#1e1f1c",
      "peekViewResult.matchHighlightBackground": "#75715E",
      "peekViewResult.selectionBackground": "#414339",
      "peekViewTitle.background": "#1e1f1c",
      "pickerGroup.foreground": "#75715E",
      "ports.iconRunningProcessForeground": "#ccccc7",
      "progressBar.background": "#75715E",
      "quickInputList.focusBackground": "#414339",
      "selection.background": "#878b9180",
      "settings.focusedRowBackground": "#4143395A",
      "sideBar.background": "#1e1f1c",
      "sideBarSectionHeader.background": "#272822",
      "statusBar.background": "#414339",
      "statusBar.debuggingBackground": "#75715E",
      "statusBar.noFolderBackground": "#414339",
      "statusBarItem.remoteBackground": "#AC6218",
      "tab.border": "#1e1f1c",
      "tab.inactiveBackground": "#34352f",
      "tab.inactiveForeground": "#ccccc7",
      "tab.lastPinnedBorder": "#414339",
      "terminal.ansiBlack": "#333333",
      "terminal.ansiBlue": "#6A7EC8",
      "terminal.ansiBrightBlack": "#666666",
      "terminal.ansiBrightBlue": "#819aff",
      "terminal.ansiBrightCyan": "#66D9EF",
      "terminal.ansiBrightGreen": "#A6E22E",
      "terminal.ansiBrightMagenta": "#AE81FF",
      "terminal.ansiBrightRed": "#f92672",
      "terminal.ansiBrightWhite": "#f8f8f2",
      "terminal.ansiBrightYellow": "#e2e22e",
      "terminal.ansiCyan": "#56ADBC",
      "terminal.ansiGreen": "#86B42B",
      "terminal.ansiMagenta": "#8C6BC8",
      "terminal.ansiRed": "#C4265E",
      "terminal.ansiWhite": "#e3e3dd",
      "terminal.ansiYellow": "#B3B42B",
      "titleBar.activeBackground": "#1e1f1c",
      "widget.shadow": "#00000098"
    },
    "name": "monokai",
    "semanticHighlighting": true,
    "tokenColors": [
      {
        "settings": {
          "foreground": "#F8F8F2"
        }
      },
      {
        "scope": [
          "meta.embedded",
          "source.groovy.embedded",
          "string meta.image.inline.markdown",
          "variable.legacy.builtin.python"
        ],
        "settings": {
          "foreground": "#F8F8F2"
        }
      },
      {
        "scope": "comment",
        "settings": {
          "foreground": "#88846f"
        }
      },
      {
        "scope": "string",
        "settings": {
          "foreground": "#E6DB74"
        }
      },
      {
        "scope": [
          "punctuation.definition.template-expression",
          "punctuation.section.embedded"
        ],
        "settings": {
          "foreground": "#F92672"
        }
      },
      {
        "scope": [
          "meta.template.expression"
        ],
        "settings": {
          "foreground": "#F8F8F2"
        }
      },
      {
        "scope": "constant.numeric",
        "settings": {
          "foreground": "#AE81FF"
        }
      },
      {
        "scope": "constant.language",
        "settings": {
          "foreground": "#AE81FF"
        }
      },
      {
        "scope": "constant.character, constant.other",
        "settings": {
          "foreground": "#AE81FF"
        }
      },
      {
        "scope": "variable",
        "settings": {
          "fontStyle": "",
          "foreground": "#F8F8F2"
        }
      },
      {
        "scope": "keyword",
        "settings": {
          "foreground": "#F92672"
        }
      },
      {
        "scope": "storage",
        "settings": {
          "fontStyle": "",
          "foreground": "#F92672"
        }
      },
      {
        "scope": "storage.type",
        "settings": {
          "fontStyle": "italic",
          "foreground": "#66D9EF"
        }
      },
      {
        "scope": "entity.name.type, entity.name.class, entity.name.namespace, entity.name.scope-resolution",
        "settings": {
          "fontStyle": "underline",
          "foreground": "#A6E22E"
        }
      },
      {
        "scope": [
          "entity.other.inherited-class",
          "punctuation.separator.namespace.ruby"
        ],
        "settings": {
          "fontStyle": "italic underline",
          "foreground": "#A6E22E"
        }
      },
      {
        "scope": "entity.name.function",
        "settings": {
          "fontStyle": "",
          "foreground": "#A6E22E"
        }
      },
      {
        "scope": "variable.parameter",
        "settings": {
          "fontStyle": "italic",
          "foreground": "#FD971F"
        }
      },
      {
        "scope": "entity.name.tag",
        "settings": {
          "fontStyle": "",
          "foreground": "#F92672"
        }
      },
      {
        "scope": "entity.other.attribute-name",
        "settings": {
          "fontStyle": "",
          "foreground": "#A6E22E"
        }
      },
      {
        "scope": "support.function",
        "settings": {
          "fontStyle": "",
          "foreground": "#66D9EF"
        }
      },
      {
        "scope": "support.constant",
        "settings": {
          "fontStyle": "",
          "foreground": "#66D9EF"
        }
      },
      {
        "scope": "support.type, support.class",
        "settings": {
          "fontStyle": "italic",
          "foreground": "#66D9EF"
        }
      },
      {
        "scope": "support.other.variable",
        "settings": {
          "fontStyle": ""
        }
      },
      {
        "scope": "invalid",
        "settings": {
          "fontStyle": "",
          "foreground": "#F44747"
        }
      },
      {
        "scope": "invalid.deprecated",
        "settings": {
          "foreground": "#F44747"
        }
      },
      {
        "scope": "meta.structure.dictionary.json string.quoted.double.json",
        "settings": {
          "foreground": "#CFCFC2"
        }
      },
      {
        "scope": "meta.diff, meta.diff.header",
        "settings": {
          "foreground": "#75715E"
        }
      },
      {
        "scope": "markup.deleted",
        "settings": {
          "foreground": "#F92672"
        }
      },
      {
        "scope": "markup.inserted",
        "settings": {
          "foreground": "#A6E22E"
        }
      },
      {
        "scope": "markup.changed",
        "settings": {
          "foreground": "#E6DB74"
        }
      },
      {
        "scope": "constant.numeric.line-number.find-in-files - match",
        "settings": {
          "foreground": "#AE81FFA0"
        }
      },
      {
        "scope": "entity.name.filename.find-in-files",
        "settings": {
          "foreground": "#E6DB74"
        }
      },
      {
        "scope": "markup.quote",
        "settings": {
          "foreground": "#F92672"
        }
      },
      {
        "scope": "markup.list",
        "settings": {
          "foreground": "#E6DB74"
        }
      },
      {
        "scope": "markup.bold, markup.italic",
        "settings": {
          "foreground": "#66D9EF"
        }
      },
      {
        "scope": "markup.inline.raw",
        "settings": {
          "fontStyle": "",
          "foreground": "#FD971F"
        }
      },
      {
        "scope": "markup.heading",
        "settings": {
          "foreground": "#A6E22E"
        }
      },
      {
        "scope": "markup.heading.setext",
        "settings": {
          "fontStyle": "bold",
          "foreground": "#A6E22E"
        }
      },
      {
        "scope": "markup.heading.markdown",
        "settings": {
          "fontStyle": "bold"
        }
      },
      {
        "scope": "markup.quote.markdown",
        "settings": {
          "fontStyle": "italic",
          "foreground": "#75715E"
        }
      },
      {
        "scope": "markup.bold.markdown",
        "settings": {
          "fontStyle": "bold"
        }
      },
      {
        "scope": "string.other.link.title.markdown,string.other.link.description.markdown",
        "settings": {
          "foreground": "#AE81FF"
        }
      },
      {
        "scope": "markup.underline.link.markdown,markup.underline.link.image.markdown",
        "settings": {
          "foreground": "#E6DB74"
        }
      },
      {
        "scope": "markup.italic.markdown",
        "settings": {
          "fontStyle": "italic"
        }
      },
      {
        "scope": "markup.strikethrough",
        "settings": {
          "fontStyle": "strikethrough"
        }
      },
      {
        "scope": "markup.list.unnumbered.markdown, markup.list.numbered.markdown",
        "settings": {
          "foreground": "#f8f8f2"
        }
      },
      {
        "scope": [
          "punctuation.definition.list.begin.markdown"
        ],
        "settings": {
          "foreground": "#A6E22E"
        }
      },
      {
        "scope": "token.info-token",
        "settings": {
          "foreground": "#6796e6"
        }
      },
      {
        "scope": "token.warn-token",
        "settings": {
          "foreground": "#cd9731"
        }
      },
      {
        "scope": "token.error-token",
        "settings": {
          "foreground": "#f44747"
        }
      },
      {
        "scope": "token.debug-token",
        "settings": {
          "foreground": "#b267e6"
        }
      },
      {
        "scope": "variable.language",
        "settings": {
          "foreground": "#FD971F"
        }
      }
    ],
    "type": "dark"
  },
  "solarized-light": {
    "colors": {
      "activityBar.background": "#DDD6C1",
      "activityBar.foreground": "#584c27",
      "activityBarBadge.background": "#B58900",
      "badge.background": "#B58900AA",
      "button.background": "#AC9D57",
      "debugExceptionWidget.background": "#DDD6C1",
      "debugExceptionWidget.border": "#AB395B",
      "debugToolBar.background": "#DDD6C1",
      "dropdown.background": "#EEE8D5",
      "dropdown.border": "#D3AF86",
      "editor.background": "#FDF6E3",
      "editor.foreground": "#657B83",
      "editor.lineHighlightBackground": "#EEE8D5",
      "editor.selectionBackground": "#EEE8D5",
      "editorCursor.foreground": "#657B83",
      "editorGroup.border": "#DDD6C1",
      "editorGroup.dropBackground": "#DDD6C1AA",
      "editorGroupHeader.tabsBackground": "#D9D2C2",
      "editorHoverWidget.background": "#CCC4B0",
      "editorIndentGuide.activeBackground": "#081E2580",
      "editorIndentGuide.background": "#586E7580",
      "editorLineNumber.activeForeground": "#567983",
      "editorWhitespace.foreground": "#586E7580",
      "editorWidget.background": "#EEE8D5",
      "extensionButton.prominentBackground": "#b58900",
      "extensionButton.prominentHoverBackground": "#584c27aa",
      "focusBorder": "#b49471",
      "input.background": "#DDD6C1",
      "input.foreground": "#586E75",
      "input.placeholderForeground": "#586E75AA",
      "inputOption.activeBorder": "#D3AF86",
      "list.activeSelectionBackground": "#DFCA88",
      "list.activeSelectionForeground": "#6C6C6C",
      "list.highlightForeground": "#B58900",
      "list.hoverBackground": "#DFCA8844",
      "list.inactiveSelectionBackground": "#D1CBB8",
      "minimap.selectionHighlight": "#EEE8D5",
      "notebook.cellEditorBackground": "#F7F0E0",
      "panel.border": "#DDD6C1",
      "peekView.border": "#B58900",
      "peekViewEditor.background": "#FFFBF2",
      "peekViewEditor.matchHighlightBackground": "#7744AA40",
      "peekViewResult.background": "#EEE8D5",
      "peekViewTitle.background": "#EEE8D5",
      "pickerGroup.border": "#2AA19899",
      "pickerGroup.foreground": "#2AA19899",
      "ports.iconRunningProcessForeground": "#2AA19899",
      "progressBar.background": "#B58900",
      "quickInputList.focusBackground": "#DFCA8866",
      "selection.background": "#878b9180",
      "sideBar.background": "#EEE8D5",
      "sideBarTitle.foreground": "#586E75",
      "statusBar.background": "#EEE8D5",
      "statusBar.debuggingBackground": "#EEE8D5",
      "statusBar.foreground": "#586E75",
      "statusBar.noFolderBackground": "#EEE8D5",
      "statusBarItem.prominentBackground": "#DDD6C1",
      "statusBarItem.prominentHoverBackground": "#DDD6C199",
      "statusBarItem.remoteBackground": "#AC9D57",
      "tab.activeBackground": "#FDF6E3",
      "tab.activeModifiedBorder": "#cb4b16",
      "tab.border": "#DDD6C1",
      "tab.inactiveBackground": "#D3CBB7",
      "tab.inactiveForeground": "#586E75",
      "tab.lastPinnedBorder": "#FDF6E3",
      "terminal.ansiBlack": "#073642",
      "terminal.ansiBlue": "#268bd2",
      "terminal.ansiBrightBlack": "#002b36",
      "terminal.ansiBrightBlue": "#839496",
      "terminal.ansiBrightCyan": "#93a1a1",
      "terminal.ansiBrightGreen": "#586e75",
      "terminal.ansiBrightMagenta": "#6c71c4",
      "terminal.ansiBrightRed": "#cb4b16",
      "terminal.ansiBrightWhite": "#fdf6e3",
      "terminal.ansiBrightYellow": "#657b83",
      "terminal.ansiCyan": "#2aa198",
      "terminal.ansiGreen": "#859900",
      "terminal.ansiMagenta": "#d33682",
      "terminal.ansiRed": "#dc322f",
      "terminal.ansiWhite": "#eee8d5",
      "terminal.ansiYellow": "#b58900",
      "terminal.background": "#FDF6E3",
      "titleBar.activeBackground": "#EEE8D5",
      "walkThrough.embeddedEditorBackground": "#00000014"
    },
    "name": "solarized-light",
    "semanticHighlighting": true,
    "tokenColors": [
      {
        "settings": {
          "foreground": "#657B83"
        }
      },
      {
        "scope": [
          "meta.embedded",
          "source.groovy.embedded",
          "string meta.image.inline.markdown",
          "variable.legacy.builtin.python"
        ],
        "settings": {
          "foreground": "#657B83"
        }
      },
      {
        "scope": "comment",
        "settings": {
          "fontStyle": "italic",
          "foreground": "#93A1A1"
        }
      },
      {
        "scope": "string",
        "settings": {
          "foreground": "#2AA198"
        }
      },
      {
        "scope": "string.regexp",
        "settings": {
          "foreground": "#DC322F"
        }
      },
      {
        "scope": "constant.numeric",
        "settings": {
          "foreground": "#D33682"
        }
      },
      {
        "scope": [
          "variable.language",
          "variable.other"
        ],
        "settings": {
          "foreground": "#268BD2"
        }
      },
      {
        "scope": "keyword",
        "settings": {
          "foreground": "#859900"
        }
      },
      {
        "scope": "storage",
        "settings": {
          "fontStyle": "bold",
          "foreground": "#586E75"
        }
      },
      {
        "scope": [
          "entity.name.class",
          "entity.name.type",
          "entity.name.namespace",
          "entity.name.scope-resolution"
        ],
        "settings": {
          "fontStyle": "",
          "foreground": "#CB4B16"
        }
      },
      {
        "scope": "entity.name.function",
        "settings": {
          "foreground": "#268BD2"
        }
      },
      {
        "scope": "punctuation.definition.variable",
        "settings": {
          "foreground": "#859900"
        }
      },
      {
        "scope": [
          "punctuation.section.embedded.begin",
          "punctuation.section.embedded.end"
        ],
        "settings": {
          "foreground": "#DC322F"
        }
      },
      {
        "scope": [
          "constant.language",
          "meta.preprocessor"
        ],
        "settings": {
          "foreground": "#B58900"
        }
      },
      {
        "scope": [
          "support.function.construct",
          "keyword.other.new"
        ],
        "settings": {
          "foreground": "#CB4B16"
        }
      },
      {
        "scope": [
          "constant.character",
          "constant.other"
        ],
        "settings": {
          "foreground": "#CB4B16"
        }
      },
      {
        "scope": [
          "entity.other.inherited-class",
          "punctuation.separator.namespace.ruby"
        ],
        "settings": {
          "foreground": "#6C71C4"
        }
      },
      {
        "scope": "variable.parameter",
        "settings": {}
      },
      {
        "scope": "entity.name.tag",
        "settings": {
          "foreground": "#268BD2"
        }
      },
      {
        "scope": "punctuation.definition.tag",
        "settings": {
          "foreground": "#93A1A1"
        }
      },
      {
        "scope": "entity.other.attribute-name",
        "settings": {
          "foreground": "#93A1A1"
        }
      },
      {
        "scope": "support.function",
        "settings": {
          "foreground": "#268BD2"
        }
      },
      {
        "scope": "punctuation.separator.continuation",
        "settings": {
          "foreground": "#DC322F"
        }
      },
      {
        "scope": [
          "support.constant",
          "support.variable"
        ],
        "settings": {}
      },
      {
        "scope": [
          "support.type",
          "support.class"
        ],
        "settings": {
          "foreground": "#859900"
        }
      },
      {
        "scope": "support.type.exception",
        "settings": {
          "foreground": "#CB4B16"
        }
      },
      {
        "scope": "support.other.variable",
        "settings": {}
      },
      {
        "scope": "invalid",
        "settings": {
          "foreground": "#DC322F"
        }
      },
      {
        "scope": [
          "meta.diff",
          "meta.diff.header"
        ],
        "settings": {
          "fontStyle": "italic",
          "foreground": "#268BD2"
        }
      },
      {
        "scope": "markup.deleted",
        "settings": {
          "fontStyle": "",
          "foreground": "#DC322F"
        }
      },
      {
        "scope": "markup.changed",
        "settings": {
          "fontStyle": "",
          "foreground": "#CB4B16"
        }
      },
      {
        "scope": "markup.inserted",
        "settings": {
          "foreground": "#859900"
        }
      },
      {
        "scope": "markup.quote",
        "settings": {
          "foreground": "#859900"
        }
      },
      {
        "scope": "markup.list",
        "settings": {
          "foreground": "#B58900"
        }
      },
      {
        "scope": [
          "markup.bold",
          "markup.italic"
        ],
        "settings": {
          "foreground": "#D33682"
        }
      },
      {
        "scope": "markup.bold",
        "settings": {
          "fontStyle": "bold"
        }
      },
      {
        "scope": "markup.italic",
        "settings": {
          "fontStyle": "italic"
        }
      },
      {
        "scope": "markup.strikethrough",
        "settings": {
          "fontStyle": "strikethrough"
        }
      },
      {
        "scope": "markup.inline.raw",
        "settings": {
          "fontStyle": "",
          "foreground": "#2AA198"
        }
      },
      {
        "scope": "markup.heading",
        "settings": {
          "fontStyle": "bold",
          "foreground": "#268BD2"
        }
      },
      {
        "scope": "markup.heading.setext",
        "settings": {
          "fontStyle": "",
          "foreground": "#268BD2"
        }
      }
    ],
    "type": "light"
  },
} as unknown as Readonly<Record<string, ThemeRegistration>>
