// Generated by scripts/generate-codex-themes.ts from oscurange-CGm630nf.js, proof-light-BQdbajck.js.
// Do not edit this file manually.
import type { ThemeRegistration } from 'shiki'

export const themes = {
  "oscurange": {
    "$schema": "vscode://schemas/color-theme",
    "colors": {
      "editor.background": "#0B0B0F",
      "editor.foreground": "#E6E6E6",
      "editorCursor.foreground": "#F9B98C"
    },
    "name": "oscurange",
    "tokenColors": [
      {
        "name": "Default foreground",
        "scope": [
          "source",
          "text"
        ],
        "settings": {
          "foreground": "#E6E6E6"
        }
      },
      {
        "name": "Comments",
        "scope": [
          "comment",
          "punctuation.definition.comment"
        ],
        "settings": {
          "foreground": "#46474F"
        }
      },
      {
        "name": "Constants and enums",
        "scope": [
          "constant",
          "constant.language",
          "constant.other",
          "entity.name.enum",
          "support.constant"
        ],
        "settings": {
          "foreground": "#F9B98C"
        }
      },
      {
        "name": "Strings",
        "scope": [
          "string",
          "string.quoted"
        ],
        "settings": {
          "foreground": "#E6E6E6"
        }
      },
      {
        "name": "Numbers and booleans",
        "scope": [
          "constant.numeric",
          "constant.language.boolean"
        ],
        "settings": {
          "foreground": "#F9B98C"
        }
      },
      {
        "name": "Functions and constructors",
        "scope": [
          "entity.name.function",
          "meta.function-call",
          "support.function",
          "variable.function",
          "entity.name.function.constructor"
        ],
        "settings": {
          "foreground": "#F9B98C"
        }
      },
      {
        "name": "Keywords and operators",
        "scope": [
          "keyword",
          "keyword.operator",
          "storage",
          "storage.type"
        ],
        "settings": {
          "foreground": "#9099A1"
        }
      },
      {
        "name": "Punctuation",
        "scope": [
          "punctuation",
          "punctuation.bracket",
          "punctuation.separator",
          "punctuation.definition.list.begin"
        ],
        "settings": {
          "foreground": "#5C6974"
        }
      },
      {
        "name": "Tags",
        "scope": [
          "entity.name.tag",
          "meta.tag"
        ],
        "settings": {
          "foreground": "#F9B98C"
        }
      },
      {
        "name": "Attributes",
        "scope": [
          "entity.other.attribute-name"
        ],
        "settings": {
          "foreground": "#9099A1"
        }
      },
      {
        "name": "Properties",
        "scope": [
          "variable.other.property",
          "meta.object-literal.key"
        ],
        "settings": {
          "foreground": "#E6E6E6"
        }
      },
      {
        "name": "Variables",
        "scope": [
          "variable",
          "variable.other.readwrite",
          "variable.parameter",
          "variable.other.object"
        ],
        "settings": {
          "foreground": "#E6E6E6"
        }
      },
      {
        "name": "Special variables",
        "scope": [
          "variable.language",
          "variable.language.this",
          "variable.language.self"
        ],
        "settings": {
          "foreground": "#E6E6E6"
        }
      },
      {
        "name": "Built-in types",
        "scope": [
          "support.type",
          "support.class",
          "support.type.primitive"
        ],
        "settings": {
          "foreground": "#9592A4"
        }
      },
      {
        "name": "Titles and headings",
        "scope": [
          "entity.name",
          "markup.heading"
        ],
        "settings": {
          "fontStyle": "bold",
          "foreground": "#FFA16C"
        }
      },
      {
        "name": "Links",
        "scope": [
          "markup.underline.link",
          "string.other.link"
        ],
        "settings": {
          "fontStyle": "italic",
          "foreground": "#479FFA"
        }
      },
      {
        "name": "Emphasis",
        "scope": [
          "markup.italic"
        ],
        "settings": {
          "fontStyle": "italic"
        }
      },
      {
        "name": "Strong emphasis",
        "scope": [
          "markup.bold"
        ],
        "settings": {
          "fontStyle": "bold"
        }
      },
      {
        "name": "Regex and escapes",
        "scope": [
          "string.regexp",
          "constant.character.escape"
        ],
        "settings": {
          "foreground": "#9592A4"
        }
      },
      {
        "name": "Labels and hints",
        "scope": [
          "entity.name.label",
          "meta.annotation",
          "markup.raw"
        ],
        "settings": {
          "foreground": "#E6E6E6"
        }
      },
      {
        "name": "Variants and modifiers",
        "scope": [
          "storage.modifier",
          "keyword.other"
        ],
        "settings": {
          "foreground": "#F9B98C"
        }
      }
    ],
    "type": "dark"
  },
  "proof-light": {
    "bg": "#f5f3ed",
    "chromeTheme": {
      "fonts": {
        "code": null,
        "ui": null
      }
    },
    "colors": {
      "activityBar.activeBorder": "#3d755d",
      "activityBar.background": "#efede6",
      "activityBarBadge.background": "#3d755d",
      "button.background": "#3d755d",
      "editor.background": "#f5f3ed",
      "editor.foreground": "#2f312d",
      "editorCursor.foreground": "#3d755d",
      "editorGroupHeader.tabsBackground": "#efede6",
      "focusBorder": "#3d755d",
      "foreground": "#2f312d",
      "panel.background": "#efede6",
      "sideBar.background": "#efede6",
      "sideBar.foreground": "#4b4d48",
      "sideBarTitle.foreground": "#2f312d",
      "textLink.foreground": "#3d755d"
    },
    "fg": "#2f312d",
    "name": "proof-light",
    "tokenColors": [
      {
        "scope": [
          "comment",
          "punctuation.definition.comment"
        ],
        "settings": {
          "foreground": "#8b877c"
        }
      },
      {
        "scope": [
          "string",
          "string.quoted",
          "constant.other.symbol"
        ],
        "settings": {
          "foreground": "#3d755d"
        }
      },
      {
        "scope": [
          "constant.numeric",
          "constant.language.boolean",
          "regexp",
          "string.regexp"
        ],
        "settings": {
          "foreground": "#d3b45b"
        }
      },
      {
        "scope": [
          "keyword",
          "keyword.control",
          "storage",
          "storage.type",
          "storage.modifier"
        ],
        "settings": {
          "foreground": "#5f6ac2"
        }
      },
      {
        "scope": [
          "entity.name.type",
          "entity.other.inherited-class",
          "support.class",
          "support.type"
        ],
        "settings": {
          "foreground": "#5f6ac2"
        }
      },
      {
        "scope": [
          "entity.name.function",
          "support.function",
          "variable.function",
          "meta.function-call"
        ],
        "settings": {
          "foreground": "#3d755d"
        }
      },
      {
        "scope": [
          "keyword.operator",
          "punctuation.accessor",
          "punctuation",
          "punctuation.bracket",
          "punctuation.separator"
        ],
        "settings": {
          "foreground": "#7a766d"
        }
      },
      {
        "scope": [
          "variable",
          "meta.object-literal.key",
          "meta.object.member",
          "meta.property-name"
        ],
        "settings": {
          "foreground": "#2f312d"
        }
      }
    ],
    "type": "light"
  },
} as unknown as Readonly<Record<string, ThemeRegistration>>
