// Generated by scripts/generate-codex-themes.ts from dark-plus-BXTMAQPu.js, dark-plus-Bz98YTJ5.js, one-dark-pro-BkDH7paD.js, one-dark-pro-CYmvQ-E_.js, rose-pine-dawn-CjvZT0IE.js, rose-pine-dawn-Dq4HFGK-.js.
// Do not edit this file manually.
import type { ThemeRegistration } from 'shiki'

export const themes = {
  "dark-plus": {
    "colors": {
      "actionBar.toggledBackground": "#383a49",
      "activityBarBadge.background": "#007ACC",
      "checkbox.border": "#6B6B6B",
      "editor.background": "#1E1E1E",
      "editor.foreground": "#D4D4D4",
      "editor.inactiveSelectionBackground": "#3A3D41",
      "editor.selectionHighlightBackground": "#ADD6FF26",
      "editorIndentGuide.activeBackground1": "#707070",
      "editorIndentGuide.background1": "#404040",
      "input.placeholderForeground": "#A6A6A6",
      "list.activeSelectionIconForeground": "#FFF",
      "list.dropBackground": "#383B3D",
      "menu.background": "#252526",
      "menu.border": "#454545",
      "menu.foreground": "#CCCCCC",
      "menu.selectionBackground": "#0078d4",
      "menu.separatorBackground": "#454545",
      "ports.iconRunningProcessForeground": "#369432",
      "sideBarSectionHeader.background": "#0000",
      "sideBarSectionHeader.border": "#ccc3",
      "sideBarTitle.foreground": "#BBBBBB",
      "statusBarItem.remoteBackground": "#16825D",
      "statusBarItem.remoteForeground": "#FFF",
      "tab.lastPinnedBorder": "#ccc3",
      "tab.selectedBackground": "#222222",
      "tab.selectedForeground": "#ffffffa0",
      "terminal.inactiveSelectionBackground": "#3A3D41",
      "widget.border": "#303031"
    },
    "name": "dark-plus",
    "semanticHighlighting": true,
    "semanticTokenColors": {
      "customLiteral": "#DCDCAA",
      "newOperator": "#C586C0",
      "numberLiteral": "#b5cea8",
      "stringLiteral": "#ce9178"
    },
    "tokenColors": [
      {
        "scope": [
          "meta.embedded",
          "source.groovy.embedded",
          "string meta.image.inline.markdown",
          "variable.legacy.builtin.python"
        ],
        "settings": {
          "foreground": "#D4D4D4"
        }
      },
      {
        "scope": "emphasis",
        "settings": {
          "fontStyle": "italic"
        }
      },
      {
        "scope": "strong",
        "settings": {
          "fontStyle": "bold"
        }
      },
      {
        "scope": "header",
        "settings": {
          "foreground": "#000080"
        }
      },
      {
        "scope": "comment",
        "settings": {
          "foreground": "#6A9955"
        }
      },
      {
        "scope": "constant.language",
        "settings": {
          "foreground": "#569cd6"
        }
      },
      {
        "scope": [
          "constant.numeric",
          "variable.other.enummember",
          "keyword.operator.plus.exponent",
          "keyword.operator.minus.exponent"
        ],
        "settings": {
          "foreground": "#b5cea8"
        }
      },
      {
        "scope": "constant.regexp",
        "settings": {
          "foreground": "#646695"
        }
      },
      {
        "scope": "entity.name.tag",
        "settings": {
          "foreground": "#569cd6"
        }
      },
      {
        "scope": [
          "entity.name.tag.css",
          "entity.name.tag.less"
        ],
        "settings": {
          "foreground": "#d7ba7d"
        }
      },
      {
        "scope": "entity.other.attribute-name",
        "settings": {
          "foreground": "#9cdcfe"
        }
      },
      {
        "scope": [
          "entity.other.attribute-name.class.css",
          "source.css entity.other.attribute-name.class",
          "entity.other.attribute-name.id.css",
          "entity.other.attribute-name.parent-selector.css",
          "entity.other.attribute-name.parent.less",
          "source.css entity.other.attribute-name.pseudo-class",
          "entity.other.attribute-name.pseudo-element.css",
          "source.css.less entity.other.attribute-name.id",
          "entity.other.attribute-name.scss"
        ],
        "settings": {
          "foreground": "#d7ba7d"
        }
      },
      {
        "scope": "invalid",
        "settings": {
          "foreground": "#f44747"
        }
      },
      {
        "scope": "markup.underline",
        "settings": {
          "fontStyle": "underline"
        }
      },
      {
        "scope": "markup.bold",
        "settings": {
          "fontStyle": "bold",
          "foreground": "#569cd6"
        }
      },
      {
        "scope": "markup.heading",
        "settings": {
          "fontStyle": "bold",
          "foreground": "#569cd6"
        }
      },
      {
        "scope": "markup.italic",
        "settings": {
          "fontStyle": "italic"
        }
      },
      {
        "scope": "markup.strikethrough",
        "settings": {
          "fontStyle": "strikethrough"
        }
      },
      {
        "scope": "markup.inserted",
        "settings": {
          "foreground": "#b5cea8"
        }
      },
      {
        "scope": "markup.deleted",
        "settings": {
          "foreground": "#ce9178"
        }
      },
      {
        "scope": "markup.changed",
        "settings": {
          "foreground": "#569cd6"
        }
      },
      {
        "scope": "punctuation.definition.quote.begin.markdown",
        "settings": {
          "foreground": "#6A9955"
        }
      },
      {
        "scope": "punctuation.definition.list.begin.markdown",
        "settings": {
          "foreground": "#6796e6"
        }
      },
      {
        "scope": "markup.inline.raw",
        "settings": {
          "foreground": "#ce9178"
        }
      },
      {
        "scope": "punctuation.definition.tag",
        "settings": {
          "foreground": "#808080"
        }
      },
      {
        "scope": [
          "meta.preprocessor",
          "entity.name.function.preprocessor"
        ],
        "settings": {
          "foreground": "#569cd6"
        }
      },
      {
        "scope": "meta.preprocessor.string",
        "settings": {
          "foreground": "#ce9178"
        }
      },
      {
        "scope": "meta.preprocessor.numeric",
        "settings": {
          "foreground": "#b5cea8"
        }
      },
      {
        "scope": "meta.structure.dictionary.key.python",
        "settings": {
          "foreground": "#9cdcfe"
        }
      },
      {
        "scope": "meta.diff.header",
        "settings": {
          "foreground": "#569cd6"
        }
      },
      {
        "scope": "storage",
        "settings": {
          "foreground": "#569cd6"
        }
      },
      {
        "scope": "storage.type",
        "settings": {
          "foreground": "#569cd6"
        }
      },
      {
        "scope": [
          "storage.modifier",
          "keyword.operator.noexcept"
        ],
        "settings": {
          "foreground": "#569cd6"
        }
      },
      {
        "scope": [
          "string",
          "meta.embedded.assembly"
        ],
        "settings": {
          "foreground": "#ce9178"
        }
      },
      {
        "scope": "string.tag",
        "settings": {
          "foreground": "#ce9178"
        }
      },
      {
        "scope": "string.value",
        "settings": {
          "foreground": "#ce9178"
        }
      },
      {
        "scope": "string.regexp",
        "settings": {
          "foreground": "#d16969"
        }
      },
      {
        "scope": [
          "punctuation.definition.template-expression.begin",
          "punctuation.definition.template-expression.end",
          "punctuation.section.embedded"
        ],
        "settings": {
          "foreground": "#569cd6"
        }
      },
      {
        "scope": [
          "meta.template.expression"
        ],
        "settings": {
          "foreground": "#d4d4d4"
        }
      },
      {
        "scope": [
          "support.type.vendored.property-name",
          "support.type.property-name",
          "source.css variable",
          "source.coffee.embedded"
        ],
        "settings": {
          "foreground": "#9cdcfe"
        }
      },
      {
        "scope": "keyword",
        "settings": {
          "foreground": "#569cd6"
        }
      },
      {
        "scope": "keyword.control",
        "settings": {
          "foreground": "#569cd6"
        }
      },
      {
        "scope": "keyword.operator",
        "settings": {
          "foreground": "#d4d4d4"
        }
      },
      {
        "scope": [
          "keyword.operator.new",
          "keyword.operator.expression",
          "keyword.operator.cast",
          "keyword.operator.sizeof",
          "keyword.operator.alignof",
          "keyword.operator.typeid",
          "keyword.operator.alignas",
          "keyword.operator.instanceof",
          "keyword.operator.logical.python",
          "keyword.operator.wordlike"
        ],
        "settings": {
          "foreground": "#569cd6"
        }
      },
      {
        "scope": "keyword.other.unit",
        "settings": {
          "foreground": "#b5cea8"
        }
      },
      {
        "scope": [
          "punctuation.section.embedded.begin.php",
          "punctuation.section.embedded.end.php"
        ],
        "settings": {
          "foreground": "#569cd6"
        }
      },
      {
        "scope": "support.function.git-rebase",
        "settings": {
          "foreground": "#9cdcfe"
        }
      },
      {
        "scope": "constant.sha.git-rebase",
        "settings": {
          "foreground": "#b5cea8"
        }
      },
      {
        "scope": [
          "storage.modifier.import.java",
          "variable.language.wildcard.java",
          "storage.modifier.package.java"
        ],
        "settings": {
          "foreground": "#d4d4d4"
        }
      },
      {
        "scope": "variable.language",
        "settings": {
          "foreground": "#569cd6"
        }
      },
      {
        "scope": [
          "entity.name.function",
          "support.function",
          "support.constant.handlebars",
          "source.powershell variable.other.member",
          "entity.name.operator.custom-literal"
        ],
        "settings": {
          "foreground": "#DCDCAA"
        }
      },
      {
        "scope": [
          "support.class",
          "support.type",
          "entity.name.type",
          "entity.name.namespace",
          "entity.other.attribute",
          "entity.name.scope-resolution",
          "entity.name.class",
          "storage.type.numeric.go",
          "storage.type.byte.go",
          "storage.type.boolean.go",
          "storage.type.string.go",
          "storage.type.uintptr.go",
          "storage.type.error.go",
          "storage.type.rune.go",
          "storage.type.cs",
          "storage.type.generic.cs",
          "storage.type.modifier.cs",
          "storage.type.variable.cs",
          "storage.type.annotation.java",
          "storage.type.generic.java",
          "storage.type.java",
          "storage.type.object.array.java",
          "storage.type.primitive.array.java",
          "storage.type.primitive.java",
          "storage.type.token.java",
          "storage.type.groovy",
          "storage.type.annotation.groovy",
          "storage.type.parameters.groovy",
          "storage.type.generic.groovy",
          "storage.type.object.array.groovy",
          "storage.type.primitive.array.groovy",
          "storage.type.primitive.groovy"
        ],
        "settings": {
          "foreground": "#4EC9B0"
        }
      },
      {
        "scope": [
          "meta.type.cast.expr",
          "meta.type.new.expr",
          "support.constant.math",
          "support.constant.dom",
          "support.constant.json",
          "entity.other.inherited-class",
          "punctuation.separator.namespace.ruby"
        ],
        "settings": {
          "foreground": "#4EC9B0"
        }
      },
      {
        "scope": [
          "keyword.control",
          "source.cpp keyword.operator.new",
          "keyword.operator.delete",
          "keyword.other.using",
          "keyword.other.directive.using",
          "keyword.other.operator",
          "entity.name.operator"
        ],
        "settings": {
          "foreground": "#C586C0"
        }
      },
      {
        "scope": [
          "variable",
          "meta.definition.variable.name",
          "support.variable",
          "entity.name.variable",
          "constant.other.placeholder"
        ],
        "settings": {
          "foreground": "#9CDCFE"
        }
      },
      {
        "scope": [
          "variable.other.constant",
          "variable.other.enummember"
        ],
        "settings": {
          "foreground": "#4FC1FF"
        }
      },
      {
        "scope": [
          "meta.object-literal.key"
        ],
        "settings": {
          "foreground": "#9CDCFE"
        }
      },
      {
        "scope": [
          "support.constant.property-value",
          "support.constant.font-name",
          "support.constant.media-type",
          "support.constant.media",
          "constant.other.color.rgb-value",
          "constant.other.rgb-value",
          "support.constant.color"
        ],
        "settings": {
          "foreground": "#CE9178"
        }
      },
      {
        "scope": [
          "punctuation.definition.group.regexp",
          "punctuation.definition.group.assertion.regexp",
          "punctuation.definition.character-class.regexp",
          "punctuation.character.set.begin.regexp",
          "punctuation.character.set.end.regexp",
          "keyword.operator.negation.regexp",
          "support.other.parenthesis.regexp"
        ],
        "settings": {
          "foreground": "#CE9178"
        }
      },
      {
        "scope": [
          "constant.character.character-class.regexp",
          "constant.other.character-class.set.regexp",
          "constant.other.character-class.regexp",
          "constant.character.set.regexp"
        ],
        "settings": {
          "foreground": "#d16969"
        }
      },
      {
        "scope": [
          "keyword.operator.or.regexp",
          "keyword.control.anchor.regexp"
        ],
        "settings": {
          "foreground": "#DCDCAA"
        }
      },
      {
        "scope": "keyword.operator.quantifier.regexp",
        "settings": {
          "foreground": "#d7ba7d"
        }
      },
      {
        "scope": [
          "constant.character",
          "constant.other.option"
        ],
        "settings": {
          "foreground": "#569cd6"
        }
      },
      {
        "scope": "constant.character.escape",
        "settings": {
          "foreground": "#d7ba7d"
        }
      },
      {
        "scope": "entity.name.label",
        "settings": {
          "foreground": "#C8C8C8"
        }
      }
    ],
    "type": "dark"
  },
  "one-dark-pro": {
    "colors": {
      "actionBar.toggledBackground": "#525761",
      "activityBar.background": "#282c34",
      "activityBar.foreground": "#d7dae0",
      "activityBarBadge.background": "#4d78cc",
      "activityBarBadge.foreground": "#f8fafd",
      "badge.background": "#282c34",
      "button.background": "#404754",
      "button.secondaryBackground": "#30333d",
      "button.secondaryForeground": "#c0bdbd",
      "checkbox.border": "#404754",
      "debugToolBar.background": "#21252b",
      "descriptionForeground": "#abb2bf",
      "diffEditor.insertedTextBackground": "#00809b33",
      "dropdown.background": "#21252b",
      "dropdown.border": "#21252b",
      "editor.background": "#282c34",
      "editor.findMatchBackground": "#d19a6644",
      "editor.findMatchBorder": "#ffffff5a",
      "editor.findMatchHighlightBackground": "#ffffff22",
      "editor.foreground": "#abb2bf",
      "editor.lineHighlightBackground": "#2c313c",
      "editor.selectionBackground": "#67769660",
      "editor.selectionHighlightBackground": "#ffd33d44",
      "editor.selectionHighlightBorder": "#dddddd",
      "editor.wordHighlightBackground": "#d2e0ff2f",
      "editor.wordHighlightBorder": "#7f848e",
      "editor.wordHighlightStrongBackground": "#abb2bf26",
      "editor.wordHighlightStrongBorder": "#7f848e",
      "editorBracketHighlight.foreground1": "#d19a66",
      "editorBracketHighlight.foreground2": "#c678dd",
      "editorBracketHighlight.foreground3": "#56b6c2",
      "editorBracketMatch.background": "#515a6b",
      "editorBracketMatch.border": "#515a6b",
      "editorCursor.background": "#ffffffc9",
      "editorCursor.foreground": "#528bff",
      "editorError.foreground": "#c24038",
      "editorGroup.background": "#181a1f",
      "editorGroup.border": "#181a1f",
      "editorGroupHeader.tabsBackground": "#21252b",
      "editorGutter.addedBackground": "#109868",
      "editorGutter.deletedBackground": "#9A353D",
      "editorGutter.modifiedBackground": "#948B60",
      "editorHoverWidget.background": "#21252b",
      "editorHoverWidget.border": "#181a1f",
      "editorHoverWidget.highlightForeground": "#61afef",
      "editorIndentGuide.activeBackground1": "#c8c8c859",
      "editorIndentGuide.background1": "#3b4048",
      "editorInlayHint.background": "#2c313c",
      "editorInlayHint.foreground": "#abb2bf",
      "editorLineNumber.activeForeground": "#abb2bf",
      "editorLineNumber.foreground": "#495162",
      "editorMarkerNavigation.background": "#21252b",
      "editorOverviewRuler.addedBackground": "#109868",
      "editorOverviewRuler.deletedBackground": "#9A353D",
      "editorOverviewRuler.modifiedBackground": "#948B60",
      "editorRuler.foreground": "#abb2bf26",
      "editorSuggestWidget.background": "#21252b",
      "editorSuggestWidget.border": "#181a1f",
      "editorSuggestWidget.selectedBackground": "#2c313a",
      "editorWarning.foreground": "#d19a66",
      "editorWhitespace.foreground": "#ffffff1d",
      "editorWidget.background": "#21252b",
      "focusBorder": "#3e4452",
      "gitDecoration.ignoredResourceForeground": "#636b78",
      "input.background": "#1d1f23",
      "input.foreground": "#abb2bf",
      "list.activeSelectionBackground": "#2c313a",
      "list.activeSelectionForeground": "#d7dae0",
      "list.focusBackground": "#323842",
      "list.focusForeground": "#f0f0f0",
      "list.highlightForeground": "#ecebeb",
      "list.hoverBackground": "#2c313a",
      "list.hoverForeground": "#abb2bf",
      "list.inactiveSelectionBackground": "#323842",
      "list.inactiveSelectionForeground": "#d7dae0",
      "list.warningForeground": "#d19a66",
      "menu.foreground": "#abb2bf",
      "menu.separatorBackground": "#343a45",
      "minimapGutter.addedBackground": "#109868",
      "minimapGutter.deletedBackground": "#9A353D",
      "minimapGutter.modifiedBackground": "#948B60",
      "multiDiffEditor.headerBackground": "#21252b",
      "panel.border": "#3e4452",
      "panelSectionHeader.background": "#21252b",
      "peekViewEditor.background": "#1b1d23",
      "peekViewEditor.matchHighlightBackground": "#29244b",
      "peekViewResult.background": "#22262b",
      "scrollbar.shadow": "#23252c",
      "scrollbarSlider.activeBackground": "#747d9180",
      "scrollbarSlider.background": "#4e566660",
      "scrollbarSlider.hoverBackground": "#5a637580",
      "settings.focusedRowBackground": "#282c34",
      "settings.headerForeground": "#fff",
      "sideBar.background": "#21252b",
      "sideBar.foreground": "#abb2bf",
      "sideBarSectionHeader.background": "#282c34",
      "sideBarSectionHeader.foreground": "#abb2bf",
      "statusBar.background": "#21252b",
      "statusBar.debuggingBackground": "#cc6633",
      "statusBar.debuggingBorder": "#ff000000",
      "statusBar.debuggingForeground": "#ffffff",
      "statusBar.foreground": "#9da5b4",
      "statusBar.noFolderBackground": "#21252b",
      "statusBarItem.remoteBackground": "#4d78cc",
      "statusBarItem.remoteForeground": "#f8fafd",
      "tab.activeBackground": "#282c34",
      "tab.activeBorder": "#b4b4b4",
      "tab.activeForeground": "#dcdcdc",
      "tab.border": "#181a1f",
      "tab.hoverBackground": "#323842",
      "tab.inactiveBackground": "#21252b",
      "tab.unfocusedHoverBackground": "#323842",
      "terminal.ansiBlack": "#3f4451",
      "terminal.ansiBlue": "#4aa5f0",
      "terminal.ansiBrightBlack": "#4f5666",
      "terminal.ansiBrightBlue": "#4dc4ff",
      "terminal.ansiBrightCyan": "#4cd1e0",
      "terminal.ansiBrightGreen": "#a5e075",
      "terminal.ansiBrightMagenta": "#de73ff",
      "terminal.ansiBrightRed": "#ff616e",
      "terminal.ansiBrightWhite": "#e6e6e6",
      "terminal.ansiBrightYellow": "#f0a45d",
      "terminal.ansiCyan": "#42b3c2",
      "terminal.ansiGreen": "#8cc265",
      "terminal.ansiMagenta": "#c162de",
      "terminal.ansiRed": "#e05561",
      "terminal.ansiWhite": "#d7dae0",
      "terminal.ansiYellow": "#d18f52",
      "terminal.background": "#282c34",
      "terminal.border": "#3e4452",
      "terminal.foreground": "#abb2bf",
      "terminal.selectionBackground": "#abb2bf30",
      "textBlockQuote.background": "#2e3440",
      "textBlockQuote.border": "#4b5362",
      "textLink.foreground": "#61afef",
      "textPreformat.foreground": "#d19a66",
      "titleBar.activeBackground": "#282c34",
      "titleBar.activeForeground": "#9da5b4",
      "titleBar.inactiveBackground": "#282c34",
      "titleBar.inactiveForeground": "#6b717d",
      "tree.indentGuidesStroke": "#ffffff1d",
      "walkThrough.embeddedEditorBackground": "#2e3440",
      "welcomePage.buttonHoverBackground": "#404754"
    },
    "name": "one-dark-pro",
    "semanticHighlighting": true,
    "semanticTokenColors": {
      "annotation:dart": {
        "foreground": "#d19a66"
      },
      "enumMember": {
        "foreground": "#56b6c2"
      },
      "macro": {
        "foreground": "#d19a66"
      },
      "memberOperatorOverload": {
        "foreground": "#c678dd"
      },
      "parameter.label:dart": {
        "foreground": "#abb2bf"
      },
      "property:dart": {
        "foreground": "#d19a66"
      },
      "tomlArrayKey": {
        "foreground": "#e5c07b"
      },
      "variable:dart": {
        "foreground": "#d19a66"
      },
      "variable.constant": {
        "foreground": "#d19a66"
      },
      "variable.defaultLibrary": {
        "foreground": "#e5c07b"
      }
    },
    "tokenColors": [
      {
        "scope": "meta.embedded",
        "settings": {
          "foreground": "#abb2bf"
        }
      },
      {
        "scope": "punctuation.definition.delayed.unison,punctuation.definition.list.begin.unison,punctuation.definition.list.end.unison,punctuation.definition.ability.begin.unison,punctuation.definition.ability.end.unison,punctuation.operator.assignment.as.unison,punctuation.separator.pipe.unison,punctuation.separator.delimiter.unison,punctuation.definition.hash.unison",
        "settings": {
          "foreground": "#e06c75"
        }
      },
      {
        "scope": "variable.other.generic-type.haskell",
        "settings": {
          "foreground": "#c678dd"
        }
      },
      {
        "scope": "storage.type.haskell",
        "settings": {
          "foreground": "#d19a66"
        }
      },
      {
        "scope": "support.variable.magic.python",
        "settings": {
          "foreground": "#e06c75"
        }
      },
      {
        "scope": "punctuation.separator.period.python,punctuation.separator.element.python,punctuation.parenthesis.begin.python,punctuation.parenthesis.end.python",
        "settings": {
          "foreground": "#abb2bf"
        }
      },
      {
        "scope": "variable.parameter.function.language.special.self.python",
        "settings": {
          "foreground": "#e5c07b"
        }
      },
      {
        "scope": "variable.parameter.function.language.special.cls.python",
        "settings": {
          "foreground": "#e5c07b"
        }
      },
      {
        "scope": "storage.modifier.lifetime.rust",
        "settings": {
          "foreground": "#abb2bf"
        }
      },
      {
        "scope": "support.function.std.rust",
        "settings": {
          "foreground": "#61afef"
        }
      },
      {
        "scope": "entity.name.lifetime.rust",
        "settings": {
          "foreground": "#e5c07b"
        }
      },
      {
        "scope": "variable.language.rust",
        "settings": {
          "foreground": "#e06c75"
        }
      },
      {
        "scope": "support.constant.edge",
        "settings": {
          "foreground": "#c678dd"
        }
      },
      {
        "scope": "constant.other.character-class.regexp",
        "settings": {
          "foreground": "#e06c75"
        }
      },
      {
        "scope": [
          "keyword.operator.word"
        ],
        "settings": {
          "foreground": "#c678dd"
        }
      },
      {
        "scope": "keyword.operator.quantifier.regexp",
        "settings": {
          "foreground": "#d19a66"
        }
      },
      {
        "scope": "variable.parameter.function",
        "settings": {
          "foreground": "#abb2bf"
        }
      },
      {
        "scope": "comment markup.link",
        "settings": {
          "foreground": "#5c6370"
        }
      },
      {
        "scope": "markup.changed.diff",
        "settings": {
          "foreground": "#e5c07b"
        }
      },
      {
        "scope": "meta.diff.header.from-file,meta.diff.header.to-file,punctuation.definition.from-file.diff,punctuation.definition.to-file.diff",
        "settings": {
          "foreground": "#61afef"
        }
      },
      {
        "scope": "markup.inserted.diff",
        "settings": {
          "foreground": "#98c379"
        }
      },
      {
        "scope": "markup.deleted.diff",
        "settings": {
          "foreground": "#e06c75"
        }
      },
      {
        "scope": "meta.function.c,meta.function.cpp",
        "settings": {
          "foreground": "#e06c75"
        }
      },
      {
        "scope": "punctuation.section.block.begin.bracket.curly.cpp,punctuation.section.block.end.bracket.curly.cpp,punctuation.terminator.statement.c,punctuation.section.block.begin.bracket.curly.c,punctuation.section.block.end.bracket.curly.c,punctuation.section.parens.begin.bracket.round.c,punctuation.section.parens.end.bracket.round.c,punctuation.section.parameters.begin.bracket.round.c,punctuation.section.parameters.end.bracket.round.c",
        "settings": {
          "foreground": "#abb2bf"
        }
      },
      {
        "scope": "punctuation.separator.key-value",
        "settings": {
          "foreground": "#abb2bf"
        }
      },
      {
        "scope": "keyword.operator.expression.import",
        "settings": {
          "foreground": "#61afef"
        }
      },
      {
        "scope": "support.constant.math",
        "settings": {
          "foreground": "#e5c07b"
        }
      },
      {
        "scope": "support.constant.property.math",
        "settings": {
          "foreground": "#d19a66"
        }
      },
      {
        "scope": "variable.other.constant",
        "settings": {
          "foreground": "#e5c07b"
        }
      },
      {
        "scope": [
          "storage.type.annotation.java",
          "storage.type.object.array.java"
        ],
        "settings": {
          "foreground": "#e5c07b"
        }
      },
      {
        "scope": "source.java",
        "settings": {
          "foreground": "#e06c75"
        }
      },
      {
        "scope": "punctuation.section.block.begin.java,punctuation.section.block.end.java,punctuation.definition.method-parameters.begin.java,punctuation.definition.method-parameters.end.java,meta.method.identifier.java,punctuation.section.method.begin.java,punctuation.section.method.end.java,punctuation.terminator.java,punctuation.section.class.begin.java,punctuation.section.class.end.java,punctuation.section.inner-class.begin.java,punctuation.section.inner-class.end.java,meta.method-call.java,punctuation.section.class.begin.bracket.curly.java,punctuation.section.class.end.bracket.curly.java,punctuation.section.method.begin.bracket.curly.java,punctuation.section.method.end.bracket.curly.java,punctuation.separator.period.java,punctuation.bracket.angle.java,punctuation.definition.annotation.java,meta.method.body.java",
        "settings": {
          "foreground": "#abb2bf"
        }
      },
      {
        "scope": "meta.method.java",
        "settings": {
          "foreground": "#61afef"
        }
      },
      {
        "scope": "storage.modifier.import.java,storage.type.java,storage.type.generic.java",
        "settings": {
          "foreground": "#e5c07b"
        }
      },
      {
        "scope": "keyword.operator.instanceof.java",
        "settings": {
          "foreground": "#c678dd"
        }
      },
      {
        "scope": "meta.definition.variable.name.java",
        "settings": {
          "foreground": "#e06c75"
        }
      },
      {
        "scope": "keyword.operator.logical",
        "settings": {
          "foreground": "#56b6c2"
        }
      },
      {
        "scope": "keyword.operator.bitwise",
        "settings": {
          "foreground": "#56b6c2"
        }
      },
      {
        "scope": "keyword.operator.channel",
        "settings": {
          "foreground": "#56b6c2"
        }
      },
      {
        "scope": "support.constant.property-value.scss,support.constant.property-value.css",
        "settings": {
          "foreground": "#d19a66"
        }
      },
      {
        "scope": "keyword.operator.css,keyword.operator.scss,keyword.operator.less",
        "settings": {
          "foreground": "#56b6c2"
        }
      },
      {
        "scope": "support.constant.color.w3c-standard-color-name.css,support.constant.color.w3c-standard-color-name.scss",
        "settings": {
          "foreground": "#d19a66"
        }
      },
      {
        "scope": "punctuation.separator.list.comma.css",
        "settings": {
          "foreground": "#abb2bf"
        }
      },
      {
        "scope": "support.constant.color.w3c-standard-color-name.css",
        "settings": {
          "foreground": "#d19a66"
        }
      },
      {
        "scope": "support.type.vendored.property-name.css",
        "settings": {
          "foreground": "#56b6c2"
        }
      },
      {
        "scope": "support.module.node,support.type.object.module,support.module.node",
        "settings": {
          "foreground": "#e5c07b"
        }
      },
      {
        "scope": "entity.name.type.module",
        "settings": {
          "foreground": "#e5c07b"
        }
      },
      {
        "scope": "variable.other.readwrite,meta.object-literal.key,support.variable.property,support.variable.object.process,support.variable.object.node",
        "settings": {
          "foreground": "#e06c75"
        }
      },
      {
        "scope": "support.constant.json",
        "settings": {
          "foreground": "#d19a66"
        }
      },
      {
        "scope": [
          "keyword.operator.expression.instanceof",
          "keyword.operator.new",
          "keyword.operator.ternary",
          "keyword.operator.optional",
          "keyword.operator.expression.keyof"
        ],
        "settings": {
          "foreground": "#c678dd"
        }
      },
      {
        "scope": "support.type.object.console",
        "settings": {
          "foreground": "#e06c75"
        }
      },
      {
        "scope": "support.variable.property.process",
        "settings": {
          "foreground": "#d19a66"
        }
      },
      {
        "scope": "entity.name.function,support.function.console",
        "settings": {
          "foreground": "#61afef"
        }
      },
      {
        "scope": "keyword.operator.misc.rust",
        "settings": {
          "foreground": "#abb2bf"
        }
      },
      {
        "scope": "keyword.operator.sigil.rust",
        "settings": {
          "foreground": "#c678dd"
        }
      },
      {
        "scope": "keyword.operator.delete",
        "settings": {
          "foreground": "#c678dd"
        }
      },
      {
        "scope": "support.type.object.dom",
        "settings": {
          "foreground": "#56b6c2"
        }
      },
      {
        "scope": "support.variable.dom,support.variable.property.dom",
        "settings": {
          "foreground": "#e06c75"
        }
      },
      {
        "scope": "keyword.operator.arithmetic,keyword.operator.comparison,keyword.operator.decrement,keyword.operator.increment,keyword.operator.relational",
        "settings": {
          "foreground": "#56b6c2"
        }
      },
      {
        "scope": "keyword.operator.assignment.c,keyword.operator.comparison.c,keyword.operator.c,keyword.operator.increment.c,keyword.operator.decrement.c,keyword.operator.bitwise.shift.c,keyword.operator.assignment.cpp,keyword.operator.comparison.cpp,keyword.operator.cpp,keyword.operator.increment.cpp,keyword.operator.decrement.cpp,keyword.operator.bitwise.shift.cpp",
        "settings": {
          "foreground": "#c678dd"
        }
      },
      {
        "scope": "punctuation.separator.delimiter",
        "settings": {
          "foreground": "#abb2bf"
        }
      },
      {
        "scope": "punctuation.separator.c,punctuation.separator.cpp",
        "settings": {
          "foreground": "#c678dd"
        }
      },
      {
        "scope": "support.type.posix-reserved.c,support.type.posix-reserved.cpp",
        "settings": {
          "foreground": "#56b6c2"
        }
      },
      {
        "scope": "keyword.operator.sizeof.c,keyword.operator.sizeof.cpp",
        "settings": {
          "foreground": "#c678dd"
        }
      },
      {
        "scope": "variable.parameter.function.language.python",
        "settings": {
          "foreground": "#d19a66"
        }
      },
      {
        "scope": "support.type.python",
        "settings": {
          "foreground": "#56b6c2"
        }
      },
      {
        "scope": "keyword.operator.logical.python",
        "settings": {
          "foreground": "#c678dd"
        }
      },
      {
        "scope": "variable.parameter.function.python",
        "settings": {
          "foreground": "#d19a66"
        }
      },
      {
        "scope": "punctuation.definition.arguments.begin.python,punctuation.definition.arguments.end.python,punctuation.separator.arguments.python,punctuation.definition.list.begin.python,punctuation.definition.list.end.python",
        "settings": {
          "foreground": "#abb2bf"
        }
      },
      {
        "scope": "meta.function-call.generic.python",
        "settings": {
          "foreground": "#61afef"
        }
      },
      {
        "scope": "constant.character.format.placeholder.other.python",
        "settings": {
          "foreground": "#d19a66"
        }
      },
      {
        "scope": "keyword.operator",
        "settings": {
          "foreground": "#abb2bf"
        }
      },
      {
        "scope": "keyword.operator.assignment.compound",
        "settings": {
          "foreground": "#c678dd"
        }
      },
      {
        "scope": "keyword.operator.assignment.compound.js,keyword.operator.assignment.compound.ts",
        "settings": {
          "foreground": "#56b6c2"
        }
      },
      {
        "scope": "keyword",
        "settings": {
          "foreground": "#c678dd"
        }
      },
      {
        "scope": "entity.name.namespace",
        "settings": {
          "foreground": "#e5c07b"
        }
      },
      {
        "scope": "variable",
        "settings": {
          "foreground": "#e06c75"
        }
      },
      {
        "scope": "variable.c",
        "settings": {
          "foreground": "#abb2bf"
        }
      },
      {
        "scope": "variable.language",
        "settings": {
          "foreground": "#e5c07b"
        }
      },
      {
        "scope": "token.variable.parameter.java",
        "settings": {
          "foreground": "#abb2bf"
        }
      },
      {
        "scope": "import.storage.java",
        "settings": {
          "foreground": "#e5c07b"
        }
      },
      {
        "scope": "token.package.keyword",
        "settings": {
          "foreground": "#c678dd"
        }
      },
      {
        "scope": "token.package",
        "settings": {
          "foreground": "#abb2bf"
        }
      },
      {
        "scope": [
          "entity.name.function",
          "meta.require",
          "support.function.any-method",
          "variable.function"
        ],
        "settings": {
          "foreground": "#61afef"
        }
      },
      {
        "scope": "entity.name.type.namespace",
        "settings": {
          "foreground": "#e5c07b"
        }
      },
      {
        "scope": "support.class, entity.name.type.class",
        "settings": {
          "foreground": "#e5c07b"
        }
      },
      {
        "scope": "entity.name.class.identifier.namespace.type",
        "settings": {
          "foreground": "#e5c07b"
        }
      },
      {
        "scope": [
          "entity.name.class",
          "variable.other.class.js",
          "variable.other.class.ts"
        ],
        "settings": {
          "foreground": "#e5c07b"
        }
      },
      {
        "scope": "variable.other.class.php",
        "settings": {
          "foreground": "#e06c75"
        }
      },
      {
        "scope": "entity.name.type",
        "settings": {
          "foreground": "#e5c07b"
        }
      },
      {
        "scope": "keyword.control",
        "settings": {
          "foreground": "#c678dd"
        }
      },
      {
        "scope": "control.elements, keyword.operator.less",
        "settings": {
          "foreground": "#d19a66"
        }
      },
      {
        "scope": "keyword.other.special-method",
        "settings": {
          "foreground": "#61afef"
        }
      },
      {
        "scope": "storage",
        "settings": {
          "foreground": "#c678dd"
        }
      },
      {
        "scope": "token.storage",
        "settings": {
          "foreground": "#c678dd"
        }
      },
      {
        "scope": "keyword.operator.expression.delete,keyword.operator.expression.in,keyword.operator.expression.of,keyword.operator.expression.instanceof,keyword.operator.new,keyword.operator.expression.typeof,keyword.operator.expression.void",
        "settings": {
          "foreground": "#c678dd"
        }
      },
      {
        "scope": "token.storage.type.java",
        "settings": {
          "foreground": "#e5c07b"
        }
      },
      {
        "scope": "support.function",
        "settings": {
          "foreground": "#56b6c2"
        }
      },
      {
        "scope": "support.type.property-name",
        "settings": {
          "foreground": "#abb2bf"
        }
      },
      {
        "scope": "support.type.property-name.toml, support.type.property-name.table.toml, support.type.property-name.array.toml",
        "settings": {
          "foreground": "#e06c75"
        }
      },
      {
        "scope": "support.constant.property-value",
        "settings": {
          "foreground": "#abb2bf"
        }
      },
      {
        "scope": "support.constant.font-name",
        "settings": {
          "foreground": "#d19a66"
        }
      },
      {
        "scope": "meta.tag",
        "settings": {
          "foreground": "#abb2bf"
        }
      },
      {
        "scope": "string",
        "settings": {
          "foreground": "#98c379"
        }
      },
      {
        "scope": "constant.other.symbol",
        "settings": {
          "foreground": "#56b6c2"
        }
      },
      {
        "scope": "constant.numeric",
        "settings": {
          "foreground": "#d19a66"
        }
      },
      {
        "scope": "constant",
        "settings": {
          "foreground": "#d19a66"
        }
      },
      {
        "scope": "punctuation.definition.constant",
        "settings": {
          "foreground": "#d19a66"
        }
      },
      {
        "scope": "entity.name.tag",
        "settings": {
          "foreground": "#e06c75"
        }
      },
      {
        "scope": "entity.other.attribute-name",
        "settings": {
          "foreground": "#d19a66"
        }
      },
      {
        "scope": "entity.other.attribute-name.id",
        "settings": {
          "foreground": "#61afef"
        }
      },
      {
        "scope": "entity.other.attribute-name.class.css",
        "settings": {
          "foreground": "#d19a66"
        }
      },
      {
        "scope": "meta.selector",
        "settings": {
          "foreground": "#c678dd"
        }
      },
      {
        "scope": "markup.heading",
        "settings": {
          "foreground": "#e06c75"
        }
      },
      {
        "scope": "markup.heading punctuation.definition.heading, entity.name.section",
        "settings": {
          "foreground": "#61afef"
        }
      },
      {
        "scope": "keyword.other.unit",
        "settings": {
          "foreground": "#e06c75"
        }
      },
      {
        "scope": "markup.bold,todo.bold",
        "settings": {
          "foreground": "#d19a66"
        }
      },
      {
        "scope": "punctuation.definition.bold",
        "settings": {
          "foreground": "#e5c07b"
        }
      },
      {
        "scope": "markup.italic, punctuation.definition.italic,todo.emphasis",
        "settings": {
          "foreground": "#c678dd"
        }
      },
      {
        "scope": "emphasis md",
        "settings": {
          "foreground": "#c678dd"
        }
      },
      {
        "scope": "entity.name.section.markdown",
        "settings": {
          "foreground": "#e06c75"
        }
      },
      {
        "scope": "punctuation.definition.heading.markdown",
        "settings": {
          "foreground": "#e06c75"
        }
      },
      {
        "scope": "punctuation.definition.list.begin.markdown",
        "settings": {
          "foreground": "#e5c07b"
        }
      },
      {
        "scope": "markup.heading.setext",
        "settings": {
          "foreground": "#abb2bf"
        }
      },
      {
        "scope": "punctuation.definition.bold.markdown",
        "settings": {
          "foreground": "#d19a66"
        }
      },
      {
        "scope": "markup.inline.raw.markdown",
        "settings": {
          "foreground": "#98c379"
        }
      },
      {
        "scope": "markup.inline.raw.string.markdown",
        "settings": {
          "foreground": "#98c379"
        }
      },
      {
        "scope": "punctuation.definition.raw.markdown",
        "settings": {
          "foreground": "#e5c07b"
        }
      },
      {
        "scope": "punctuation.definition.list.markdown",
        "settings": {
          "foreground": "#e5c07b"
        }
      },
      {
        "scope": [
          "punctuation.definition.string.begin.markdown",
          "punctuation.definition.string.end.markdown",
          "punctuation.definition.metadata.markdown"
        ],
        "settings": {
          "foreground": "#e06c75"
        }
      },
      {
        "scope": [
          "beginning.punctuation.definition.list.markdown"
        ],
        "settings": {
          "foreground": "#e06c75"
        }
      },
      {
        "scope": "punctuation.definition.metadata.markdown",
        "settings": {
          "foreground": "#e06c75"
        }
      },
      {
        "scope": "markup.underline.link.markdown,markup.underline.link.image.markdown",
        "settings": {
          "foreground": "#c678dd"
        }
      },
      {
        "scope": "string.other.link.title.markdown,string.other.link.description.markdown",
        "settings": {
          "foreground": "#61afef"
        }
      },
      {
        "scope": "markup.raw.monospace.asciidoc",
        "settings": {
          "foreground": "#98c379"
        }
      },
      {
        "scope": "punctuation.definition.asciidoc",
        "settings": {
          "foreground": "#e5c07b"
        }
      },
      {
        "scope": "markup.list.asciidoc",
        "settings": {
          "foreground": "#e5c07b"
        }
      },
      {
        "scope": "markup.link.asciidoc,markup.other.url.asciidoc",
        "settings": {
          "foreground": "#c678dd"
        }
      },
      {
        "scope": "string.unquoted.asciidoc,markup.other.url.asciidoc",
        "settings": {
          "foreground": "#61afef"
        }
      },
      {
        "scope": "string.regexp",
        "settings": {
          "foreground": "#56b6c2"
        }
      },
      {
        "scope": "punctuation.section.embedded, variable.interpolation",
        "settings": {
          "foreground": "#e06c75"
        }
      },
      {
        "scope": "punctuation.section.embedded.begin,punctuation.section.embedded.end",
        "settings": {
          "foreground": "#c678dd"
        }
      },
      {
        "scope": "invalid.illegal",
        "settings": {
          "foreground": "#ffffff"
        }
      },
      {
        "scope": "invalid.illegal.bad-ampersand.html",
        "settings": {
          "foreground": "#abb2bf"
        }
      },
      {
        "scope": "invalid.illegal.unrecognized-tag.html",
        "settings": {
          "foreground": "#e06c75"
        }
      },
      {
        "scope": "invalid.broken",
        "settings": {
          "foreground": "#ffffff"
        }
      },
      {
        "scope": "invalid.deprecated",
        "settings": {
          "foreground": "#ffffff"
        }
      },
      {
        "scope": "invalid.deprecated.entity.other.attribute-name.html",
        "settings": {
          "foreground": "#d19a66"
        }
      },
      {
        "scope": "invalid.unimplemented",
        "settings": {
          "foreground": "#ffffff"
        }
      },
      {
        "scope": "source.json meta.structure.dictionary.json > string.quoted.json",
        "settings": {
          "foreground": "#e06c75"
        }
      },
      {
        "scope": "source.json meta.structure.dictionary.json > string.quoted.json > punctuation.string",
        "settings": {
          "foreground": "#e06c75"
        }
      },
      {
        "scope": "source.json meta.structure.dictionary.json > value.json > string.quoted.json,source.json meta.structure.array.json > value.json > string.quoted.json,source.json meta.structure.dictionary.json > value.json > string.quoted.json > punctuation,source.json meta.structure.array.json > value.json > string.quoted.json > punctuation",
        "settings": {
          "foreground": "#98c379"
        }
      },
      {
        "scope": "source.json meta.structure.dictionary.json > constant.language.json,source.json meta.structure.array.json > constant.language.json",
        "settings": {
          "foreground": "#56b6c2"
        }
      },
      {
        "scope": "support.type.property-name.json",
        "settings": {
          "foreground": "#e06c75"
        }
      },
      {
        "scope": "support.type.property-name.json punctuation",
        "settings": {
          "foreground": "#e06c75"
        }
      },
      {
        "scope": "text.html.laravel-blade source.php.embedded.line.html entity.name.tag.laravel-blade",
        "settings": {
          "foreground": "#c678dd"
        }
      },
      {
        "scope": "text.html.laravel-blade source.php.embedded.line.html support.constant.laravel-blade",
        "settings": {
          "foreground": "#c678dd"
        }
      },
      {
        "scope": "support.other.namespace.use.php,support.other.namespace.use-as.php,entity.other.alias.php,meta.interface.php",
        "settings": {
          "foreground": "#e5c07b"
        }
      },
      {
        "scope": "keyword.operator.error-control.php",
        "settings": {
          "foreground": "#c678dd"
        }
      },
      {
        "scope": "keyword.operator.type.php",
        "settings": {
          "foreground": "#c678dd"
        }
      },
      {
        "scope": "punctuation.section.array.begin.php",
        "settings": {
          "foreground": "#abb2bf"
        }
      },
      {
        "scope": "punctuation.section.array.end.php",
        "settings": {
          "foreground": "#abb2bf"
        }
      },
      {
        "scope": "invalid.illegal.non-null-typehinted.php",
        "settings": {
          "foreground": "#f44747"
        }
      },
      {
        "scope": "storage.type.php,meta.other.type.phpdoc.php,keyword.other.type.php,keyword.other.array.phpdoc.php",
        "settings": {
          "foreground": "#e5c07b"
        }
      },
      {
        "scope": "meta.function-call.php,meta.function-call.object.php,meta.function-call.static.php",
        "settings": {
          "foreground": "#61afef"
        }
      },
      {
        "scope": "punctuation.definition.parameters.begin.bracket.round.php,punctuation.definition.parameters.end.bracket.round.php,punctuation.separator.delimiter.php,punctuation.section.scope.begin.php,punctuation.section.scope.end.php,punctuation.terminator.expression.php,punctuation.definition.arguments.begin.bracket.round.php,punctuation.definition.arguments.end.bracket.round.php,punctuation.definition.storage-type.begin.bracket.round.php,punctuation.definition.storage-type.end.bracket.round.php,punctuation.definition.array.begin.bracket.round.php,punctuation.definition.array.end.bracket.round.php,punctuation.definition.begin.bracket.round.php,punctuation.definition.end.bracket.round.php,punctuation.definition.begin.bracket.curly.php,punctuation.definition.end.bracket.curly.php,punctuation.definition.section.switch-block.end.bracket.curly.php,punctuation.definition.section.switch-block.start.bracket.curly.php,punctuation.definition.section.switch-block.begin.bracket.curly.php,punctuation.definition.section.switch-block.end.bracket.curly.php",
        "settings": {
          "foreground": "#abb2bf"
        }
      },
      {
        "scope": "support.constant.core.rust",
        "settings": {
          "foreground": "#d19a66"
        }
      },
      {
        "scope": "support.constant.ext.php,support.constant.std.php,support.constant.core.php,support.constant.parser-token.php",
        "settings": {
          "foreground": "#d19a66"
        }
      },
      {
        "scope": "entity.name.goto-label.php,support.other.php",
        "settings": {
          "foreground": "#61afef"
        }
      },
      {
        "scope": "keyword.operator.logical.php,keyword.operator.bitwise.php,keyword.operator.arithmetic.php",
        "settings": {
          "foreground": "#56b6c2"
        }
      },
      {
        "scope": "keyword.operator.regexp.php",
        "settings": {
          "foreground": "#c678dd"
        }
      },
      {
        "scope": "keyword.operator.comparison.php",
        "settings": {
          "foreground": "#56b6c2"
        }
      },
      {
        "scope": "keyword.operator.heredoc.php,keyword.operator.nowdoc.php",
        "settings": {
          "foreground": "#c678dd"
        }
      },
      {
        "scope": "meta.function.decorator.python",
        "settings": {
          "foreground": "#61afef"
        }
      },
      {
        "scope": "support.token.decorator.python,meta.function.decorator.identifier.python",
        "settings": {
          "foreground": "#56b6c2"
        }
      },
      {
        "scope": "function.parameter",
        "settings": {
          "foreground": "#abb2bf"
        }
      },
      {
        "scope": "function.brace",
        "settings": {
          "foreground": "#abb2bf"
        }
      },
      {
        "scope": "function.parameter.ruby, function.parameter.cs",
        "settings": {
          "foreground": "#abb2bf"
        }
      },
      {
        "scope": "constant.language.symbol.ruby",
        "settings": {
          "foreground": "#56b6c2"
        }
      },
      {
        "scope": "constant.language.symbol.hashkey.ruby",
        "settings": {
          "foreground": "#56b6c2"
        }
      },
      {
        "scope": "rgb-value",
        "settings": {
          "foreground": "#56b6c2"
        }
      },
      {
        "scope": "inline-color-decoration rgb-value",
        "settings": {
          "foreground": "#d19a66"
        }
      },
      {
        "scope": "less rgb-value",
        "settings": {
          "foreground": "#d19a66"
        }
      },
      {
        "scope": "selector.sass",
        "settings": {
          "foreground": "#e06c75"
        }
      },
      {
        "scope": "support.type.primitive.ts,support.type.builtin.ts,support.type.primitive.tsx,support.type.builtin.tsx",
        "settings": {
          "foreground": "#e5c07b"
        }
      },
      {
        "scope": "block.scope.end,block.scope.begin",
        "settings": {
          "foreground": "#abb2bf"
        }
      },
      {
        "scope": "storage.type.cs",
        "settings": {
          "foreground": "#e5c07b"
        }
      },
      {
        "scope": "entity.name.variable.local.cs",
        "settings": {
          "foreground": "#e06c75"
        }
      },
      {
        "scope": "token.info-token",
        "settings": {
          "foreground": "#61afef"
        }
      },
      {
        "scope": "token.warn-token",
        "settings": {
          "foreground": "#d19a66"
        }
      },
      {
        "scope": "token.error-token",
        "settings": {
          "foreground": "#f44747"
        }
      },
      {
        "scope": "token.debug-token",
        "settings": {
          "foreground": "#c678dd"
        }
      },
      {
        "scope": [
          "punctuation.definition.template-expression.begin",
          "punctuation.definition.template-expression.end",
          "punctuation.section.embedded"
        ],
        "settings": {
          "foreground": "#c678dd"
        }
      },
      {
        "scope": [
          "meta.template.expression"
        ],
        "settings": {
          "foreground": "#abb2bf"
        }
      },
      {
        "scope": [
          "keyword.operator.module"
        ],
        "settings": {
          "foreground": "#c678dd"
        }
      },
      {
        "scope": [
          "support.type.type.flowtype"
        ],
        "settings": {
          "foreground": "#61afef"
        }
      },
      {
        "scope": [
          "support.type.primitive"
        ],
        "settings": {
          "foreground": "#e5c07b"
        }
      },
      {
        "scope": [
          "meta.property.object"
        ],
        "settings": {
          "foreground": "#e06c75"
        }
      },
      {
        "scope": [
          "variable.parameter.function.js"
        ],
        "settings": {
          "foreground": "#e06c75"
        }
      },
      {
        "scope": [
          "keyword.other.template.begin"
        ],
        "settings": {
          "foreground": "#98c379"
        }
      },
      {
        "scope": [
          "keyword.other.template.end"
        ],
        "settings": {
          "foreground": "#98c379"
        }
      },
      {
        "scope": [
          "keyword.other.substitution.begin"
        ],
        "settings": {
          "foreground": "#98c379"
        }
      },
      {
        "scope": [
          "keyword.other.substitution.end"
        ],
        "settings": {
          "foreground": "#98c379"
        }
      },
      {
        "scope": [
          "keyword.operator.assignment"
        ],
        "settings": {
          "foreground": "#56b6c2"
        }
      },
      {
        "scope": [
          "keyword.operator.assignment.go"
        ],
        "settings": {
          "foreground": "#e5c07b"
        }
      },
      {
        "scope": [
          "keyword.operator.arithmetic.go",
          "keyword.operator.address.go"
        ],
        "settings": {
          "foreground": "#c678dd"
        }
      },
      {
        "scope": [
          "keyword.operator.arithmetic.c",
          "keyword.operator.arithmetic.cpp"
        ],
        "settings": {
          "foreground": "#c678dd"
        }
      },
      {
        "scope": [
          "entity.name.package.go"
        ],
        "settings": {
          "foreground": "#e5c07b"
        }
      },
      {
        "scope": [
          "support.type.prelude.elm"
        ],
        "settings": {
          "foreground": "#56b6c2"
        }
      },
      {
        "scope": [
          "support.constant.elm"
        ],
        "settings": {
          "foreground": "#d19a66"
        }
      },
      {
        "scope": [
          "punctuation.quasi.element"
        ],
        "settings": {
          "foreground": "#c678dd"
        }
      },
      {
        "scope": [
          "constant.character.entity"
        ],
        "settings": {
          "foreground": "#e06c75"
        }
      },
      {
        "scope": [
          "entity.other.attribute-name.pseudo-element",
          "entity.other.attribute-name.pseudo-class"
        ],
        "settings": {
          "foreground": "#56b6c2"
        }
      },
      {
        "scope": [
          "entity.global.clojure"
        ],
        "settings": {
          "foreground": "#e5c07b"
        }
      },
      {
        "scope": [
          "meta.symbol.clojure"
        ],
        "settings": {
          "foreground": "#e06c75"
        }
      },
      {
        "scope": [
          "constant.keyword.clojure"
        ],
        "settings": {
          "foreground": "#56b6c2"
        }
      },
      {
        "scope": [
          "meta.arguments.coffee",
          "variable.parameter.function.coffee"
        ],
        "settings": {
          "foreground": "#e06c75"
        }
      },
      {
        "scope": [
          "source.ini"
        ],
        "settings": {
          "foreground": "#98c379"
        }
      },
      {
        "scope": [
          "meta.scope.prerequisites.makefile"
        ],
        "settings": {
          "foreground": "#e06c75"
        }
      },
      {
        "scope": [
          "source.makefile"
        ],
        "settings": {
          "foreground": "#e5c07b"
        }
      },
      {
        "scope": [
          "storage.modifier.import.groovy"
        ],
        "settings": {
          "foreground": "#e5c07b"
        }
      },
      {
        "scope": [
          "meta.method.groovy"
        ],
        "settings": {
          "foreground": "#61afef"
        }
      },
      {
        "scope": [
          "meta.definition.variable.name.groovy"
        ],
        "settings": {
          "foreground": "#e06c75"
        }
      },
      {
        "scope": [
          "meta.definition.class.inherited.classes.groovy"
        ],
        "settings": {
          "foreground": "#98c379"
        }
      },
      {
        "scope": [
          "support.variable.semantic.hlsl"
        ],
        "settings": {
          "foreground": "#e5c07b"
        }
      },
      {
        "scope": [
          "support.type.texture.hlsl",
          "support.type.sampler.hlsl",
          "support.type.object.hlsl",
          "support.type.object.rw.hlsl",
          "support.type.fx.hlsl",
          "support.type.object.hlsl"
        ],
        "settings": {
          "foreground": "#c678dd"
        }
      },
      {
        "scope": [
          "text.variable",
          "text.bracketed"
        ],
        "settings": {
          "foreground": "#e06c75"
        }
      },
      {
        "scope": [
          "support.type.swift",
          "support.type.vb.asp"
        ],
        "settings": {
          "foreground": "#e5c07b"
        }
      },
      {
        "scope": [
          "entity.name.function.xi"
        ],
        "settings": {
          "foreground": "#e5c07b"
        }
      },
      {
        "scope": [
          "entity.name.class.xi"
        ],
        "settings": {
          "foreground": "#56b6c2"
        }
      },
      {
        "scope": [
          "constant.character.character-class.regexp.xi"
        ],
        "settings": {
          "foreground": "#e06c75"
        }
      },
      {
        "scope": [
          "constant.regexp.xi"
        ],
        "settings": {
          "foreground": "#c678dd"
        }
      },
      {
        "scope": [
          "keyword.control.xi"
        ],
        "settings": {
          "foreground": "#56b6c2"
        }
      },
      {
        "scope": [
          "invalid.xi"
        ],
        "settings": {
          "foreground": "#abb2bf"
        }
      },
      {
        "scope": [
          "beginning.punctuation.definition.quote.markdown.xi"
        ],
        "settings": {
          "foreground": "#98c379"
        }
      },
      {
        "scope": [
          "beginning.punctuation.definition.list.markdown.xi"
        ],
        "settings": {
          "foreground": "#7f848e"
        }
      },
      {
        "scope": [
          "constant.character.xi"
        ],
        "settings": {
          "foreground": "#61afef"
        }
      },
      {
        "scope": [
          "accent.xi"
        ],
        "settings": {
          "foreground": "#61afef"
        }
      },
      {
        "scope": [
          "wikiword.xi"
        ],
        "settings": {
          "foreground": "#d19a66"
        }
      },
      {
        "scope": [
          "constant.other.color.rgb-value.xi"
        ],
        "settings": {
          "foreground": "#ffffff"
        }
      },
      {
        "scope": [
          "punctuation.definition.tag.xi"
        ],
        "settings": {
          "foreground": "#5c6370"
        }
      },
      {
        "scope": [
          "entity.name.label.cs",
          "entity.name.scope-resolution.function.call",
          "entity.name.scope-resolution.function.definition"
        ],
        "settings": {
          "foreground": "#e5c07b"
        }
      },
      {
        "scope": [
          "entity.name.label.cs",
          "markup.heading.setext.1.markdown",
          "markup.heading.setext.2.markdown"
        ],
        "settings": {
          "foreground": "#e06c75"
        }
      },
      {
        "scope": [
          " meta.brace.square"
        ],
        "settings": {
          "foreground": "#abb2bf"
        }
      },
      {
        "scope": "comment, punctuation.definition.comment",
        "settings": {
          "fontStyle": "italic",
          "foreground": "#7f848e"
        }
      },
      {
        "scope": "markup.quote.markdown",
        "settings": {
          "foreground": "#5c6370"
        }
      },
      {
        "scope": "punctuation.definition.block.sequence.item.yaml",
        "settings": {
          "foreground": "#abb2bf"
        }
      },
      {
        "scope": [
          "constant.language.symbol.elixir",
          "constant.language.symbol.double-quoted.elixir"
        ],
        "settings": {
          "foreground": "#56b6c2"
        }
      },
      {
        "scope": [
          "entity.name.variable.parameter.cs"
        ],
        "settings": {
          "foreground": "#e5c07b"
        }
      },
      {
        "scope": [
          "entity.name.variable.field.cs"
        ],
        "settings": {
          "foreground": "#e06c75"
        }
      },
      {
        "scope": "markup.deleted",
        "settings": {
          "foreground": "#e06c75"
        }
      },
      {
        "scope": "markup.inserted",
        "settings": {
          "foreground": "#98c379"
        }
      },
      {
        "scope": "markup.underline",
        "settings": {
          "fontStyle": "underline"
        }
      },
      {
        "scope": [
          "punctuation.section.embedded.begin.php",
          "punctuation.section.embedded.end.php"
        ],
        "settings": {
          "foreground": "#BE5046"
        }
      },
      {
        "scope": [
          "support.other.namespace.php"
        ],
        "settings": {
          "foreground": "#abb2bf"
        }
      },
      {
        "scope": [
          "variable.parameter.function.latex"
        ],
        "settings": {
          "foreground": "#e06c75"
        }
      },
      {
        "scope": [
          "variable.other.object"
        ],
        "settings": {
          "foreground": "#e5c07b"
        }
      },
      {
        "scope": [
          "variable.other.constant.property"
        ],
        "settings": {
          "foreground": "#e06c75"
        }
      },
      {
        "scope": [
          "entity.other.inherited-class"
        ],
        "settings": {
          "foreground": "#e5c07b"
        }
      },
      {
        "scope": "variable.other.readwrite.c",
        "settings": {
          "foreground": "#e06c75"
        }
      },
      {
        "scope": "entity.name.variable.parameter.php,punctuation.separator.colon.php,constant.other.php",
        "settings": {
          "foreground": "#abb2bf"
        }
      },
      {
        "scope": [
          "constant.numeric.decimal.asm.x86_64"
        ],
        "settings": {
          "foreground": "#c678dd"
        }
      },
      {
        "scope": [
          "support.other.parenthesis.regexp"
        ],
        "settings": {
          "foreground": "#d19a66"
        }
      },
      {
        "scope": [
          "constant.character.escape"
        ],
        "settings": {
          "foreground": "#56b6c2"
        }
      },
      {
        "scope": [
          "string.regexp"
        ],
        "settings": {
          "foreground": "#e06c75"
        }
      },
      {
        "scope": [
          "log.info"
        ],
        "settings": {
          "foreground": "#98c379"
        }
      },
      {
        "scope": [
          "log.warning"
        ],
        "settings": {
          "foreground": "#e5c07b"
        }
      },
      {
        "scope": [
          "log.error"
        ],
        "settings": {
          "foreground": "#e06c75"
        }
      },
      {
        "scope": "keyword.operator.expression.is",
        "settings": {
          "foreground": "#c678dd"
        }
      },
      {
        "scope": "entity.name.label",
        "settings": {
          "foreground": "#e06c75"
        }
      },
      {
        "scope": [
          "support.class.math.block.environment.latex",
          "constant.other.general.math.tex"
        ],
        "settings": {
          "foreground": "#61afef"
        }
      },
      {
        "scope": [
          "constant.character.math.tex"
        ],
        "settings": {
          "foreground": "#98c379"
        }
      },
      {
        "scope": "entity.other.attribute-name.js,entity.other.attribute-name.ts,entity.other.attribute-name.jsx,entity.other.attribute-name.tsx,variable.parameter,variable.language.super",
        "settings": {
          "fontStyle": "italic"
        }
      },
      {
        "scope": "comment.line.double-slash,comment.block.documentation",
        "settings": {
          "fontStyle": "italic"
        }
      },
      {
        "scope": "markup.italic.markdown",
        "settings": {
          "fontStyle": "italic"
        }
      }
    ],
    "type": "dark"
  },
  "rose-pine-dawn": {
    "colors": {
      "activityBar.activeBorder": "#575279",
      "activityBar.background": "#faf4ed",
      "activityBar.dropBorder": "#f2e9e1",
      "activityBar.foreground": "#575279",
      "activityBar.inactiveForeground": "#797593",
      "activityBarBadge.background": "#d7827e",
      "activityBarBadge.foreground": "#faf4ed",
      "badge.background": "#d7827e",
      "badge.foreground": "#faf4ed",
      "banner.background": "#fffaf3",
      "banner.foreground": "#575279",
      "banner.iconForeground": "#797593",
      "breadcrumb.activeSelectionForeground": "#d7827e",
      "breadcrumb.background": "#faf4ed",
      "breadcrumb.focusForeground": "#797593",
      "breadcrumb.foreground": "#9893a5",
      "breadcrumbPicker.background": "#fffaf3",
      "button.background": "#d7827e",
      "button.foreground": "#faf4ed",
      "button.hoverBackground": "#d7827ee6",
      "button.secondaryBackground": "#fffaf3",
      "button.secondaryForeground": "#575279",
      "button.secondaryHoverBackground": "#f2e9e1",
      "charts.blue": "#56949f",
      "charts.foreground": "#575279",
      "charts.green": "#286983",
      "charts.lines": "#797593",
      "charts.orange": "#d7827e",
      "charts.purple": "#907aa9",
      "charts.red": "#b4637a",
      "charts.yellow": "#ea9d34",
      "checkbox.background": "#fffaf3",
      "checkbox.border": "#6e6a8614",
      "checkbox.foreground": "#575279",
      "debugExceptionWidget.background": "#fffaf3",
      "debugExceptionWidget.border": "#6e6a8614",
      "debugIcon.breakpointCurrentStackframeForeground": "#797593",
      "debugIcon.breakpointDisabledForeground": "#797593",
      "debugIcon.breakpointForeground": "#797593",
      "debugIcon.breakpointStackframeForeground": "#797593",
      "debugIcon.breakpointUnverifiedForeground": "#797593",
      "debugIcon.continueForeground": "#797593",
      "debugIcon.disconnectForeground": "#797593",
      "debugIcon.pauseForeground": "#797593",
      "debugIcon.restartForeground": "#797593",
      "debugIcon.startForeground": "#797593",
      "debugIcon.stepBackForeground": "#797593",
      "debugIcon.stepIntoForeground": "#797593",
      "debugIcon.stepOutForeground": "#797593",
      "debugIcon.stepOverForeground": "#797593",
      "debugIcon.stopForeground": "#b4637a",
      "debugToolBar.background": "#fffaf3",
      "debugToolBar.border": "#f2e9e1",
      "descriptionForeground": "#797593",
      "diffEditor.border": "#f2e9e1",
      "diffEditor.diagonalFill": "#6e6a8626",
      "diffEditor.insertedLineBackground": "#56949f26",
      "diffEditor.insertedTextBackground": "#56949f26",
      "diffEditor.removedLineBackground": "#b4637a26",
      "diffEditor.removedTextBackground": "#b4637a26",
      "diffEditorOverview.insertedForeground": "#56949f80",
      "diffEditorOverview.removedForeground": "#b4637a80",
      "dropdown.background": "#fffaf3",
      "dropdown.border": "#6e6a8614",
      "dropdown.foreground": "#575279",
      "dropdown.listBackground": "#fffaf3",
      "editor.background": "#faf4ed",
      "editor.findMatchBackground": "#ea9d3433",
      "editor.findMatchBorder": "#ea9d3480",
      "editor.findMatchForeground": "#575279",
      "editor.findMatchHighlightBackground": "#6e6a8626",
      "editor.findMatchHighlightForeground": "#575279cc",
      "editor.findRangeHighlightBackground": "#6e6a8626",
      "editor.findRangeHighlightBorder": "#0000",
      "editor.focusedStackFrameHighlightBackground": "#6e6a8614",
      "editor.foldBackground": "#6e6a8614",
      "editor.foreground": "#575279",
      "editor.hoverHighlightBackground": "#0000",
      "editor.inactiveSelectionBackground": "#6e6a860d",
      "editor.inlineValuesBackground": "#0000",
      "editor.inlineValuesForeground": "#797593",
      "editor.lineHighlightBackground": "#6e6a860d",
      "editor.lineHighlightBorder": "#0000",
      "editor.linkedEditingBackground": "#6e6a8614",
      "editor.rangeHighlightBackground": "#6e6a860d",
      "editor.selectionBackground": "#6e6a8614",
      "editor.selectionForeground": "#575279",
      "editor.selectionHighlightBackground": "#6e6a8614",
      "editor.selectionHighlightBorder": "#faf4ed",
      "editor.snippetFinalTabstopHighlightBackground": "#6e6a8614",
      "editor.snippetFinalTabstopHighlightBorder": "#fffaf3",
      "editor.snippetTabstopHighlightBackground": "#6e6a8614",
      "editor.snippetTabstopHighlightBorder": "#fffaf3",
      "editor.stackFrameHighlightBackground": "#6e6a8614",
      "editor.symbolHighlightBackground": "#6e6a8614",
      "editor.symbolHighlightBorder": "#0000",
      "editor.wordHighlightBackground": "#6e6a8614",
      "editor.wordHighlightBorder": "#0000",
      "editor.wordHighlightStrongBackground": "#6e6a8614",
      "editor.wordHighlightStrongBorder": "#6e6a8614",
      "editorBracketHighlight.foreground1": "#b4637a80",
      "editorBracketHighlight.foreground2": "#28698380",
      "editorBracketHighlight.foreground3": "#ea9d3480",
      "editorBracketHighlight.foreground4": "#56949f80",
      "editorBracketHighlight.foreground5": "#d7827e80",
      "editorBracketHighlight.foreground6": "#907aa980",
      "editorBracketMatch.background": "#0000",
      "editorBracketMatch.border": "#797593",
      "editorBracketPairGuide.activeBackground1": "#286983",
      "editorBracketPairGuide.activeBackground2": "#d7827e",
      "editorBracketPairGuide.activeBackground3": "#907aa9",
      "editorBracketPairGuide.activeBackground4": "#56949f",
      "editorBracketPairGuide.activeBackground5": "#ea9d34",
      "editorBracketPairGuide.activeBackground6": "#b4637a",
      "editorBracketPairGuide.background1": "#28698380",
      "editorBracketPairGuide.background2": "#d7827e80",
      "editorBracketPairGuide.background3": "#907aa980",
      "editorBracketPairGuide.background4": "#56949f80",
      "editorBracketPairGuide.background5": "#ea9d3480",
      "editorBracketPairGuide.background6": "#b4637a80",
      "editorCodeLens.foreground": "#d7827e",
      "editorCursor.background": "#575279",
      "editorCursor.foreground": "#9893a5",
      "editorError.border": "#0000",
      "editorError.foreground": "#b4637a",
      "editorGhostText.foreground": "#797593",
      "editorGroup.border": "#0000",
      "editorGroup.dropBackground": "#fffaf3",
      "editorGroup.emptyBackground": "#0000",
      "editorGroup.focusedEmptyBorder": "#0000",
      "editorGroupHeader.noTabsBackground": "#0000",
      "editorGroupHeader.tabsBackground": "#0000",
      "editorGroupHeader.tabsBorder": "#0000",
      "editorGutter.addedBackground": "#56949f",
      "editorGutter.background": "#faf4ed",
      "editorGutter.commentRangeForeground": "#f2e9e1",
      "editorGutter.deletedBackground": "#b4637a",
      "editorGutter.foldingControlForeground": "#907aa9",
      "editorGutter.modifiedBackground": "#d7827e",
      "editorHint.border": "#0000",
      "editorHint.foreground": "#797593",
      "editorHoverWidget.background": "#fffaf3",
      "editorHoverWidget.border": "#9893a580",
      "editorHoverWidget.foreground": "#797593",
      "editorHoverWidget.highlightForeground": "#575279",
      "editorHoverWidget.statusBarBackground": "#0000",
      "editorIndentGuide.activeBackground1": "#9893a5",
      "editorIndentGuide.background1": "#6e6a8626",
      "editorInfo.border": "#f2e9e1",
      "editorInfo.foreground": "#56949f",
      "editorInlayHint.background": "#f2e9e180",
      "editorInlayHint.foreground": "#79759380",
      "editorInlayHint.parameterBackground": "#f2e9e180",
      "editorInlayHint.parameterForeground": "#907aa980",
      "editorInlayHint.typeBackground": "#f2e9e180",
      "editorInlayHint.typeForeground": "#56949f80",
      "editorLightBulb.foreground": "#286983",
      "editorLightBulbAutoFix.foreground": "#d7827e",
      "editorLineNumber.activeForeground": "#575279",
      "editorLineNumber.foreground": "#797593",
      "editorLink.activeForeground": "#d7827e",
      "editorMarkerNavigation.background": "#fffaf3",
      "editorMarkerNavigationError.background": "#fffaf3",
      "editorMarkerNavigationInfo.background": "#fffaf3",
      "editorMarkerNavigationWarning.background": "#fffaf3",
      "editorOverviewRuler.addedForeground": "#56949f80",
      "editorOverviewRuler.background": "#faf4ed",
      "editorOverviewRuler.border": "#6e6a8626",
      "editorOverviewRuler.bracketMatchForeground": "#797593",
      "editorOverviewRuler.commentForeground": "#79759380",
      "editorOverviewRuler.commentUnresolvedForeground": "#ea9d3480",
      "editorOverviewRuler.commonContentForeground": "#6e6a860d",
      "editorOverviewRuler.currentContentForeground": "#6e6a8614",
      "editorOverviewRuler.deletedForeground": "#b4637a80",
      "editorOverviewRuler.errorForeground": "#b4637a80",
      "editorOverviewRuler.findMatchForeground": "#6e6a8626",
      "editorOverviewRuler.incomingContentForeground": "#907aa980",
      "editorOverviewRuler.infoForeground": "#56949f80",
      "editorOverviewRuler.modifiedForeground": "#d7827e80",
      "editorOverviewRuler.rangeHighlightForeground": "#6e6a8626",
      "editorOverviewRuler.selectionHighlightForeground": "#6e6a8626",
      "editorOverviewRuler.warningForeground": "#ea9d3480",
      "editorOverviewRuler.wordHighlightForeground": "#6e6a8614",
      "editorOverviewRuler.wordHighlightStrongForeground": "#6e6a8626",
      "editorPane.background": "#0000",
      "editorRuler.foreground": "#6e6a8626",
      "editorSuggestWidget.background": "#fffaf3",
      "editorSuggestWidget.border": "#0000",
      "editorSuggestWidget.focusHighlightForeground": "#d7827e",
      "editorSuggestWidget.foreground": "#797593",
      "editorSuggestWidget.highlightForeground": "#d7827e",
      "editorSuggestWidget.selectedBackground": "#6e6a8614",
      "editorSuggestWidget.selectedForeground": "#575279",
      "editorSuggestWidget.selectedIconForeground": "#575279",
      "editorUnnecessaryCode.border": "#0000",
      "editorUnnecessaryCode.opacity": "#57527980",
      "editorWarning.border": "#0000",
      "editorWarning.foreground": "#ea9d34",
      "editorWhitespace.foreground": "#9893a580",
      "editorWidget.background": "#fffaf3",
      "editorWidget.border": "#f2e9e1",
      "editorWidget.foreground": "#797593",
      "editorWidget.resizeBorder": "#9893a5",
      "errorForeground": "#b4637a",
      "extensionBadge.remoteBackground": "#907aa9",
      "extensionBadge.remoteForeground": "#faf4ed",
      "extensionButton.prominentBackground": "#d7827e",
      "extensionButton.prominentForeground": "#faf4ed",
      "extensionButton.prominentHoverBackground": "#d7827ee6",
      "extensionIcon.preReleaseForeground": "#286983",
      "extensionIcon.starForeground": "#d7827e",
      "extensionIcon.verifiedForeground": "#907aa9",
      "focusBorder": "#6e6a8614",
      "foreground": "#575279",
      "git.blame.editorDecorationForeground": "#9893a5",
      "gitDecoration.addedResourceForeground": "#56949f",
      "gitDecoration.conflictingResourceForeground": "#b4637a",
      "gitDecoration.deletedResourceForeground": "#797593",
      "gitDecoration.ignoredResourceForeground": "#9893a5",
      "gitDecoration.modifiedResourceForeground": "#d7827e",
      "gitDecoration.renamedResourceForeground": "#286983",
      "gitDecoration.stageDeletedResourceForeground": "#b4637a",
      "gitDecoration.stageModifiedResourceForeground": "#907aa9",
      "gitDecoration.submoduleResourceForeground": "#ea9d34",
      "gitDecoration.untrackedResourceForeground": "#ea9d34",
      "icon.foreground": "#797593",
      "input.background": "#f2e9e180",
      "input.border": "#6e6a8614",
      "input.foreground": "#575279",
      "input.placeholderForeground": "#797593",
      "inputOption.activeBackground": "#d7827e26",
      "inputOption.activeBorder": "#0000",
      "inputOption.activeForeground": "#d7827e",
      "inputValidation.errorBackground": "#fffaf3",
      "inputValidation.errorBorder": "#6e6a8626",
      "inputValidation.errorForeground": "#b4637a",
      "inputValidation.infoBackground": "#fffaf3",
      "inputValidation.infoBorder": "#6e6a8626",
      "inputValidation.infoForeground": "#56949f",
      "inputValidation.warningBackground": "#fffaf3",
      "inputValidation.warningBorder": "#6e6a8626",
      "inputValidation.warningForeground": "#56949f80",
      "keybindingLabel.background": "#f2e9e1",
      "keybindingLabel.border": "#6e6a8626",
      "keybindingLabel.bottomBorder": "#6e6a8626",
      "keybindingLabel.foreground": "#907aa9",
      "keybindingTable.headerBackground": "#f2e9e1",
      "keybindingTable.rowsBackground": "#fffaf3",
      "list.activeSelectionBackground": "#6e6a8614",
      "list.activeSelectionForeground": "#575279",
      "list.deemphasizedForeground": "#797593",
      "list.dropBackground": "#fffaf3",
      "list.errorForeground": "#b4637a",
      "list.filterMatchBackground": "#fffaf3",
      "list.filterMatchBorder": "#d7827e",
      "list.focusBackground": "#6e6a8626",
      "list.focusForeground": "#575279",
      "list.focusOutline": "#6e6a8614",
      "list.highlightForeground": "#d7827e",
      "list.hoverBackground": "#6e6a860d",
      "list.hoverForeground": "#575279",
      "list.inactiveFocusBackground": "#6e6a860d",
      "list.inactiveSelectionBackground": "#fffaf3",
      "list.inactiveSelectionForeground": "#575279",
      "list.invalidItemForeground": "#b4637a",
      "list.warningForeground": "#ea9d34",
      "listFilterWidget.background": "#fffaf3",
      "listFilterWidget.noMatchesOutline": "#b4637a",
      "listFilterWidget.outline": "#f2e9e1",
      "menu.background": "#fffaf3",
      "menu.border": "#6e6a860d",
      "menu.foreground": "#575279",
      "menu.selectionBackground": "#6e6a8614",
      "menu.selectionBorder": "#f2e9e1",
      "menu.selectionForeground": "#575279",
      "menu.separatorBackground": "#6e6a8626",
      "menubar.selectionBackground": "#6e6a8614",
      "menubar.selectionBorder": "#6e6a860d",
      "menubar.selectionForeground": "#575279",
      "merge.border": "#f2e9e1",
      "merge.commonContentBackground": "#6e6a8614",
      "merge.commonHeaderBackground": "#6e6a8614",
      "merge.currentContentBackground": "#ea9d3433",
      "merge.currentHeaderBackground": "#ea9d3433",
      "merge.incomingContentBackground": "#56949f33",
      "merge.incomingHeaderBackground": "#56949f33",
      "minimap.background": "#fffaf3",
      "minimap.errorHighlight": "#b4637a80",
      "minimap.findMatchHighlight": "#6e6a8614",
      "minimap.selectionHighlight": "#6e6a8614",
      "minimap.warningHighlight": "#ea9d3480",
      "minimapGutter.addedBackground": "#56949f",
      "minimapGutter.deletedBackground": "#b4637a",
      "minimapGutter.modifiedBackground": "#d7827e",
      "minimapSlider.activeBackground": "#6e6a8626",
      "minimapSlider.background": "#6e6a8614",
      "minimapSlider.hoverBackground": "#6e6a8614",
      "notebook.cellBorderColor": "#56949f80",
      "notebook.cellEditorBackground": "#fffaf3",
      "notebook.cellHoverBackground": "#f2e9e180",
      "notebook.focusedCellBackground": "#6e6a860d",
      "notebook.focusedCellBorder": "#56949f",
      "notebook.outputContainerBackgroundColor": "#6e6a860d",
      "notificationCenter.border": "#6e6a8614",
      "notificationCenterHeader.background": "#fffaf3",
      "notificationCenterHeader.foreground": "#797593",
      "notificationLink.foreground": "#907aa9",
      "notifications.background": "#fffaf3",
      "notifications.border": "#6e6a8614",
      "notifications.foreground": "#575279",
      "notificationsErrorIcon.foreground": "#b4637a",
      "notificationsInfoIcon.foreground": "#56949f",
      "notificationsWarningIcon.foreground": "#ea9d34",
      "notificationToast.border": "#6e6a8614",
      "panel.background": "#fffaf3",
      "panel.border": "#0000",
      "panel.dropBorder": "#f2e9e1",
      "panelInput.border": "#fffaf3",
      "panelSection.dropBackground": "#6e6a8614",
      "panelSectionHeader.background": "#fffaf3",
      "panelSectionHeader.foreground": "#575279",
      "panelTitle.activeBorder": "#6e6a8626",
      "panelTitle.activeForeground": "#575279",
      "panelTitle.inactiveForeground": "#797593",
      "peekView.border": "#f2e9e1",
      "peekViewEditor.background": "#fffaf3",
      "peekViewEditor.matchHighlightBackground": "#6e6a8626",
      "peekViewResult.background": "#fffaf3",
      "peekViewResult.fileForeground": "#797593",
      "peekViewResult.lineForeground": "#797593",
      "peekViewResult.matchHighlightBackground": "#6e6a8626",
      "peekViewResult.selectionBackground": "#6e6a8614",
      "peekViewResult.selectionForeground": "#575279",
      "peekViewTitle.background": "#f2e9e1",
      "peekViewTitleDescription.foreground": "#797593",
      "pickerGroup.border": "#6e6a8626",
      "pickerGroup.foreground": "#907aa9",
      "ports.iconRunningProcessForeground": "#d7827e",
      "problemsErrorIcon.foreground": "#b4637a",
      "problemsInfoIcon.foreground": "#56949f",
      "problemsWarningIcon.foreground": "#ea9d34",
      "progressBar.background": "#d7827e",
      "quickInput.background": "#fffaf3",
      "quickInput.foreground": "#797593",
      "quickInputList.focusBackground": "#6e6a8614",
      "quickInputList.focusForeground": "#575279",
      "quickInputList.focusIconForeground": "#575279",
      "scrollbar.shadow": "#fffaf34d",
      "scrollbarSlider.activeBackground": "#28698380",
      "scrollbarSlider.background": "#6e6a8614",
      "scrollbarSlider.hoverBackground": "#6e6a8626",
      "searchEditor.findMatchBackground": "#6e6a8614",
      "selection.background": "#6e6a8626",
      "settings.focusedRowBackground": "#fffaf3",
      "settings.focusedRowBorder": "#6e6a8614",
      "settings.headerForeground": "#575279",
      "settings.modifiedItemIndicator": "#d7827e",
      "settings.rowHoverBackground": "#fffaf3",
      "sideBar.background": "#faf4ed",
      "sideBar.dropBackground": "#fffaf3",
      "sideBar.foreground": "#797593",
      "sideBarSectionHeader.background": "#0000",
      "sideBarSectionHeader.border": "#6e6a8614",
      "statusBar.background": "#faf4ed",
      "statusBar.debuggingBackground": "#907aa9",
      "statusBar.debuggingForeground": "#faf4ed",
      "statusBar.foreground": "#797593",
      "statusBar.noFolderBackground": "#faf4ed",
      "statusBar.noFolderForeground": "#797593",
      "statusBarItem.activeBackground": "#6e6a8626",
      "statusBarItem.errorBackground": "#faf4ed",
      "statusBarItem.errorForeground": "#b4637a",
      "statusBarItem.hoverBackground": "#6e6a8614",
      "statusBarItem.prominentBackground": "#f2e9e1",
      "statusBarItem.prominentForeground": "#575279",
      "statusBarItem.prominentHoverBackground": "#6e6a8614",
      "statusBarItem.remoteBackground": "#faf4ed",
      "statusBarItem.remoteForeground": "#ea9d34",
      "symbolIcon.arrayForeground": "#797593",
      "symbolIcon.classForeground": "#797593",
      "symbolIcon.colorForeground": "#797593",
      "symbolIcon.constantForeground": "#797593",
      "symbolIcon.constructorForeground": "#797593",
      "symbolIcon.enumeratorForeground": "#797593",
      "symbolIcon.enumeratorMemberForeground": "#797593",
      "symbolIcon.eventForeground": "#797593",
      "symbolIcon.fieldForeground": "#797593",
      "symbolIcon.fileForeground": "#797593",
      "symbolIcon.folderForeground": "#797593",
      "symbolIcon.functionForeground": "#797593",
      "symbolIcon.interfaceForeground": "#797593",
      "symbolIcon.keyForeground": "#797593",
      "symbolIcon.keywordForeground": "#797593",
      "symbolIcon.methodForeground": "#797593",
      "symbolIcon.moduleForeground": "#797593",
      "symbolIcon.namespaceForeground": "#797593",
      "symbolIcon.nullForeground": "#797593",
      "symbolIcon.numberForeground": "#797593",
      "symbolIcon.objectForeground": "#797593",
      "symbolIcon.operatorForeground": "#797593",
      "symbolIcon.packageForeground": "#797593",
      "symbolIcon.propertyForeground": "#797593",
      "symbolIcon.referenceForeground": "#797593",
      "symbolIcon.snippetForeground": "#797593",
      "symbolIcon.stringForeground": "#797593",
      "symbolIcon.structForeground": "#797593",
      "symbolIcon.textForeground": "#797593",
      "symbolIcon.typeParameterForeground": "#797593",
      "symbolIcon.unitForeground": "#797593",
      "symbolIcon.variableForeground": "#797593",
      "tab.activeBackground": "#6e6a860d",
      "tab.activeForeground": "#575279",
      "tab.activeModifiedBorder": "#56949f",
      "tab.border": "#0000",
      "tab.hoverBackground": "#6e6a8614",
      "tab.inactiveBackground": "#0000",
      "tab.inactiveForeground": "#797593",
      "tab.inactiveModifiedBorder": "#56949f80",
      "tab.lastPinnedBorder": "#9893a5",
      "tab.unfocusedActiveBackground": "#0000",
      "tab.unfocusedHoverBackground": "#0000",
      "tab.unfocusedInactiveBackground": "#0000",
      "tab.unfocusedInactiveModifiedBorder": "#56949f80",
      "terminal.ansiBlack": "#f2e9e1",
      "terminal.ansiBlue": "#56949f",
      "terminal.ansiBrightBlack": "#797593",
      "terminal.ansiBrightBlue": "#56949f",
      "terminal.ansiBrightCyan": "#d7827e",
      "terminal.ansiBrightGreen": "#286983",
      "terminal.ansiBrightMagenta": "#907aa9",
      "terminal.ansiBrightRed": "#b4637a",
      "terminal.ansiBrightWhite": "#575279",
      "terminal.ansiBrightYellow": "#ea9d34",
      "terminal.ansiCyan": "#d7827e",
      "terminal.ansiGreen": "#286983",
      "terminal.ansiMagenta": "#907aa9",
      "terminal.ansiRed": "#b4637a",
      "terminal.ansiWhite": "#575279",
      "terminal.ansiYellow": "#ea9d34",
      "terminal.dropBackground": "#6e6a8614",
      "terminal.foreground": "#575279",
      "terminal.selectionBackground": "#6e6a8614",
      "terminal.tab.activeBorder": "#575279",
      "terminalCursor.background": "#575279",
      "terminalCursor.foreground": "#9893a5",
      "textBlockQuote.background": "#fffaf3",
      "textBlockQuote.border": "#6e6a8614",
      "textCodeBlock.background": "#fffaf3",
      "textLink.activeForeground": "#907aa9e6",
      "textLink.foreground": "#907aa9",
      "textPreformat.foreground": "#ea9d34",
      "textSeparator.foreground": "#797593",
      "titleBar.activeBackground": "#faf4ed",
      "titleBar.activeForeground": "#797593",
      "titleBar.inactiveBackground": "#fffaf3",
      "titleBar.inactiveForeground": "#797593",
      "toolbar.activeBackground": "#6e6a8626",
      "toolbar.hoverBackground": "#6e6a8614",
      "tree.indentGuidesStroke": "#797593",
      "walkThrough.embeddedEditorBackground": "#faf4ed",
      "welcomePage.background": "#faf4ed",
      "widget.shadow": "#fffaf34d",
      "window.activeBorder": "#fffaf3",
      "window.inactiveBorder": "#fffaf3"
    },
    "name": "rose-pine-dawn",
    "tokenColors": [
      {
        "scope": [
          "comment"
        ],
        "settings": {
          "fontStyle": "italic",
          "foreground": "#9893a5"
        }
      },
      {
        "scope": [
          "constant"
        ],
        "settings": {
          "foreground": "#286983"
        }
      },
      {
        "scope": [
          "constant.numeric",
          "constant.language"
        ],
        "settings": {
          "foreground": "#d7827e"
        }
      },
      {
        "scope": [
          "entity.name"
        ],
        "settings": {
          "foreground": "#d7827e"
        }
      },
      {
        "scope": [
          "entity.name.section",
          "entity.name.tag",
          "entity.name.namespace",
          "entity.name.type"
        ],
        "settings": {
          "foreground": "#56949f"
        }
      },
      {
        "scope": [
          "entity.other.attribute-name",
          "entity.other.inherited-class"
        ],
        "settings": {
          "fontStyle": "italic",
          "foreground": "#907aa9"
        }
      },
      {
        "scope": [
          "invalid"
        ],
        "settings": {
          "foreground": "#b4637a"
        }
      },
      {
        "scope": [
          "invalid.deprecated"
        ],
        "settings": {
          "foreground": "#797593"
        }
      },
      {
        "scope": [
          "keyword",
          "variable.language.this"
        ],
        "settings": {
          "foreground": "#286983"
        }
      },
      {
        "scope": [
          "markup.inserted.diff"
        ],
        "settings": {
          "foreground": "#56949f"
        }
      },
      {
        "scope": [
          "markup.deleted.diff"
        ],
        "settings": {
          "foreground": "#b4637a"
        }
      },
      {
        "scope": "markup.heading",
        "settings": {
          "fontStyle": "bold"
        }
      },
      {
        "scope": "markup.bold.markdown",
        "settings": {
          "fontStyle": "bold"
        }
      },
      {
        "scope": "markup.italic.markdown",
        "settings": {
          "fontStyle": "italic"
        }
      },
      {
        "scope": [
          "meta.diff.range"
        ],
        "settings": {
          "foreground": "#907aa9"
        }
      },
      {
        "scope": [
          "meta.tag",
          "meta.brace"
        ],
        "settings": {
          "foreground": "#575279"
        }
      },
      {
        "scope": [
          "meta.import",
          "meta.export"
        ],
        "settings": {
          "foreground": "#286983"
        }
      },
      {
        "scope": "meta.directive.vue",
        "settings": {
          "fontStyle": "italic",
          "foreground": "#907aa9"
        }
      },
      {
        "scope": "meta.property-name.css",
        "settings": {
          "foreground": "#56949f"
        }
      },
      {
        "scope": "meta.property-value.css",
        "settings": {
          "foreground": "#ea9d34"
        }
      },
      {
        "scope": "meta.tag.other.html",
        "settings": {
          "foreground": "#797593"
        }
      },
      {
        "scope": [
          "punctuation"
        ],
        "settings": {
          "foreground": "#797593"
        }
      },
      {
        "scope": [
          "punctuation.accessor"
        ],
        "settings": {
          "foreground": "#286983"
        }
      },
      {
        "scope": [
          "punctuation.definition.string"
        ],
        "settings": {
          "foreground": "#ea9d34"
        }
      },
      {
        "scope": [
          "punctuation.definition.tag"
        ],
        "settings": {
          "foreground": "#9893a5"
        }
      },
      {
        "scope": [
          "storage.type",
          "storage.modifier"
        ],
        "settings": {
          "foreground": "#286983"
        }
      },
      {
        "scope": [
          "string"
        ],
        "settings": {
          "foreground": "#ea9d34"
        }
      },
      {
        "scope": [
          "support"
        ],
        "settings": {
          "foreground": "#56949f"
        }
      },
      {
        "scope": [
          "support.constant"
        ],
        "settings": {
          "foreground": "#ea9d34"
        }
      },
      {
        "scope": [
          "support.function"
        ],
        "settings": {
          "fontStyle": "italic",
          "foreground": "#b4637a"
        }
      },
      {
        "scope": [
          "variable"
        ],
        "settings": {
          "fontStyle": "italic",
          "foreground": "#d7827e"
        }
      },
      {
        "scope": [
          "variable.other",
          "variable.language",
          "variable.function",
          "variable.argument"
        ],
        "settings": {
          "foreground": "#575279"
        }
      },
      {
        "scope": [
          "variable.parameter"
        ],
        "settings": {
          "foreground": "#907aa9"
        }
      }
    ],
    "type": "light"
  },
} as unknown as Readonly<Record<string, ThemeRegistration>>
