// Generated by scripts/generate-codex-themes.ts from .
// Do not edit this file manually.
import type { ThemeRegistration } from 'shiki'

export const themes = {

} as unknown as Readonly<Record<string, ThemeRegistration>>
