// Generated by scripts/generate-codex-themes.ts from github-light-default-BiToXucL.js, github-light-default-BoCrtMwS.js, gruvbox-light-medium-BUoTX1kc.js, gruvbox-light-medium-CZhGxS8I.js, matrix-dark-r0o3RVz1.js, rose-pine-moon-D-H0rxwo.js, rose-pine-moon-DW5GYyfK.js, solarized-dark-CcRUsLNQ.js, solarized-dark-PKzXpC8j.js, temple-dark-Dow-mbbS.js.
// Do not edit this file manually.
import type { ThemeRegistration } from 'shiki'

export const themes = {
  "github-light-default": {
    "colors": {
      "activityBar.activeBorder": "#fd8c73",
      "activityBar.background": "#ffffff",
      "activityBar.border": "#d0d7de",
      "activityBar.foreground": "#1f2328",
      "activityBar.inactiveForeground": "#656d76",
      "activityBarBadge.background": "#0969da",
      "activityBarBadge.foreground": "#ffffff",
      "badge.background": "#0969da",
      "badge.foreground": "#ffffff",
      "breadcrumb.activeSelectionForeground": "#656d76",
      "breadcrumb.focusForeground": "#1f2328",
      "breadcrumb.foreground": "#656d76",
      "breadcrumbPicker.background": "#ffffff",
      "button.background": "#1f883d",
      "button.foreground": "#ffffff",
      "button.hoverBackground": "#1a7f37",
      "button.secondaryBackground": "#ebecf0",
      "button.secondaryForeground": "#24292f",
      "button.secondaryHoverBackground": "#f3f4f6",
      "checkbox.background": "#f6f8fa",
      "checkbox.border": "#d0d7de",
      "debugConsole.errorForeground": "#cf222e",
      "debugConsole.infoForeground": "#57606a",
      "debugConsole.sourceForeground": "#9a6700",
      "debugConsole.warningForeground": "#7d4e00",
      "debugConsoleInputIcon.foreground": "#6639ba",
      "debugIcon.breakpointForeground": "#cf222e",
      "debugTokenExpression.boolean": "#116329",
      "debugTokenExpression.error": "#a40e26",
      "debugTokenExpression.name": "#0550ae",
      "debugTokenExpression.number": "#116329",
      "debugTokenExpression.string": "#0a3069",
      "debugTokenExpression.value": "#0a3069",
      "debugToolBar.background": "#ffffff",
      "descriptionForeground": "#656d76",
      "diffEditor.insertedLineBackground": "#aceebb4d",
      "diffEditor.insertedTextBackground": "#6fdd8b80",
      "diffEditor.removedLineBackground": "#ffcecb4d",
      "diffEditor.removedTextBackground": "#ff818266",
      "dropdown.background": "#ffffff",
      "dropdown.border": "#d0d7de",
      "dropdown.foreground": "#1f2328",
      "dropdown.listBackground": "#ffffff",
      "editor.background": "#ffffff",
      "editor.findMatchBackground": "#bf8700",
      "editor.findMatchHighlightBackground": "#fae17d80",
      "editor.focusedStackFrameHighlightBackground": "#4ac26b66",
      "editor.foldBackground": "#6e77811a",
      "editor.foreground": "#1f2328",
      "editor.lineHighlightBackground": "#eaeef280",
      "editor.linkedEditingBackground": "#0969da12",
      "editor.selectionHighlightBackground": "#4ac26b40",
      "editor.stackFrameHighlightBackground": "#d4a72c66",
      "editor.wordHighlightBackground": "#eaeef280",
      "editor.wordHighlightBorder": "#afb8c199",
      "editor.wordHighlightStrongBackground": "#afb8c14d",
      "editor.wordHighlightStrongBorder": "#afb8c199",
      "editorBracketHighlight.foreground1": "#0969da",
      "editorBracketHighlight.foreground2": "#1a7f37",
      "editorBracketHighlight.foreground3": "#9a6700",
      "editorBracketHighlight.foreground4": "#cf222e",
      "editorBracketHighlight.foreground5": "#bf3989",
      "editorBracketHighlight.foreground6": "#8250df",
      "editorBracketHighlight.unexpectedBracket.foreground": "#656d76",
      "editorBracketMatch.background": "#4ac26b40",
      "editorBracketMatch.border": "#4ac26b99",
      "editorCursor.foreground": "#0969da",
      "editorGroup.border": "#d0d7de",
      "editorGroupHeader.tabsBackground": "#f6f8fa",
      "editorGroupHeader.tabsBorder": "#d0d7de",
      "editorGutter.addedBackground": "#4ac26b66",
      "editorGutter.deletedBackground": "#ff818266",
      "editorGutter.modifiedBackground": "#d4a72c66",
      "editorIndentGuide.activeBackground": "#1f23283d",
      "editorIndentGuide.background": "#1f23281f",
      "editorInlayHint.background": "#afb8c133",
      "editorInlayHint.foreground": "#656d76",
      "editorInlayHint.paramBackground": "#afb8c133",
      "editorInlayHint.paramForeground": "#656d76",
      "editorInlayHint.typeBackground": "#afb8c133",
      "editorInlayHint.typeForeground": "#656d76",
      "editorLineNumber.activeForeground": "#1f2328",
      "editorLineNumber.foreground": "#8c959f",
      "editorOverviewRuler.border": "#ffffff",
      "editorWhitespace.foreground": "#afb8c1",
      "editorWidget.background": "#ffffff",
      "errorForeground": "#cf222e",
      "focusBorder": "#0969da",
      "foreground": "#1f2328",
      "gitDecoration.addedResourceForeground": "#1a7f37",
      "gitDecoration.conflictingResourceForeground": "#bc4c00",
      "gitDecoration.deletedResourceForeground": "#cf222e",
      "gitDecoration.ignoredResourceForeground": "#6e7781",
      "gitDecoration.modifiedResourceForeground": "#9a6700",
      "gitDecoration.submoduleResourceForeground": "#656d76",
      "gitDecoration.untrackedResourceForeground": "#1a7f37",
      "icon.foreground": "#656d76",
      "input.background": "#ffffff",
      "input.border": "#d0d7de",
      "input.foreground": "#1f2328",
      "input.placeholderForeground": "#6e7781",
      "keybindingLabel.foreground": "#1f2328",
      "list.activeSelectionBackground": "#afb8c133",
      "list.activeSelectionForeground": "#1f2328",
      "list.focusBackground": "#ddf4ff",
      "list.focusForeground": "#1f2328",
      "list.highlightForeground": "#0969da",
      "list.hoverBackground": "#eaeef280",
      "list.hoverForeground": "#1f2328",
      "list.inactiveFocusBackground": "#ddf4ff",
      "list.inactiveSelectionBackground": "#afb8c133",
      "list.inactiveSelectionForeground": "#1f2328",
      "minimapSlider.activeBackground": "#8c959f47",
      "minimapSlider.background": "#8c959f33",
      "minimapSlider.hoverBackground": "#8c959f3d",
      "notificationCenterHeader.background": "#f6f8fa",
      "notificationCenterHeader.foreground": "#656d76",
      "notifications.background": "#ffffff",
      "notifications.border": "#d0d7de",
      "notifications.foreground": "#1f2328",
      "notificationsErrorIcon.foreground": "#cf222e",
      "notificationsInfoIcon.foreground": "#0969da",
      "notificationsWarningIcon.foreground": "#9a6700",
      "panel.background": "#f6f8fa",
      "panel.border": "#d0d7de",
      "panelInput.border": "#d0d7de",
      "panelTitle.activeBorder": "#fd8c73",
      "panelTitle.activeForeground": "#1f2328",
      "panelTitle.inactiveForeground": "#656d76",
      "pickerGroup.border": "#d0d7de",
      "pickerGroup.foreground": "#656d76",
      "progressBar.background": "#0969da",
      "quickInput.background": "#ffffff",
      "quickInput.foreground": "#1f2328",
      "scrollbar.shadow": "#6e778133",
      "scrollbarSlider.activeBackground": "#8c959f47",
      "scrollbarSlider.background": "#8c959f33",
      "scrollbarSlider.hoverBackground": "#8c959f3d",
      "settings.headerForeground": "#1f2328",
      "settings.modifiedItemIndicator": "#d4a72c66",
      "sideBar.background": "#f6f8fa",
      "sideBar.border": "#d0d7de",
      "sideBar.foreground": "#1f2328",
      "sideBarSectionHeader.background": "#f6f8fa",
      "sideBarSectionHeader.border": "#d0d7de",
      "sideBarSectionHeader.foreground": "#1f2328",
      "sideBarTitle.foreground": "#1f2328",
      "statusBar.background": "#ffffff",
      "statusBar.border": "#d0d7de",
      "statusBar.debuggingBackground": "#cf222e",
      "statusBar.debuggingForeground": "#ffffff",
      "statusBar.focusBorder": "#0969da80",
      "statusBar.foreground": "#656d76",
      "statusBar.noFolderBackground": "#ffffff",
      "statusBarItem.activeBackground": "#1f23281f",
      "statusBarItem.focusBorder": "#0969da",
      "statusBarItem.hoverBackground": "#1f232814",
      "statusBarItem.prominentBackground": "#afb8c133",
      "statusBarItem.remoteBackground": "#eaeef2",
      "statusBarItem.remoteForeground": "#1f2328",
      "symbolIcon.arrayForeground": "#953800",
      "symbolIcon.booleanForeground": "#0550ae",
      "symbolIcon.classForeground": "#953800",
      "symbolIcon.colorForeground": "#0a3069",
      "symbolIcon.constantForeground": "#116329",
      "symbolIcon.constructorForeground": "#3e1f79",
      "symbolIcon.enumeratorForeground": "#953800",
      "symbolIcon.enumeratorMemberForeground": "#0550ae",
      "symbolIcon.eventForeground": "#57606a",
      "symbolIcon.fieldForeground": "#953800",
      "symbolIcon.fileForeground": "#7d4e00",
      "symbolIcon.folderForeground": "#7d4e00",
      "symbolIcon.functionForeground": "#6639ba",
      "symbolIcon.interfaceForeground": "#953800",
      "symbolIcon.keyForeground": "#0550ae",
      "symbolIcon.keywordForeground": "#a40e26",
      "symbolIcon.methodForeground": "#6639ba",
      "symbolIcon.moduleForeground": "#a40e26",
      "symbolIcon.namespaceForeground": "#a40e26",
      "symbolIcon.nullForeground": "#0550ae",
      "symbolIcon.numberForeground": "#116329",
      "symbolIcon.objectForeground": "#953800",
      "symbolIcon.operatorForeground": "#0a3069",
      "symbolIcon.packageForeground": "#953800",
      "symbolIcon.propertyForeground": "#953800",
      "symbolIcon.referenceForeground": "#0550ae",
      "symbolIcon.snippetForeground": "#0550ae",
      "symbolIcon.stringForeground": "#0a3069",
      "symbolIcon.structForeground": "#953800",
      "symbolIcon.textForeground": "#0a3069",
      "symbolIcon.typeParameterForeground": "#0a3069",
      "symbolIcon.unitForeground": "#0550ae",
      "symbolIcon.variableForeground": "#953800",
      "tab.activeBackground": "#ffffff",
      "tab.activeBorder": "#ffffff",
      "tab.activeBorderTop": "#fd8c73",
      "tab.activeForeground": "#1f2328",
      "tab.border": "#d0d7de",
      "tab.hoverBackground": "#ffffff",
      "tab.inactiveBackground": "#f6f8fa",
      "tab.inactiveForeground": "#656d76",
      "tab.unfocusedActiveBorder": "#ffffff",
      "tab.unfocusedActiveBorderTop": "#d0d7de",
      "tab.unfocusedHoverBackground": "#eaeef280",
      "terminal.ansiBlack": "#24292f",
      "terminal.ansiBlue": "#0969da",
      "terminal.ansiBrightBlack": "#57606a",
      "terminal.ansiBrightBlue": "#218bff",
      "terminal.ansiBrightCyan": "#3192aa",
      "terminal.ansiBrightGreen": "#1a7f37",
      "terminal.ansiBrightMagenta": "#a475f9",
      "terminal.ansiBrightRed": "#a40e26",
      "terminal.ansiBrightWhite": "#8c959f",
      "terminal.ansiBrightYellow": "#633c01",
      "terminal.ansiCyan": "#1b7c83",
      "terminal.ansiGreen": "#116329",
      "terminal.ansiMagenta": "#8250df",
      "terminal.ansiRed": "#cf222e",
      "terminal.ansiWhite": "#6e7781",
      "terminal.ansiYellow": "#4d2d00",
      "terminal.foreground": "#1f2328",
      "textBlockQuote.background": "#f6f8fa",
      "textBlockQuote.border": "#d0d7de",
      "textCodeBlock.background": "#afb8c133",
      "textLink.activeForeground": "#0969da",
      "textLink.foreground": "#0969da",
      "textPreformat.background": "#afb8c133",
      "textPreformat.foreground": "#656d76",
      "textSeparator.foreground": "#d8dee4",
      "titleBar.activeBackground": "#ffffff",
      "titleBar.activeForeground": "#656d76",
      "titleBar.border": "#d0d7de",
      "titleBar.inactiveBackground": "#f6f8fa",
      "titleBar.inactiveForeground": "#656d76",
      "tree.indentGuidesStroke": "#d8dee4",
      "welcomePage.buttonBackground": "#f6f8fa",
      "welcomePage.buttonHoverBackground": "#f3f4f6"
    },
    "name": "github-light-default",
    "semanticHighlighting": true,
    "tokenColors": [
      {
        "scope": [
          "comment",
          "punctuation.definition.comment",
          "string.comment"
        ],
        "settings": {
          "foreground": "#6e7781"
        }
      },
      {
        "scope": [
          "constant.other.placeholder",
          "constant.character"
        ],
        "settings": {
          "foreground": "#cf222e"
        }
      },
      {
        "scope": [
          "constant",
          "entity.name.constant",
          "variable.other.constant",
          "variable.other.enummember",
          "variable.language",
          "entity"
        ],
        "settings": {
          "foreground": "#0550ae"
        }
      },
      {
        "scope": [
          "entity.name",
          "meta.export.default",
          "meta.definition.variable"
        ],
        "settings": {
          "foreground": "#953800"
        }
      },
      {
        "scope": [
          "variable.parameter.function",
          "meta.jsx.children",
          "meta.block",
          "meta.tag.attributes",
          "entity.name.constant",
          "meta.object.member",
          "meta.embedded.expression"
        ],
        "settings": {
          "foreground": "#1f2328"
        }
      },
      {
        "scope": "entity.name.function",
        "settings": {
          "foreground": "#8250df"
        }
      },
      {
        "scope": [
          "entity.name.tag",
          "support.class.component"
        ],
        "settings": {
          "foreground": "#116329"
        }
      },
      {
        "scope": "keyword",
        "settings": {
          "foreground": "#cf222e"
        }
      },
      {
        "scope": [
          "storage",
          "storage.type"
        ],
        "settings": {
          "foreground": "#cf222e"
        }
      },
      {
        "scope": [
          "storage.modifier.package",
          "storage.modifier.import",
          "storage.type.java"
        ],
        "settings": {
          "foreground": "#1f2328"
        }
      },
      {
        "scope": [
          "string",
          "string punctuation.section.embedded source"
        ],
        "settings": {
          "foreground": "#0a3069"
        }
      },
      {
        "scope": "support",
        "settings": {
          "foreground": "#0550ae"
        }
      },
      {
        "scope": "meta.property-name",
        "settings": {
          "foreground": "#0550ae"
        }
      },
      {
        "scope": "variable",
        "settings": {
          "foreground": "#953800"
        }
      },
      {
        "scope": "variable.other",
        "settings": {
          "foreground": "#1f2328"
        }
      },
      {
        "scope": "invalid.broken",
        "settings": {
          "fontStyle": "italic",
          "foreground": "#82071e"
        }
      },
      {
        "scope": "invalid.deprecated",
        "settings": {
          "fontStyle": "italic",
          "foreground": "#82071e"
        }
      },
      {
        "scope": "invalid.illegal",
        "settings": {
          "fontStyle": "italic",
          "foreground": "#82071e"
        }
      },
      {
        "scope": "invalid.unimplemented",
        "settings": {
          "fontStyle": "italic",
          "foreground": "#82071e"
        }
      },
      {
        "scope": "carriage-return",
        "settings": {
          "background": "#cf222e",
          "content": "^M",
          "fontStyle": "italic underline",
          "foreground": "#f6f8fa"
        }
      },
      {
        "scope": "message.error",
        "settings": {
          "foreground": "#82071e"
        }
      },
      {
        "scope": "string variable",
        "settings": {
          "foreground": "#0550ae"
        }
      },
      {
        "scope": [
          "source.regexp",
          "string.regexp"
        ],
        "settings": {
          "foreground": "#0a3069"
        }
      },
      {
        "scope": [
          "string.regexp.character-class",
          "string.regexp constant.character.escape",
          "string.regexp source.ruby.embedded",
          "string.regexp string.regexp.arbitrary-repitition"
        ],
        "settings": {
          "foreground": "#0a3069"
        }
      },
      {
        "scope": "string.regexp constant.character.escape",
        "settings": {
          "fontStyle": "bold",
          "foreground": "#116329"
        }
      },
      {
        "scope": "support.constant",
        "settings": {
          "foreground": "#0550ae"
        }
      },
      {
        "scope": "support.variable",
        "settings": {
          "foreground": "#0550ae"
        }
      },
      {
        "scope": "support.type.property-name.json",
        "settings": {
          "foreground": "#116329"
        }
      },
      {
        "scope": "meta.module-reference",
        "settings": {
          "foreground": "#0550ae"
        }
      },
      {
        "scope": "punctuation.definition.list.begin.markdown",
        "settings": {
          "foreground": "#953800"
        }
      },
      {
        "scope": [
          "markup.heading",
          "markup.heading entity.name"
        ],
        "settings": {
          "fontStyle": "bold",
          "foreground": "#0550ae"
        }
      },
      {
        "scope": "markup.quote",
        "settings": {
          "foreground": "#116329"
        }
      },
      {
        "scope": "markup.italic",
        "settings": {
          "fontStyle": "italic",
          "foreground": "#1f2328"
        }
      },
      {
        "scope": "markup.bold",
        "settings": {
          "fontStyle": "bold",
          "foreground": "#1f2328"
        }
      },
      {
        "scope": [
          "markup.underline"
        ],
        "settings": {
          "fontStyle": "underline"
        }
      },
      {
        "scope": [
          "markup.strikethrough"
        ],
        "settings": {
          "fontStyle": "strikethrough"
        }
      },
      {
        "scope": "markup.inline.raw",
        "settings": {
          "foreground": "#0550ae"
        }
      },
      {
        "scope": [
          "markup.deleted",
          "meta.diff.header.from-file",
          "punctuation.definition.deleted"
        ],
        "settings": {
          "background": "#ffebe9",
          "foreground": "#82071e"
        }
      },
      {
        "scope": [
          "punctuation.section.embedded"
        ],
        "settings": {
          "foreground": "#cf222e"
        }
      },
      {
        "scope": [
          "markup.inserted",
          "meta.diff.header.to-file",
          "punctuation.definition.inserted"
        ],
        "settings": {
          "background": "#dafbe1",
          "foreground": "#116329"
        }
      },
      {
        "scope": [
          "markup.changed",
          "punctuation.definition.changed"
        ],
        "settings": {
          "background": "#ffd8b5",
          "foreground": "#953800"
        }
      },
      {
        "scope": [
          "markup.ignored",
          "markup.untracked"
        ],
        "settings": {
          "background": "#0550ae",
          "foreground": "#eaeef2"
        }
      },
      {
        "scope": "meta.diff.range",
        "settings": {
          "fontStyle": "bold",
          "foreground": "#8250df"
        }
      },
      {
        "scope": "meta.diff.header",
        "settings": {
          "foreground": "#0550ae"
        }
      },
      {
        "scope": "meta.separator",
        "settings": {
          "fontStyle": "bold",
          "foreground": "#0550ae"
        }
      },
      {
        "scope": "meta.output",
        "settings": {
          "foreground": "#0550ae"
        }
      },
      {
        "scope": [
          "brackethighlighter.tag",
          "brackethighlighter.curly",
          "brackethighlighter.round",
          "brackethighlighter.square",
          "brackethighlighter.angle",
          "brackethighlighter.quote"
        ],
        "settings": {
          "foreground": "#57606a"
        }
      },
      {
        "scope": "brackethighlighter.unmatched",
        "settings": {
          "foreground": "#82071e"
        }
      },
      {
        "scope": [
          "constant.other.reference.link",
          "string.other.link"
        ],
        "settings": {
          "foreground": "#0a3069"
        }
      }
    ],
    "type": "light"
  },
  "gruvbox-light-medium": {
    "colors": {
      "activityBar.background": "#fbf1c7",
      "activityBar.border": "#ebdbb2",
      "activityBar.foreground": "#3c3836",
      "activityBarBadge.background": "#458588",
      "activityBarBadge.foreground": "#ebdbb2",
      "activityBarTop.background": "#fbf1c7",
      "activityBarTop.foreground": "#3c3836",
      "badge.background": "#b16286",
      "badge.foreground": "#ebdbb2",
      "button.background": "#45858880",
      "button.foreground": "#3c3836",
      "button.hoverBackground": "#45858860",
      "debugToolBar.background": "#fbf1c7",
      "diffEditor.insertedTextBackground": "#79740e30",
      "diffEditor.removedTextBackground": "#9d000630",
      "dropdown.background": "#fbf1c7",
      "dropdown.border": "#ebdbb2",
      "dropdown.foreground": "#3c3836",
      "editor.background": "#fbf1c7",
      "editor.findMatchBackground": "#07667870",
      "editor.findMatchHighlightBackground": "#af3a0330",
      "editor.findRangeHighlightBackground": "#07667870",
      "editor.foreground": "#3c3836",
      "editor.hoverHighlightBackground": "#689d6a50",
      "editor.lineHighlightBackground": "#ebdbb260",
      "editor.lineHighlightBorder": "#0000",
      "editor.selectionBackground": "#689d6a40",
      "editor.selectionHighlightBackground": "#b5761440",
      "editorBracketHighlight.foreground1": "#b16286",
      "editorBracketHighlight.foreground2": "#458588",
      "editorBracketHighlight.foreground3": "#689d6a",
      "editorBracketHighlight.foreground4": "#98971a",
      "editorBracketHighlight.foreground5": "#d79921",
      "editorBracketHighlight.foreground6": "#d65d0e",
      "editorBracketHighlight.unexpectedBracket.foreground": "#cc241d",
      "editorBracketMatch.background": "#92837480",
      "editorBracketMatch.border": "#0000",
      "editorCodeLens.foreground": "#7c6f6490",
      "editorCursor.foreground": "#3c3836",
      "editorError.foreground": "#cc241d",
      "editorGhostText.background": "#bdae9360",
      "editorGroup.border": "#ebdbb2",
      "editorGroup.dropBackground": "#ebdbb260",
      "editorGroupHeader.noTabsBackground": "#fbf1c7",
      "editorGroupHeader.tabsBackground": "#fbf1c7",
      "editorGroupHeader.tabsBorder": "#ebdbb2",
      "editorGutter.addedBackground": "#79740e",
      "editorGutter.background": "#0000",
      "editorGutter.deletedBackground": "#9d0006",
      "editorGutter.modifiedBackground": "#076678",
      "editorHoverWidget.background": "#fbf1c7",
      "editorHoverWidget.border": "#ebdbb2",
      "editorIndentGuide.activeBackground": "#bdae93",
      "editorInfo.foreground": "#458588",
      "editorLineNumber.foreground": "#bdae93",
      "editorLink.activeForeground": "#3c3836",
      "editorOverviewRuler.addedForeground": "#076678",
      "editorOverviewRuler.border": "#0000",
      "editorOverviewRuler.commonContentForeground": "#928374",
      "editorOverviewRuler.currentContentForeground": "#458588",
      "editorOverviewRuler.deletedForeground": "#076678",
      "editorOverviewRuler.errorForeground": "#9d0006",
      "editorOverviewRuler.findMatchForeground": "#665c54",
      "editorOverviewRuler.incomingContentForeground": "#689d6a",
      "editorOverviewRuler.infoForeground": "#8f3f71",
      "editorOverviewRuler.modifiedForeground": "#076678",
      "editorOverviewRuler.rangeHighlightForeground": "#665c54",
      "editorOverviewRuler.selectionHighlightForeground": "#bdae93",
      "editorOverviewRuler.warningForeground": "#d79921",
      "editorOverviewRuler.wordHighlightForeground": "#bdae93",
      "editorOverviewRuler.wordHighlightStrongForeground": "#bdae93",
      "editorRuler.foreground": "#7c6f6440",
      "editorStickyScroll.shadow": "#d5c4a199",
      "editorStickyScrollHover.background": "#ebdbb260",
      "editorSuggestWidget.background": "#fbf1c7",
      "editorSuggestWidget.border": "#ebdbb2",
      "editorSuggestWidget.foreground": "#3c3836",
      "editorSuggestWidget.highlightForeground": "#689d6a",
      "editorSuggestWidget.selectedBackground": "#ebdbb260",
      "editorWarning.foreground": "#d79921",
      "editorWhitespace.foreground": "#7c6f6420",
      "editorWidget.background": "#fbf1c7",
      "editorWidget.border": "#ebdbb2",
      "errorForeground": "#9d0006",
      "extensionButton.prominentBackground": "#79740e80",
      "extensionButton.prominentHoverBackground": "#79740e30",
      "focusBorder": "#ebdbb2",
      "foreground": "#3c3836",
      "gitDecoration.addedResourceForeground": "#3c3836",
      "gitDecoration.conflictingResourceForeground": "#b16286",
      "gitDecoration.deletedResourceForeground": "#cc241d",
      "gitDecoration.ignoredResourceForeground": "#a89984",
      "gitDecoration.modifiedResourceForeground": "#d79921",
      "gitDecoration.untrackedResourceForeground": "#98971a",
      "gitlens.closedAutolinkedIssueIconColor": "#b16286",
      "gitlens.closedPullRequestIconColor": "#cc241d",
      "gitlens.decorations.branchAheadForegroundColor": "#98971a",
      "gitlens.decorations.branchBehindForegroundColor": "#d65d0e",
      "gitlens.decorations.branchDivergedForegroundColor": "#d79921",
      "gitlens.decorations.branchMissingUpstreamForegroundColor": "#cc241d",
      "gitlens.decorations.statusMergingOrRebasingConflictForegroundColor": "#cc241d",
      "gitlens.decorations.statusMergingOrRebasingForegroundColor": "#d79921",
      "gitlens.decorations.workspaceCurrentForegroundColor": "#98971a",
      "gitlens.decorations.workspaceRepoMissingForegroundColor": "#a89984",
      "gitlens.decorations.workspaceRepoOpenForegroundColor": "#98971a",
      "gitlens.decorations.worktreeHasUncommittedChangesForegroundColor": "#928374",
      "gitlens.decorations.worktreeMissingForegroundColor": "#cc241d",
      "gitlens.graphChangesColumnAddedColor": "#98971a",
      "gitlens.graphChangesColumnDeletedColor": "#cc241d",
      "gitlens.graphLane10Color": "#98971a",
      "gitlens.graphLane1Color": "#076678",
      "gitlens.graphLane2Color": "#458588",
      "gitlens.graphLane3Color": "#8f3f71",
      "gitlens.graphLane4Color": "#b16286",
      "gitlens.graphLane5Color": "#427b58",
      "gitlens.graphLane6Color": "#689d6a",
      "gitlens.graphLane7Color": "#b57614",
      "gitlens.graphLane8Color": "#d79921",
      "gitlens.graphLane9Color": "#79740e",
      "gitlens.graphMinimapMarkerHeadColor": "#98971a",
      "gitlens.graphMinimapMarkerHighlightsColor": "#79740e",
      "gitlens.graphMinimapMarkerLocalBranchesColor": "#076678",
      "gitlens.graphMinimapMarkerPullRequestsColor": "#af3a03",
      "gitlens.graphMinimapMarkerRemoteBranchesColor": "#458588",
      "gitlens.graphMinimapMarkerStashesColor": "#b16286",
      "gitlens.graphMinimapMarkerTagsColor": "#a89984",
      "gitlens.graphMinimapMarkerUpstreamColor": "#689d6a",
      "gitlens.graphScrollMarkerHeadColor": "#79740e",
      "gitlens.graphScrollMarkerHighlightsColor": "#d79921",
      "gitlens.graphScrollMarkerLocalBranchesColor": "#076678",
      "gitlens.graphScrollMarkerPullRequestsColor": "#af3a03",
      "gitlens.graphScrollMarkerRemoteBranchesColor": "#458588",
      "gitlens.graphScrollMarkerStashesColor": "#b16286",
      "gitlens.graphScrollMarkerTagsColor": "#a89984",
      "gitlens.graphScrollMarkerUpstreamColor": "#427b58",
      "gitlens.gutterBackgroundColor": "#ebdbb2",
      "gitlens.gutterForegroundColor": "#3c3836",
      "gitlens.gutterUncommittedForegroundColor": "#458588",
      "gitlens.launchpadIndicatorAttentionColor": "#b57614",
      "gitlens.launchpadIndicatorAttentionHoverColor": "#d79921",
      "gitlens.launchpadIndicatorBlockedColor": "#9d0006",
      "gitlens.launchpadIndicatorBlockedHoverColor": "#cc241d",
      "gitlens.launchpadIndicatorMergeableColor": "#79740e",
      "gitlens.launchpadIndicatorMergeableHoverColor": "#98971a",
      "gitlens.lineHighlightBackgroundColor": "#ebdbb2",
      "gitlens.lineHighlightOverviewRulerColor": "#458588",
      "gitlens.mergedPullRequestIconColor": "#b16286",
      "gitlens.openAutolinkedIssueIconColor": "#98971a",
      "gitlens.openPullRequestIconColor": "#98971a",
      "gitlens.trailingLineBackgroundColor": "#fbf1c7a0",
      "gitlens.trailingLineForegroundColor": "#928374a0",
      "gitlens.unpublishedChangesIconColor": "#98971a",
      "gitlens.unpublishedCommitIconColor": "#98971a",
      "gitlens.unpulledChangesIconColor": "#af3a03",
      "icon.foreground": "#3c3836",
      "input.background": "#fbf1c7",
      "input.border": "#ebdbb2",
      "input.foreground": "#3c3836",
      "input.placeholderForeground": "#3c383660",
      "inputOption.activeBorder": "#3c383660",
      "inputValidation.errorBackground": "#cc241d",
      "inputValidation.errorBorder": "#9d0006",
      "inputValidation.infoBackground": "#45858880",
      "inputValidation.infoBorder": "#076678",
      "inputValidation.warningBackground": "#d79921",
      "inputValidation.warningBorder": "#b57614",
      "list.activeSelectionBackground": "#ebdbb280",
      "list.activeSelectionForeground": "#427b58",
      "list.dropBackground": "#ebdbb2",
      "list.focusBackground": "#ebdbb2",
      "list.focusForeground": "#3c3836",
      "list.highlightForeground": "#689d6a",
      "list.hoverBackground": "#ebdbb280",
      "list.hoverForeground": "#504945",
      "list.inactiveSelectionBackground": "#ebdbb280",
      "list.inactiveSelectionForeground": "#689d6a",
      "menu.border": "#ebdbb2",
      "menu.separatorBackground": "#ebdbb2",
      "merge.border": "#0000",
      "merge.currentContentBackground": "#45858820",
      "merge.currentHeaderBackground": "#45858840",
      "merge.incomingContentBackground": "#689d6a20",
      "merge.incomingHeaderBackground": "#689d6a40",
      "notebook.cellBorderColor": "#d5c4a1",
      "notebook.cellEditorBackground": "#ebdbb2",
      "notebook.focusedCellBorder": "#7c6f64",
      "notebook.focusedEditorBorder": "#d5c4a1",
      "panel.border": "#ebdbb2",
      "panelTitle.activeForeground": "#3c3836",
      "peekView.border": "#ebdbb2",
      "peekViewEditor.background": "#ebdbb270",
      "peekViewEditor.matchHighlightBackground": "#d5c4a1",
      "peekViewEditorGutter.background": "#ebdbb270",
      "peekViewResult.background": "#ebdbb270",
      "peekViewResult.fileForeground": "#3c3836",
      "peekViewResult.lineForeground": "#3c3836",
      "peekViewResult.matchHighlightBackground": "#d5c4a1",
      "peekViewResult.selectionBackground": "#45858820",
      "peekViewResult.selectionForeground": "#3c3836",
      "peekViewTitle.background": "#ebdbb270",
      "peekViewTitleDescription.foreground": "#665c54",
      "peekViewTitleLabel.foreground": "#3c3836",
      "progressBar.background": "#689d6a",
      "scmGraph.historyItemHoverDefaultLabelForeground": "#ebdbb2",
      "scmGraph.historyItemHoverLabelForeground": "#ebdbb2",
      "scrollbar.shadow": "#fbf1c7",
      "scrollbarSlider.activeBackground": "#689d6a",
      "scrollbarSlider.background": "#d5c4a199",
      "scrollbarSlider.hoverBackground": "#bdae93",
      "selection.background": "#689d6a80",
      "sideBar.background": "#fbf1c7",
      "sideBar.border": "#ebdbb2",
      "sideBar.foreground": "#504945",
      "sideBarSectionHeader.background": "#0000",
      "sideBarSectionHeader.foreground": "#3c3836",
      "sideBarTitle.foreground": "#3c3836",
      "statusBar.background": "#fbf1c7",
      "statusBar.border": "#ebdbb2",
      "statusBar.debuggingBackground": "#af3a03",
      "statusBar.debuggingBorder": "#0000",
      "statusBar.debuggingForeground": "#fbf1c7",
      "statusBar.foreground": "#3c3836",
      "statusBar.noFolderBackground": "#fbf1c7",
      "statusBar.noFolderBorder": "#0000",
      "tab.activeBackground": "#ebdbb2",
      "tab.activeBorder": "#689d6a",
      "tab.activeForeground": "#3c3836",
      "tab.border": "#0000",
      "tab.inactiveBackground": "#fbf1c7",
      "tab.inactiveForeground": "#7c6f64",
      "tab.unfocusedActiveBorder": "#0000",
      "tab.unfocusedActiveForeground": "#7c6f64",
      "tab.unfocusedInactiveForeground": "#928374",
      "terminal.ansiBlack": "#ebdbb2",
      "terminal.ansiBlue": "#458588",
      "terminal.ansiBrightBlack": "#928374",
      "terminal.ansiBrightBlue": "#076678",
      "terminal.ansiBrightCyan": "#427b58",
      "terminal.ansiBrightGreen": "#79740e",
      "terminal.ansiBrightMagenta": "#8f3f71",
      "terminal.ansiBrightRed": "#9d0006",
      "terminal.ansiBrightWhite": "#3c3836",
      "terminal.ansiBrightYellow": "#b57614",
      "terminal.ansiCyan": "#689d6a",
      "terminal.ansiGreen": "#98971a",
      "terminal.ansiMagenta": "#b16286",
      "terminal.ansiRed": "#cc241d",
      "terminal.ansiWhite": "#7c6f64",
      "terminal.ansiYellow": "#d79921",
      "terminal.background": "#fbf1c7",
      "terminal.foreground": "#3c3836",
      "textLink.activeForeground": "#458588",
      "textLink.foreground": "#076678",
      "titleBar.activeBackground": "#fbf1c7",
      "titleBar.activeForeground": "#3c3836",
      "titleBar.inactiveBackground": "#fbf1c7",
      "widget.border": "#ebdbb2",
      "widget.shadow": "#fbf1c730"
    },
    "name": "gruvbox-light-medium",
    "semanticHighlighting": true,
    "semanticTokenColors": {
      "component": "#af3a03",
      "constant.builtin": "#8f3f71",
      "function": "#427b58",
      "function.builtin": "#af3a03",
      "method": "#427b58",
      "parameter": "#076678",
      "property": "#076678",
      "property:python": "#3c3836",
      "variable": "#3c3836"
    },
    "tokenColors": [
      {
        "settings": {
          "foreground": "#3c3836"
        }
      },
      {
        "scope": "emphasis",
        "settings": {
          "fontStyle": "italic"
        }
      },
      {
        "scope": "strong",
        "settings": {
          "fontStyle": "bold"
        }
      },
      {
        "scope": "header",
        "settings": {
          "foreground": "#458588"
        }
      },
      {
        "scope": [
          "comment",
          "punctuation.definition.comment"
        ],
        "settings": {
          "fontStyle": "italic",
          "foreground": "#928374"
        }
      },
      {
        "scope": [
          "constant",
          "support.constant",
          "variable.arguments"
        ],
        "settings": {
          "foreground": "#8f3f71"
        }
      },
      {
        "scope": "constant.rgb-value",
        "settings": {
          "foreground": "#3c3836"
        }
      },
      {
        "scope": "entity.name.selector",
        "settings": {
          "foreground": "#427b58"
        }
      },
      {
        "scope": "entity.other.attribute-name",
        "settings": {
          "foreground": "#b57614"
        }
      },
      {
        "scope": [
          "entity.name.tag",
          "punctuation.tag"
        ],
        "settings": {
          "foreground": "#427b58"
        }
      },
      {
        "scope": [
          "invalid",
          "invalid.illegal"
        ],
        "settings": {
          "foreground": "#cc241d"
        }
      },
      {
        "scope": "invalid.deprecated",
        "settings": {
          "foreground": "#b16286"
        }
      },
      {
        "scope": "meta.selector",
        "settings": {
          "foreground": "#427b58"
        }
      },
      {
        "scope": "meta.preprocessor",
        "settings": {
          "foreground": "#af3a03"
        }
      },
      {
        "scope": "meta.preprocessor.string",
        "settings": {
          "foreground": "#79740e"
        }
      },
      {
        "scope": "meta.preprocessor.numeric",
        "settings": {
          "foreground": "#79740e"
        }
      },
      {
        "scope": "meta.header.diff",
        "settings": {
          "foreground": "#af3a03"
        }
      },
      {
        "scope": "storage",
        "settings": {
          "foreground": "#9d0006"
        }
      },
      {
        "scope": [
          "storage.type",
          "storage.modifier"
        ],
        "settings": {
          "foreground": "#af3a03"
        }
      },
      {
        "scope": "string",
        "settings": {
          "foreground": "#79740e"
        }
      },
      {
        "scope": "string.tag",
        "settings": {
          "foreground": "#79740e"
        }
      },
      {
        "scope": "string.value",
        "settings": {
          "foreground": "#79740e"
        }
      },
      {
        "scope": "string.regexp",
        "settings": {
          "foreground": "#af3a03"
        }
      },
      {
        "scope": "string.escape",
        "settings": {
          "foreground": "#9d0006"
        }
      },
      {
        "scope": "string.quasi",
        "settings": {
          "foreground": "#427b58"
        }
      },
      {
        "scope": "string.entity",
        "settings": {
          "foreground": "#79740e"
        }
      },
      {
        "scope": "object",
        "settings": {
          "foreground": "#3c3836"
        }
      },
      {
        "scope": "module.node",
        "settings": {
          "foreground": "#076678"
        }
      },
      {
        "scope": "support.type.property-name",
        "settings": {
          "foreground": "#689d6a"
        }
      },
      {
        "scope": "keyword",
        "settings": {
          "foreground": "#9d0006"
        }
      },
      {
        "scope": "keyword.control",
        "settings": {
          "foreground": "#9d0006"
        }
      },
      {
        "scope": "keyword.control.module",
        "settings": {
          "foreground": "#427b58"
        }
      },
      {
        "scope": "keyword.control.less",
        "settings": {
          "foreground": "#d79921"
        }
      },
      {
        "scope": "keyword.operator",
        "settings": {
          "foreground": "#427b58"
        }
      },
      {
        "scope": "keyword.operator.new",
        "settings": {
          "foreground": "#af3a03"
        }
      },
      {
        "scope": "keyword.other.unit",
        "settings": {
          "foreground": "#79740e"
        }
      },
      {
        "scope": "metatag.php",
        "settings": {
          "foreground": "#af3a03"
        }
      },
      {
        "scope": "support.function.git-rebase",
        "settings": {
          "foreground": "#689d6a"
        }
      },
      {
        "scope": "constant.sha.git-rebase",
        "settings": {
          "foreground": "#79740e"
        }
      },
      {
        "scope": [
          "meta.type.name",
          "meta.return.type",
          "meta.return-type",
          "meta.cast",
          "meta.type.annotation",
          "support.type",
          "storage.type.cs",
          "variable.class"
        ],
        "settings": {
          "foreground": "#b57614"
        }
      },
      {
        "scope": [
          "variable.this",
          "support.variable"
        ],
        "settings": {
          "foreground": "#8f3f71"
        }
      },
      {
        "scope": [
          "entity.name",
          "entity.static",
          "entity.name.class.static.function",
          "entity.name.function",
          "entity.name.class",
          "entity.name.type"
        ],
        "settings": {
          "foreground": "#b57614"
        }
      },
      {
        "scope": [
          "entity.function",
          "entity.name.function.static"
        ],
        "settings": {
          "foreground": "#427b58"
        }
      },
      {
        "scope": "entity.name.function.function-call",
        "settings": {
          "foreground": "#427b58"
        }
      },
      {
        "scope": "support.function.builtin",
        "settings": {
          "foreground": "#af3a03"
        }
      },
      {
        "scope": [
          "entity.name.method",
          "entity.name.method.function-call",
          "entity.name.static.function-call"
        ],
        "settings": {
          "foreground": "#689d6a"
        }
      },
      {
        "scope": "brace",
        "settings": {
          "foreground": "#504945"
        }
      },
      {
        "scope": [
          "meta.parameter.type.variable",
          "variable.parameter",
          "variable.name",
          "variable.other",
          "variable",
          "string.constant.other.placeholder"
        ],
        "settings": {
          "foreground": "#076678"
        }
      },
      {
        "scope": "prototype",
        "settings": {
          "foreground": "#8f3f71"
        }
      },
      {
        "scope": [
          "punctuation"
        ],
        "settings": {
          "foreground": "#7c6f64"
        }
      },
      {
        "scope": "punctuation.quoted",
        "settings": {
          "foreground": "#3c3836"
        }
      },
      {
        "scope": "punctuation.quasi",
        "settings": {
          "foreground": "#9d0006"
        }
      },
      {
        "scope": [
          "*url*",
          "*link*",
          "*uri*"
        ],
        "settings": {
          "fontStyle": "underline"
        }
      },
      {
        "scope": [
          "meta.function.python",
          "entity.name.function.python"
        ],
        "settings": {
          "foreground": "#427b58"
        }
      },
      {
        "scope": [
          "storage.type.function.python",
          "storage.modifier.declaration",
          "storage.type.class.python",
          "storage.type.string.python"
        ],
        "settings": {
          "foreground": "#9d0006"
        }
      },
      {
        "scope": [
          "storage.type.function.async.python"
        ],
        "settings": {
          "foreground": "#9d0006"
        }
      },
      {
        "scope": "meta.function-call.generic",
        "settings": {
          "foreground": "#076678"
        }
      },
      {
        "scope": "meta.function-call.arguments",
        "settings": {
          "foreground": "#504945"
        }
      },
      {
        "scope": "entity.name.function.decorator",
        "settings": {
          "fontStyle": "bold",
          "foreground": "#b57614"
        }
      },
      {
        "scope": "constant.other.caps",
        "settings": {
          "fontStyle": "bold"
        }
      },
      {
        "scope": "keyword.operator.logical",
        "settings": {
          "foreground": "#9d0006"
        }
      },
      {
        "scope": "punctuation.definition.logical-expression",
        "settings": {
          "foreground": "#af3a03"
        }
      },
      {
        "scope": [
          "string.interpolated.dollar.shell",
          "string.interpolated.backtick.shell"
        ],
        "settings": {
          "foreground": "#427b58"
        }
      },
      {
        "scope": "keyword.control.directive",
        "settings": {
          "foreground": "#427b58"
        }
      },
      {
        "scope": "support.function.C99",
        "settings": {
          "foreground": "#b57614"
        }
      },
      {
        "scope": [
          "meta.function.cs",
          "entity.name.function.cs",
          "entity.name.type.namespace.cs"
        ],
        "settings": {
          "foreground": "#79740e"
        }
      },
      {
        "scope": [
          "keyword.other.using.cs",
          "entity.name.variable.field.cs",
          "entity.name.variable.local.cs",
          "variable.other.readwrite.cs"
        ],
        "settings": {
          "foreground": "#427b58"
        }
      },
      {
        "scope": [
          "keyword.other.this.cs",
          "keyword.other.base.cs"
        ],
        "settings": {
          "foreground": "#8f3f71"
        }
      },
      {
        "scope": "meta.scope.prerequisites",
        "settings": {
          "foreground": "#b57614"
        }
      },
      {
        "scope": "entity.name.function.target",
        "settings": {
          "fontStyle": "bold",
          "foreground": "#79740e"
        }
      },
      {
        "scope": [
          "storage.modifier.import.java",
          "storage.modifier.package.java"
        ],
        "settings": {
          "foreground": "#665c54"
        }
      },
      {
        "scope": [
          "keyword.other.import.java",
          "keyword.other.package.java"
        ],
        "settings": {
          "foreground": "#427b58"
        }
      },
      {
        "scope": "storage.type.java",
        "settings": {
          "foreground": "#b57614"
        }
      },
      {
        "scope": "storage.type.annotation",
        "settings": {
          "fontStyle": "bold",
          "foreground": "#076678"
        }
      },
      {
        "scope": "keyword.other.documentation.javadoc",
        "settings": {
          "foreground": "#427b58"
        }
      },
      {
        "scope": "comment.block.javadoc variable.parameter.java",
        "settings": {
          "fontStyle": "bold",
          "foreground": "#79740e"
        }
      },
      {
        "scope": [
          "source.java variable.other.object",
          "source.java variable.other.definition.java"
        ],
        "settings": {
          "foreground": "#3c3836"
        }
      },
      {
        "scope": "meta.function-parameters.lisp",
        "settings": {
          "foreground": "#b57614"
        }
      },
      {
        "scope": "markup.underline",
        "settings": {
          "fontStyle": "underline"
        }
      },
      {
        "scope": "string.other.link.title.markdown",
        "settings": {
          "fontStyle": "underline",
          "foreground": "#928374"
        }
      },
      {
        "scope": "markup.underline.link",
        "settings": {
          "foreground": "#8f3f71"
        }
      },
      {
        "scope": "markup.bold",
        "settings": {
          "fontStyle": "bold",
          "foreground": "#af3a03"
        }
      },
      {
        "scope": "markup.heading",
        "settings": {
          "fontStyle": "bold",
          "foreground": "#af3a03"
        }
      },
      {
        "scope": "heading.1.markdown entity.name.section.markdown",
        "settings": {
          "fontStyle": "bold",
          "foreground": "#9d0006"
        }
      },
      {
        "scope": "heading.2.markdown entity.name.section.markdown",
        "settings": {
          "fontStyle": "bold",
          "foreground": "#af3a03"
        }
      },
      {
        "scope": "heading.3.markdown entity.name.section.markdown",
        "settings": {
          "fontStyle": "bold",
          "foreground": "#b57614"
        }
      },
      {
        "scope": "heading.4.markdown entity.name.section.markdown",
        "settings": {
          "fontStyle": "bold",
          "foreground": "#79740e"
        }
      },
      {
        "scope": "heading.5.markdown entity.name.section.markdown",
        "settings": {
          "fontStyle": "bold",
          "foreground": "#076678"
        }
      },
      {
        "scope": "heading.6.markdown entity.name.section.markdown",
        "settings": {
          "fontStyle": "bold",
          "foreground": "#8f3f71"
        }
      },
      {
        "scope": "markup.italic",
        "settings": {
          "fontStyle": "italic"
        }
      },
      {
        "scope": "markup.inserted",
        "settings": {
          "foreground": "#79740e"
        }
      },
      {
        "scope": "markup.deleted",
        "settings": {
          "foreground": "#d65d0e"
        }
      },
      {
        "scope": "markup.changed",
        "settings": {
          "foreground": "#af3a03"
        }
      },
      {
        "scope": "markup.punctuation.quote.beginning",
        "settings": {
          "foreground": "#98971a"
        }
      },
      {
        "scope": "markup.punctuation.list.beginning",
        "settings": {
          "foreground": "#076678"
        }
      },
      {
        "scope": [
          "markup.inline.raw",
          "markup.fenced_code.block"
        ],
        "settings": {
          "foreground": "#427b58"
        }
      },
      {
        "scope": "string.quoted.double.json",
        "settings": {
          "foreground": "#076678"
        }
      },
      {
        "scope": "entity.other.attribute-name.css",
        "settings": {
          "foreground": "#af3a03"
        }
      },
      {
        "scope": "source.css meta.selector",
        "settings": {
          "foreground": "#3c3836"
        }
      },
      {
        "scope": "support.type.property-name.css",
        "settings": {
          "foreground": "#af3a03"
        }
      },
      {
        "scope": "entity.other.attribute-name.class",
        "settings": {
          "foreground": "#79740e"
        }
      },
      {
        "scope": [
          "source.css support.function.transform",
          "source.css support.function.timing-function",
          "source.css support.function.misc"
        ],
        "settings": {
          "foreground": "#9d0006"
        }
      },
      {
        "scope": [
          "support.property-value",
          "constant.rgb-value",
          "support.property-value.scss",
          "constant.rgb-value.scss"
        ],
        "settings": {
          "foreground": "#d65d0e"
        }
      },
      {
        "scope": [
          "entity.name.tag.css"
        ],
        "settings": {
          "fontStyle": ""
        }
      },
      {
        "scope": [
          "punctuation.definition.tag"
        ],
        "settings": {
          "foreground": "#076678"
        }
      },
      {
        "scope": [
          "text.html entity.name.tag",
          "text.html punctuation.tag"
        ],
        "settings": {
          "fontStyle": "bold",
          "foreground": "#427b58"
        }
      },
      {
        "scope": [
          "source.js variable.language"
        ],
        "settings": {
          "foreground": "#af3a03"
        }
      },
      {
        "scope": [
          "source.ts variable.language"
        ],
        "settings": {
          "foreground": "#af3a03"
        }
      },
      {
        "scope": [
          "source.go storage.type"
        ],
        "settings": {
          "foreground": "#b57614"
        }
      },
      {
        "scope": [
          "source.go entity.name.import"
        ],
        "settings": {
          "foreground": "#79740e"
        }
      },
      {
        "scope": [
          "source.go keyword.package",
          "source.go keyword.import"
        ],
        "settings": {
          "foreground": "#427b58"
        }
      },
      {
        "scope": [
          "source.go keyword.interface",
          "source.go keyword.struct"
        ],
        "settings": {
          "foreground": "#076678"
        }
      },
      {
        "scope": [
          "source.go entity.name.type"
        ],
        "settings": {
          "foreground": "#3c3836"
        }
      },
      {
        "scope": [
          "source.go entity.name.function"
        ],
        "settings": {
          "foreground": "#8f3f71"
        }
      },
      {
        "scope": [
          "keyword.control.cucumber.table"
        ],
        "settings": {
          "foreground": "#076678"
        }
      },
      {
        "scope": [
          "source.reason string.double",
          "source.reason string.regexp"
        ],
        "settings": {
          "foreground": "#79740e"
        }
      },
      {
        "scope": [
          "source.reason keyword.control.less"
        ],
        "settings": {
          "foreground": "#427b58"
        }
      },
      {
        "scope": [
          "source.reason entity.name.function"
        ],
        "settings": {
          "foreground": "#076678"
        }
      },
      {
        "scope": [
          "source.reason support.property-value",
          "source.reason entity.name.filename"
        ],
        "settings": {
          "foreground": "#af3a03"
        }
      },
      {
        "scope": [
          "source.powershell variable.other.member.powershell"
        ],
        "settings": {
          "foreground": "#af3a03"
        }
      },
      {
        "scope": [
          "source.powershell support.function.powershell"
        ],
        "settings": {
          "foreground": "#b57614"
        }
      },
      {
        "scope": [
          "source.powershell support.function.attribute.powershell"
        ],
        "settings": {
          "foreground": "#665c54"
        }
      },
      {
        "scope": [
          "source.powershell meta.hashtable.assignment.powershell variable.other.readwrite.powershell"
        ],
        "settings": {
          "foreground": "#af3a03"
        }
      },
      {
        "scope": [
          "support.function.be.latex",
          "support.function.general.tex",
          "support.function.section.latex",
          "support.function.textbf.latex",
          "support.function.textit.latex",
          "support.function.texttt.latex",
          "support.function.emph.latex",
          "support.function.url.latex"
        ],
        "settings": {
          "foreground": "#9d0006"
        }
      },
      {
        "scope": [
          "support.class.math.block.tex",
          "support.class.math.block.environment.latex"
        ],
        "settings": {
          "foreground": "#af3a03"
        }
      },
      {
        "scope": [
          "keyword.control.preamble.latex",
          "keyword.control.include.latex"
        ],
        "settings": {
          "foreground": "#8f3f71"
        }
      },
      {
        "scope": [
          "support.class.latex"
        ],
        "settings": {
          "foreground": "#427b58"
        }
      }
    ],
    "type": "light"
  },
  "matrix-dark": {
    "bg": "#040805",
    "chromeTheme": {
      "fonts": {
        "code": null,
        "ui": "ui-monospace, \"SFMono-Regular\", \"SF Mono\", Menlo, Consolas, \"Liberation Mono\", monospace"
      }
    },
    "colors": {
      "activityBar.activeBorder": "#1eff5a",
      "activityBar.background": "#020402",
      "activityBarBadge.background": "#1eff5a",
      "button.background": "#1eff5a",
      "editor.background": "#040805",
      "editor.foreground": "#b8ffca",
      "editorCursor.foreground": "#1eff5a",
      "editorGroupHeader.tabsBackground": "#020402",
      "focusBorder": "#1eff5a",
      "foreground": "#b8ffca",
      "panel.background": "#020402",
      "sideBar.background": "#020402",
      "sideBar.foreground": "#9bffb8",
      "sideBarTitle.foreground": "#d8ffe2",
      "textLink.foreground": "#1eff5a"
    },
    "fg": "#b8ffca",
    "name": "matrix-dark",
    "tokenColors": [
      {
        "scope": [
          "comment",
          "punctuation.definition.comment"
        ],
        "settings": {
          "foreground": "#3f8f52"
        }
      },
      {
        "scope": [
          "string",
          "string.quoted",
          "constant.other.symbol",
          "entity.other.attribute-name",
          "support.constant"
        ],
        "settings": {
          "foreground": "#7dff95"
        }
      },
      {
        "scope": [
          "constant.numeric",
          "constant.language",
          "constant.language.boolean",
          "constant.character.escape",
          "regexp",
          "string.regexp"
        ],
        "settings": {
          "foreground": "#55ff7d"
        }
      },
      {
        "scope": [
          "keyword",
          "keyword.control",
          "storage",
          "storage.type",
          "storage.modifier"
        ],
        "settings": {
          "foreground": "#1eff5a"
        }
      },
      {
        "scope": [
          "entity.name.type",
          "entity.other.inherited-class",
          "support.class",
          "support.type"
        ],
        "settings": {
          "foreground": "#3adf6a"
        }
      },
      {
        "scope": [
          "entity.name.function",
          "support.function",
          "variable.function",
          "meta.function-call"
        ],
        "settings": {
          "foreground": "#9bffb8"
        }
      },
      {
        "scope": [
          "keyword.operator",
          "punctuation.accessor",
          "punctuation.definition.tag",
          "punctuation",
          "punctuation.bracket",
          "punctuation.separator"
        ],
        "settings": {
          "foreground": "#6bd985"
        }
      },
      {
        "scope": [
          "variable",
          "meta.object-literal.key",
          "meta.object.member",
          "meta.property-name"
        ],
        "settings": {
          "foreground": "#b8ffca"
        }
      }
    ],
    "type": "dark"
  },
  "rose-pine-moon": {
    "colors": {
      "activityBar.activeBorder": "#e0def4",
      "activityBar.background": "#232136",
      "activityBar.dropBorder": "#393552",
      "activityBar.foreground": "#e0def4",
      "activityBar.inactiveForeground": "#908caa",
      "activityBarBadge.background": "#ea9a97",
      "activityBarBadge.foreground": "#232136",
      "badge.background": "#ea9a97",
      "badge.foreground": "#232136",
      "banner.background": "#2a273f",
      "banner.foreground": "#e0def4",
      "banner.iconForeground": "#908caa",
      "breadcrumb.activeSelectionForeground": "#ea9a97",
      "breadcrumb.background": "#232136",
      "breadcrumb.focusForeground": "#908caa",
      "breadcrumb.foreground": "#6e6a86",
      "breadcrumbPicker.background": "#2a273f",
      "button.background": "#ea9a97",
      "button.foreground": "#232136",
      "button.hoverBackground": "#ea9a97e6",
      "button.secondaryBackground": "#2a273f",
      "button.secondaryForeground": "#e0def4",
      "button.secondaryHoverBackground": "#393552",
      "charts.blue": "#9ccfd8",
      "charts.foreground": "#e0def4",
      "charts.green": "#3e8fb0",
      "charts.lines": "#908caa",
      "charts.orange": "#ea9a97",
      "charts.purple": "#c4a7e7",
      "charts.red": "#eb6f92",
      "charts.yellow": "#f6c177",
      "checkbox.background": "#2a273f",
      "checkbox.border": "#817c9c26",
      "checkbox.foreground": "#e0def4",
      "debugExceptionWidget.background": "#2a273f",
      "debugExceptionWidget.border": "#817c9c26",
      "debugIcon.breakpointCurrentStackframeForeground": "#908caa",
      "debugIcon.breakpointDisabledForeground": "#908caa",
      "debugIcon.breakpointForeground": "#908caa",
      "debugIcon.breakpointStackframeForeground": "#908caa",
      "debugIcon.breakpointUnverifiedForeground": "#908caa",
      "debugIcon.continueForeground": "#908caa",
      "debugIcon.disconnectForeground": "#908caa",
      "debugIcon.pauseForeground": "#908caa",
      "debugIcon.restartForeground": "#908caa",
      "debugIcon.startForeground": "#908caa",
      "debugIcon.stepBackForeground": "#908caa",
      "debugIcon.stepIntoForeground": "#908caa",
      "debugIcon.stepOutForeground": "#908caa",
      "debugIcon.stepOverForeground": "#908caa",
      "debugIcon.stopForeground": "#eb6f92",
      "debugToolBar.background": "#2a273f",
      "debugToolBar.border": "#393552",
      "descriptionForeground": "#908caa",
      "diffEditor.border": "#393552",
      "diffEditor.diagonalFill": "#817c9c4d",
      "diffEditor.insertedLineBackground": "#9ccfd826",
      "diffEditor.insertedTextBackground": "#9ccfd826",
      "diffEditor.removedLineBackground": "#eb6f9226",
      "diffEditor.removedTextBackground": "#eb6f9226",
      "diffEditorOverview.insertedForeground": "#9ccfd880",
      "diffEditorOverview.removedForeground": "#eb6f9280",
      "dropdown.background": "#2a273f",
      "dropdown.border": "#817c9c26",
      "dropdown.foreground": "#e0def4",
      "dropdown.listBackground": "#2a273f",
      "editor.background": "#232136",
      "editor.findMatchBackground": "#f6c17733",
      "editor.findMatchBorder": "#f6c17780",
      "editor.findMatchForeground": "#e0def4",
      "editor.findMatchHighlightBackground": "#817c9c4d",
      "editor.findMatchHighlightForeground": "#e0def4cc",
      "editor.findRangeHighlightBackground": "#817c9c4d",
      "editor.findRangeHighlightBorder": "#0000",
      "editor.focusedStackFrameHighlightBackground": "#817c9c26",
      "editor.foldBackground": "#817c9c26",
      "editor.foreground": "#e0def4",
      "editor.hoverHighlightBackground": "#0000",
      "editor.inactiveSelectionBackground": "#817c9c14",
      "editor.inlineValuesBackground": "#0000",
      "editor.inlineValuesForeground": "#908caa",
      "editor.lineHighlightBackground": "#817c9c14",
      "editor.lineHighlightBorder": "#0000",
      "editor.linkedEditingBackground": "#817c9c26",
      "editor.rangeHighlightBackground": "#817c9c14",
      "editor.selectionBackground": "#817c9c26",
      "editor.selectionForeground": "#e0def4",
      "editor.selectionHighlightBackground": "#817c9c26",
      "editor.selectionHighlightBorder": "#232136",
      "editor.snippetFinalTabstopHighlightBackground": "#817c9c26",
      "editor.snippetFinalTabstopHighlightBorder": "#2a273f",
      "editor.snippetTabstopHighlightBackground": "#817c9c26",
      "editor.snippetTabstopHighlightBorder": "#2a273f",
      "editor.stackFrameHighlightBackground": "#817c9c26",
      "editor.symbolHighlightBackground": "#817c9c26",
      "editor.symbolHighlightBorder": "#0000",
      "editor.wordHighlightBackground": "#817c9c26",
      "editor.wordHighlightBorder": "#0000",
      "editor.wordHighlightStrongBackground": "#817c9c26",
      "editor.wordHighlightStrongBorder": "#817c9c26",
      "editorBracketHighlight.foreground1": "#eb6f9280",
      "editorBracketHighlight.foreground2": "#3e8fb080",
      "editorBracketHighlight.foreground3": "#f6c17780",
      "editorBracketHighlight.foreground4": "#9ccfd880",
      "editorBracketHighlight.foreground5": "#ea9a9780",
      "editorBracketHighlight.foreground6": "#c4a7e780",
      "editorBracketMatch.background": "#0000",
      "editorBracketMatch.border": "#908caa",
      "editorBracketPairGuide.activeBackground1": "#3e8fb0",
      "editorBracketPairGuide.activeBackground2": "#ea9a97",
      "editorBracketPairGuide.activeBackground3": "#c4a7e7",
      "editorBracketPairGuide.activeBackground4": "#9ccfd8",
      "editorBracketPairGuide.activeBackground5": "#f6c177",
      "editorBracketPairGuide.activeBackground6": "#eb6f92",
      "editorBracketPairGuide.background1": "#3e8fb080",
      "editorBracketPairGuide.background2": "#ea9a9780",
      "editorBracketPairGuide.background3": "#c4a7e780",
      "editorBracketPairGuide.background4": "#9ccfd880",
      "editorBracketPairGuide.background5": "#f6c17780",
      "editorBracketPairGuide.background6": "#eb6f9280",
      "editorCodeLens.foreground": "#ea9a97",
      "editorCursor.background": "#e0def4",
      "editorCursor.foreground": "#6e6a86",
      "editorError.border": "#0000",
      "editorError.foreground": "#eb6f92",
      "editorGhostText.foreground": "#908caa",
      "editorGroup.border": "#0000",
      "editorGroup.dropBackground": "#2a273f",
      "editorGroup.emptyBackground": "#0000",
      "editorGroup.focusedEmptyBorder": "#0000",
      "editorGroupHeader.noTabsBackground": "#0000",
      "editorGroupHeader.tabsBackground": "#0000",
      "editorGroupHeader.tabsBorder": "#0000",
      "editorGutter.addedBackground": "#9ccfd8",
      "editorGutter.background": "#232136",
      "editorGutter.commentRangeForeground": "#393552",
      "editorGutter.deletedBackground": "#eb6f92",
      "editorGutter.foldingControlForeground": "#c4a7e7",
      "editorGutter.modifiedBackground": "#ea9a97",
      "editorHint.border": "#0000",
      "editorHint.foreground": "#908caa",
      "editorHoverWidget.background": "#2a273f",
      "editorHoverWidget.border": "#6e6a8680",
      "editorHoverWidget.foreground": "#908caa",
      "editorHoverWidget.highlightForeground": "#e0def4",
      "editorHoverWidget.statusBarBackground": "#0000",
      "editorIndentGuide.activeBackground1": "#6e6a86",
      "editorIndentGuide.background1": "#817c9c4d",
      "editorInfo.border": "#393552",
      "editorInfo.foreground": "#9ccfd8",
      "editorInlayHint.background": "#39355280",
      "editorInlayHint.foreground": "#908caa80",
      "editorInlayHint.parameterBackground": "#39355280",
      "editorInlayHint.parameterForeground": "#c4a7e780",
      "editorInlayHint.typeBackground": "#39355280",
      "editorInlayHint.typeForeground": "#9ccfd880",
      "editorLightBulb.foreground": "#3e8fb0",
      "editorLightBulbAutoFix.foreground": "#ea9a97",
      "editorLineNumber.activeForeground": "#e0def4",
      "editorLineNumber.foreground": "#908caa",
      "editorLink.activeForeground": "#ea9a97",
      "editorMarkerNavigation.background": "#2a273f",
      "editorMarkerNavigationError.background": "#2a273f",
      "editorMarkerNavigationInfo.background": "#2a273f",
      "editorMarkerNavigationWarning.background": "#2a273f",
      "editorOverviewRuler.addedForeground": "#9ccfd880",
      "editorOverviewRuler.background": "#232136",
      "editorOverviewRuler.border": "#817c9c4d",
      "editorOverviewRuler.bracketMatchForeground": "#908caa",
      "editorOverviewRuler.commentForeground": "#908caa80",
      "editorOverviewRuler.commentUnresolvedForeground": "#f6c17780",
      "editorOverviewRuler.commonContentForeground": "#817c9c14",
      "editorOverviewRuler.currentContentForeground": "#817c9c26",
      "editorOverviewRuler.deletedForeground": "#eb6f9280",
      "editorOverviewRuler.errorForeground": "#eb6f9280",
      "editorOverviewRuler.findMatchForeground": "#817c9c4d",
      "editorOverviewRuler.incomingContentForeground": "#c4a7e780",
      "editorOverviewRuler.infoForeground": "#9ccfd880",
      "editorOverviewRuler.modifiedForeground": "#ea9a9780",
      "editorOverviewRuler.rangeHighlightForeground": "#817c9c4d",
      "editorOverviewRuler.selectionHighlightForeground": "#817c9c4d",
      "editorOverviewRuler.warningForeground": "#f6c17780",
      "editorOverviewRuler.wordHighlightForeground": "#817c9c26",
      "editorOverviewRuler.wordHighlightStrongForeground": "#817c9c4d",
      "editorPane.background": "#0000",
      "editorRuler.foreground": "#817c9c4d",
      "editorSuggestWidget.background": "#2a273f",
      "editorSuggestWidget.border": "#0000",
      "editorSuggestWidget.focusHighlightForeground": "#ea9a97",
      "editorSuggestWidget.foreground": "#908caa",
      "editorSuggestWidget.highlightForeground": "#ea9a97",
      "editorSuggestWidget.selectedBackground": "#817c9c26",
      "editorSuggestWidget.selectedForeground": "#e0def4",
      "editorSuggestWidget.selectedIconForeground": "#e0def4",
      "editorUnnecessaryCode.border": "#0000",
      "editorUnnecessaryCode.opacity": "#e0def480",
      "editorWarning.border": "#0000",
      "editorWarning.foreground": "#f6c177",
      "editorWhitespace.foreground": "#6e6a8680",
      "editorWidget.background": "#2a273f",
      "editorWidget.border": "#393552",
      "editorWidget.foreground": "#908caa",
      "editorWidget.resizeBorder": "#6e6a86",
      "errorForeground": "#eb6f92",
      "extensionBadge.remoteBackground": "#c4a7e7",
      "extensionBadge.remoteForeground": "#232136",
      "extensionButton.prominentBackground": "#ea9a97",
      "extensionButton.prominentForeground": "#232136",
      "extensionButton.prominentHoverBackground": "#ea9a97e6",
      "extensionIcon.preReleaseForeground": "#3e8fb0",
      "extensionIcon.starForeground": "#ea9a97",
      "extensionIcon.verifiedForeground": "#c4a7e7",
      "focusBorder": "#817c9c26",
      "foreground": "#e0def4",
      "git.blame.editorDecorationForeground": "#6e6a86",
      "gitDecoration.addedResourceForeground": "#9ccfd8",
      "gitDecoration.conflictingResourceForeground": "#eb6f92",
      "gitDecoration.deletedResourceForeground": "#908caa",
      "gitDecoration.ignoredResourceForeground": "#6e6a86",
      "gitDecoration.modifiedResourceForeground": "#ea9a97",
      "gitDecoration.renamedResourceForeground": "#3e8fb0",
      "gitDecoration.stageDeletedResourceForeground": "#eb6f92",
      "gitDecoration.stageModifiedResourceForeground": "#c4a7e7",
      "gitDecoration.submoduleResourceForeground": "#f6c177",
      "gitDecoration.untrackedResourceForeground": "#f6c177",
      "icon.foreground": "#908caa",
      "input.background": "#39355280",
      "input.border": "#817c9c26",
      "input.foreground": "#e0def4",
      "input.placeholderForeground": "#908caa",
      "inputOption.activeBackground": "#ea9a9726",
      "inputOption.activeBorder": "#0000",
      "inputOption.activeForeground": "#ea9a97",
      "inputValidation.errorBackground": "#2a273f",
      "inputValidation.errorBorder": "#817c9c4d",
      "inputValidation.errorForeground": "#eb6f92",
      "inputValidation.infoBackground": "#2a273f",
      "inputValidation.infoBorder": "#817c9c4d",
      "inputValidation.infoForeground": "#9ccfd8",
      "inputValidation.warningBackground": "#2a273f",
      "inputValidation.warningBorder": "#817c9c4d",
      "inputValidation.warningForeground": "#9ccfd880",
      "keybindingLabel.background": "#393552",
      "keybindingLabel.border": "#817c9c4d",
      "keybindingLabel.bottomBorder": "#817c9c4d",
      "keybindingLabel.foreground": "#c4a7e7",
      "keybindingTable.headerBackground": "#393552",
      "keybindingTable.rowsBackground": "#2a273f",
      "list.activeSelectionBackground": "#817c9c26",
      "list.activeSelectionForeground": "#e0def4",
      "list.deemphasizedForeground": "#908caa",
      "list.dropBackground": "#2a273f",
      "list.errorForeground": "#eb6f92",
      "list.filterMatchBackground": "#2a273f",
      "list.filterMatchBorder": "#ea9a97",
      "list.focusBackground": "#817c9c4d",
      "list.focusForeground": "#e0def4",
      "list.focusOutline": "#817c9c26",
      "list.highlightForeground": "#ea9a97",
      "list.hoverBackground": "#817c9c14",
      "list.hoverForeground": "#e0def4",
      "list.inactiveFocusBackground": "#817c9c14",
      "list.inactiveSelectionBackground": "#2a273f",
      "list.inactiveSelectionForeground": "#e0def4",
      "list.invalidItemForeground": "#eb6f92",
      "list.warningForeground": "#f6c177",
      "listFilterWidget.background": "#2a273f",
      "listFilterWidget.noMatchesOutline": "#eb6f92",
      "listFilterWidget.outline": "#393552",
      "menu.background": "#2a273f",
      "menu.border": "#817c9c14",
      "menu.foreground": "#e0def4",
      "menu.selectionBackground": "#817c9c26",
      "menu.selectionBorder": "#393552",
      "menu.selectionForeground": "#e0def4",
      "menu.separatorBackground": "#817c9c4d",
      "menubar.selectionBackground": "#817c9c26",
      "menubar.selectionBorder": "#817c9c14",
      "menubar.selectionForeground": "#e0def4",
      "merge.border": "#393552",
      "merge.commonContentBackground": "#817c9c26",
      "merge.commonHeaderBackground": "#817c9c26",
      "merge.currentContentBackground": "#f6c17733",
      "merge.currentHeaderBackground": "#f6c17733",
      "merge.incomingContentBackground": "#9ccfd833",
      "merge.incomingHeaderBackground": "#9ccfd833",
      "minimap.background": "#2a273f",
      "minimap.errorHighlight": "#eb6f9280",
      "minimap.findMatchHighlight": "#817c9c26",
      "minimap.selectionHighlight": "#817c9c26",
      "minimap.warningHighlight": "#f6c17780",
      "minimapGutter.addedBackground": "#9ccfd8",
      "minimapGutter.deletedBackground": "#eb6f92",
      "minimapGutter.modifiedBackground": "#ea9a97",
      "minimapSlider.activeBackground": "#817c9c4d",
      "minimapSlider.background": "#817c9c26",
      "minimapSlider.hoverBackground": "#817c9c26",
      "notebook.cellBorderColor": "#9ccfd880",
      "notebook.cellEditorBackground": "#2a273f",
      "notebook.cellHoverBackground": "#39355280",
      "notebook.focusedCellBackground": "#817c9c14",
      "notebook.focusedCellBorder": "#9ccfd8",
      "notebook.outputContainerBackgroundColor": "#817c9c14",
      "notificationCenter.border": "#817c9c26",
      "notificationCenterHeader.background": "#2a273f",
      "notificationCenterHeader.foreground": "#908caa",
      "notificationLink.foreground": "#c4a7e7",
      "notifications.background": "#2a273f",
      "notifications.border": "#817c9c26",
      "notifications.foreground": "#e0def4",
      "notificationsErrorIcon.foreground": "#eb6f92",
      "notificationsInfoIcon.foreground": "#9ccfd8",
      "notificationsWarningIcon.foreground": "#f6c177",
      "notificationToast.border": "#817c9c26",
      "panel.background": "#2a273f",
      "panel.border": "#0000",
      "panel.dropBorder": "#393552",
      "panelInput.border": "#2a273f",
      "panelSection.dropBackground": "#817c9c26",
      "panelSectionHeader.background": "#2a273f",
      "panelSectionHeader.foreground": "#e0def4",
      "panelTitle.activeBorder": "#817c9c4d",
      "panelTitle.activeForeground": "#e0def4",
      "panelTitle.inactiveForeground": "#908caa",
      "peekView.border": "#393552",
      "peekViewEditor.background": "#2a273f",
      "peekViewEditor.matchHighlightBackground": "#817c9c4d",
      "peekViewResult.background": "#2a273f",
      "peekViewResult.fileForeground": "#908caa",
      "peekViewResult.lineForeground": "#908caa",
      "peekViewResult.matchHighlightBackground": "#817c9c4d",
      "peekViewResult.selectionBackground": "#817c9c26",
      "peekViewResult.selectionForeground": "#e0def4",
      "peekViewTitle.background": "#393552",
      "peekViewTitleDescription.foreground": "#908caa",
      "pickerGroup.border": "#817c9c4d",
      "pickerGroup.foreground": "#c4a7e7",
      "ports.iconRunningProcessForeground": "#ea9a97",
      "problemsErrorIcon.foreground": "#eb6f92",
      "problemsInfoIcon.foreground": "#9ccfd8",
      "problemsWarningIcon.foreground": "#f6c177",
      "progressBar.background": "#ea9a97",
      "quickInput.background": "#2a273f",
      "quickInput.foreground": "#908caa",
      "quickInputList.focusBackground": "#817c9c26",
      "quickInputList.focusForeground": "#e0def4",
      "quickInputList.focusIconForeground": "#e0def4",
      "scrollbar.shadow": "#2a273f4d",
      "scrollbarSlider.activeBackground": "#3e8fb080",
      "scrollbarSlider.background": "#817c9c26",
      "scrollbarSlider.hoverBackground": "#817c9c4d",
      "searchEditor.findMatchBackground": "#817c9c26",
      "selection.background": "#817c9c4d",
      "settings.focusedRowBackground": "#2a273f",
      "settings.focusedRowBorder": "#817c9c26",
      "settings.headerForeground": "#e0def4",
      "settings.modifiedItemIndicator": "#ea9a97",
      "settings.rowHoverBackground": "#2a273f",
      "sideBar.background": "#232136",
      "sideBar.dropBackground": "#2a273f",
      "sideBar.foreground": "#908caa",
      "sideBarSectionHeader.background": "#0000",
      "sideBarSectionHeader.border": "#817c9c26",
      "statusBar.background": "#232136",
      "statusBar.debuggingBackground": "#c4a7e7",
      "statusBar.debuggingForeground": "#232136",
      "statusBar.foreground": "#908caa",
      "statusBar.noFolderBackground": "#232136",
      "statusBar.noFolderForeground": "#908caa",
      "statusBarItem.activeBackground": "#817c9c4d",
      "statusBarItem.errorBackground": "#232136",
      "statusBarItem.errorForeground": "#eb6f92",
      "statusBarItem.hoverBackground": "#817c9c26",
      "statusBarItem.prominentBackground": "#393552",
      "statusBarItem.prominentForeground": "#e0def4",
      "statusBarItem.prominentHoverBackground": "#817c9c26",
      "statusBarItem.remoteBackground": "#232136",
      "statusBarItem.remoteForeground": "#f6c177",
      "symbolIcon.arrayForeground": "#908caa",
      "symbolIcon.classForeground": "#908caa",
      "symbolIcon.colorForeground": "#908caa",
      "symbolIcon.constantForeground": "#908caa",
      "symbolIcon.constructorForeground": "#908caa",
      "symbolIcon.enumeratorForeground": "#908caa",
      "symbolIcon.enumeratorMemberForeground": "#908caa",
      "symbolIcon.eventForeground": "#908caa",
      "symbolIcon.fieldForeground": "#908caa",
      "symbolIcon.fileForeground": "#908caa",
      "symbolIcon.folderForeground": "#908caa",
      "symbolIcon.functionForeground": "#908caa",
      "symbolIcon.interfaceForeground": "#908caa",
      "symbolIcon.keyForeground": "#908caa",
      "symbolIcon.keywordForeground": "#908caa",
      "symbolIcon.methodForeground": "#908caa",
      "symbolIcon.moduleForeground": "#908caa",
      "symbolIcon.namespaceForeground": "#908caa",
      "symbolIcon.nullForeground": "#908caa",
      "symbolIcon.numberForeground": "#908caa",
      "symbolIcon.objectForeground": "#908caa",
      "symbolIcon.operatorForeground": "#908caa",
      "symbolIcon.packageForeground": "#908caa",
      "symbolIcon.propertyForeground": "#908caa",
      "symbolIcon.referenceForeground": "#908caa",
      "symbolIcon.snippetForeground": "#908caa",
      "symbolIcon.stringForeground": "#908caa",
      "symbolIcon.structForeground": "#908caa",
      "symbolIcon.textForeground": "#908caa",
      "symbolIcon.typeParameterForeground": "#908caa",
      "symbolIcon.unitForeground": "#908caa",
      "symbolIcon.variableForeground": "#908caa",
      "tab.activeBackground": "#817c9c14",
      "tab.activeForeground": "#e0def4",
      "tab.activeModifiedBorder": "#9ccfd8",
      "tab.border": "#0000",
      "tab.hoverBackground": "#817c9c26",
      "tab.inactiveBackground": "#0000",
      "tab.inactiveForeground": "#908caa",
      "tab.inactiveModifiedBorder": "#9ccfd880",
      "tab.lastPinnedBorder": "#6e6a86",
      "tab.unfocusedActiveBackground": "#0000",
      "tab.unfocusedHoverBackground": "#0000",
      "tab.unfocusedInactiveBackground": "#0000",
      "tab.unfocusedInactiveModifiedBorder": "#9ccfd880",
      "terminal.ansiBlack": "#393552",
      "terminal.ansiBlue": "#9ccfd8",
      "terminal.ansiBrightBlack": "#908caa",
      "terminal.ansiBrightBlue": "#9ccfd8",
      "terminal.ansiBrightCyan": "#ea9a97",
      "terminal.ansiBrightGreen": "#3e8fb0",
      "terminal.ansiBrightMagenta": "#c4a7e7",
      "terminal.ansiBrightRed": "#eb6f92",
      "terminal.ansiBrightWhite": "#e0def4",
      "terminal.ansiBrightYellow": "#f6c177",
      "terminal.ansiCyan": "#ea9a97",
      "terminal.ansiGreen": "#3e8fb0",
      "terminal.ansiMagenta": "#c4a7e7",
      "terminal.ansiRed": "#eb6f92",
      "terminal.ansiWhite": "#e0def4",
      "terminal.ansiYellow": "#f6c177",
      "terminal.dropBackground": "#817c9c26",
      "terminal.foreground": "#e0def4",
      "terminal.selectionBackground": "#817c9c26",
      "terminal.tab.activeBorder": "#e0def4",
      "terminalCursor.background": "#e0def4",
      "terminalCursor.foreground": "#6e6a86",
      "textBlockQuote.background": "#2a273f",
      "textBlockQuote.border": "#817c9c26",
      "textCodeBlock.background": "#2a273f",
      "textLink.activeForeground": "#c4a7e7e6",
      "textLink.foreground": "#c4a7e7",
      "textPreformat.foreground": "#f6c177",
      "textSeparator.foreground": "#908caa",
      "titleBar.activeBackground": "#232136",
      "titleBar.activeForeground": "#908caa",
      "titleBar.inactiveBackground": "#2a273f",
      "titleBar.inactiveForeground": "#908caa",
      "toolbar.activeBackground": "#817c9c4d",
      "toolbar.hoverBackground": "#817c9c26",
      "tree.indentGuidesStroke": "#908caa",
      "walkThrough.embeddedEditorBackground": "#232136",
      "welcomePage.background": "#232136",
      "widget.shadow": "#2a273f4d",
      "window.activeBorder": "#2a273f",
      "window.inactiveBorder": "#2a273f"
    },
    "name": "rose-pine-moon",
    "tokenColors": [
      {
        "scope": [
          "comment"
        ],
        "settings": {
          "fontStyle": "italic",
          "foreground": "#6e6a86"
        }
      },
      {
        "scope": [
          "constant"
        ],
        "settings": {
          "foreground": "#3e8fb0"
        }
      },
      {
        "scope": [
          "constant.numeric",
          "constant.language"
        ],
        "settings": {
          "foreground": "#ea9a97"
        }
      },
      {
        "scope": [
          "entity.name"
        ],
        "settings": {
          "foreground": "#ea9a97"
        }
      },
      {
        "scope": [
          "entity.name.section",
          "entity.name.tag",
          "entity.name.namespace",
          "entity.name.type"
        ],
        "settings": {
          "foreground": "#9ccfd8"
        }
      },
      {
        "scope": [
          "entity.other.attribute-name",
          "entity.other.inherited-class"
        ],
        "settings": {
          "fontStyle": "italic",
          "foreground": "#c4a7e7"
        }
      },
      {
        "scope": [
          "invalid"
        ],
        "settings": {
          "foreground": "#eb6f92"
        }
      },
      {
        "scope": [
          "invalid.deprecated"
        ],
        "settings": {
          "foreground": "#908caa"
        }
      },
      {
        "scope": [
          "keyword",
          "variable.language.this"
        ],
        "settings": {
          "foreground": "#3e8fb0"
        }
      },
      {
        "scope": [
          "markup.inserted.diff"
        ],
        "settings": {
          "foreground": "#9ccfd8"
        }
      },
      {
        "scope": [
          "markup.deleted.diff"
        ],
        "settings": {
          "foreground": "#eb6f92"
        }
      },
      {
        "scope": "markup.heading",
        "settings": {
          "fontStyle": "bold"
        }
      },
      {
        "scope": "markup.bold.markdown",
        "settings": {
          "fontStyle": "bold"
        }
      },
      {
        "scope": "markup.italic.markdown",
        "settings": {
          "fontStyle": "italic"
        }
      },
      {
        "scope": [
          "meta.diff.range"
        ],
        "settings": {
          "foreground": "#c4a7e7"
        }
      },
      {
        "scope": [
          "meta.tag",
          "meta.brace"
        ],
        "settings": {
          "foreground": "#e0def4"
        }
      },
      {
        "scope": [
          "meta.import",
          "meta.export"
        ],
        "settings": {
          "foreground": "#3e8fb0"
        }
      },
      {
        "scope": "meta.directive.vue",
        "settings": {
          "fontStyle": "italic",
          "foreground": "#c4a7e7"
        }
      },
      {
        "scope": "meta.property-name.css",
        "settings": {
          "foreground": "#9ccfd8"
        }
      },
      {
        "scope": "meta.property-value.css",
        "settings": {
          "foreground": "#f6c177"
        }
      },
      {
        "scope": "meta.tag.other.html",
        "settings": {
          "foreground": "#908caa"
        }
      },
      {
        "scope": [
          "punctuation"
        ],
        "settings": {
          "foreground": "#908caa"
        }
      },
      {
        "scope": [
          "punctuation.accessor"
        ],
        "settings": {
          "foreground": "#3e8fb0"
        }
      },
      {
        "scope": [
          "punctuation.definition.string"
        ],
        "settings": {
          "foreground": "#f6c177"
        }
      },
      {
        "scope": [
          "punctuation.definition.tag"
        ],
        "settings": {
          "foreground": "#6e6a86"
        }
      },
      {
        "scope": [
          "storage.type",
          "storage.modifier"
        ],
        "settings": {
          "foreground": "#3e8fb0"
        }
      },
      {
        "scope": [
          "string"
        ],
        "settings": {
          "foreground": "#f6c177"
        }
      },
      {
        "scope": [
          "support"
        ],
        "settings": {
          "foreground": "#9ccfd8"
        }
      },
      {
        "scope": [
          "support.constant"
        ],
        "settings": {
          "foreground": "#f6c177"
        }
      },
      {
        "scope": [
          "support.function"
        ],
        "settings": {
          "fontStyle": "italic",
          "foreground": "#eb6f92"
        }
      },
      {
        "scope": [
          "variable"
        ],
        "settings": {
          "fontStyle": "italic",
          "foreground": "#ea9a97"
        }
      },
      {
        "scope": [
          "variable.other",
          "variable.language",
          "variable.function",
          "variable.argument"
        ],
        "settings": {
          "foreground": "#e0def4"
        }
      },
      {
        "scope": [
          "variable.parameter"
        ],
        "settings": {
          "foreground": "#c4a7e7"
        }
      }
    ],
    "type": "dark"
  },
  "solarized-dark": {
    "colors": {
      "activityBar.background": "#003847",
      "badge.background": "#047aa6",
      "button.background": "#2AA19899",
      "debugExceptionWidget.background": "#00212B",
      "debugExceptionWidget.border": "#AB395B",
      "debugToolBar.background": "#00212B",
      "dropdown.background": "#00212B",
      "dropdown.border": "#2AA19899",
      "editor.background": "#002B36",
      "editor.foreground": "#839496",
      "editor.lineHighlightBackground": "#073642",
      "editor.selectionBackground": "#274642",
      "editor.selectionHighlightBackground": "#005A6FAA",
      "editor.wordHighlightBackground": "#004454AA",
      "editor.wordHighlightStrongBackground": "#005A6FAA",
      "editorBracketHighlight.foreground1": "#cdcdcdff",
      "editorBracketHighlight.foreground2": "#b58900ff",
      "editorBracketHighlight.foreground3": "#d33682ff",
      "editorCursor.foreground": "#D30102",
      "editorGroup.border": "#00212B",
      "editorGroup.dropBackground": "#2AA19844",
      "editorGroupHeader.tabsBackground": "#004052",
      "editorHoverWidget.background": "#004052",
      "editorIndentGuide.activeBackground": "#C3E1E180",
      "editorIndentGuide.background": "#93A1A180",
      "editorLineNumber.activeForeground": "#949494",
      "editorMarkerNavigationError.background": "#AB395B",
      "editorMarkerNavigationWarning.background": "#5B7E7A",
      "editorWhitespace.foreground": "#93A1A180",
      "editorWidget.background": "#00212B",
      "errorForeground": "#ffeaea",
      "focusBorder": "#2AA19899",
      "input.background": "#003847",
      "input.foreground": "#93A1A1",
      "input.placeholderForeground": "#93A1A1AA",
      "inputOption.activeBorder": "#2AA19899",
      "inputValidation.errorBackground": "#571b26",
      "inputValidation.errorBorder": "#a92049",
      "inputValidation.infoBackground": "#052730",
      "inputValidation.infoBorder": "#363b5f",
      "inputValidation.warningBackground": "#5d5938",
      "inputValidation.warningBorder": "#9d8a5e",
      "list.activeSelectionBackground": "#005A6F",
      "list.dropBackground": "#00445488",
      "list.highlightForeground": "#1ebcc5",
      "list.hoverBackground": "#004454AA",
      "list.inactiveSelectionBackground": "#00445488",
      "minimap.selectionHighlight": "#274642",
      "panel.border": "#2b2b4a",
      "peekView.border": "#2b2b4a",
      "peekViewEditor.background": "#10192c",
      "peekViewEditor.matchHighlightBackground": "#7744AA40",
      "peekViewResult.background": "#00212B",
      "peekViewTitle.background": "#00212B",
      "pickerGroup.border": "#2AA19899",
      "pickerGroup.foreground": "#2AA19899",
      "ports.iconRunningProcessForeground": "#369432",
      "progressBar.background": "#047aa6",
      "quickInputList.focusBackground": "#005A6F",
      "selection.background": "#2AA19899",
      "sideBar.background": "#00212B",
      "sideBarTitle.foreground": "#93A1A1",
      "statusBar.background": "#00212B",
      "statusBar.debuggingBackground": "#00212B",
      "statusBar.foreground": "#93A1A1",
      "statusBar.noFolderBackground": "#00212B",
      "statusBarItem.prominentBackground": "#003847",
      "statusBarItem.prominentHoverBackground": "#003847",
      "statusBarItem.remoteBackground": "#2AA19899",
      "tab.activeBackground": "#002B37",
      "tab.activeForeground": "#d6dbdb",
      "tab.border": "#003847",
      "tab.inactiveBackground": "#004052",
      "tab.inactiveForeground": "#93A1A1",
      "tab.lastPinnedBorder": "#2AA19844",
      "terminal.ansiBlack": "#073642",
      "terminal.ansiBlue": "#268bd2",
      "terminal.ansiBrightBlack": "#002b36",
      "terminal.ansiBrightBlue": "#839496",
      "terminal.ansiBrightCyan": "#93a1a1",
      "terminal.ansiBrightGreen": "#586e75",
      "terminal.ansiBrightMagenta": "#6c71c4",
      "terminal.ansiBrightRed": "#cb4b16",
      "terminal.ansiBrightWhite": "#fdf6e3",
      "terminal.ansiBrightYellow": "#657b83",
      "terminal.ansiCyan": "#2aa198",
      "terminal.ansiGreen": "#859900",
      "terminal.ansiMagenta": "#d33682",
      "terminal.ansiRed": "#dc322f",
      "terminal.ansiWhite": "#eee8d5",
      "terminal.ansiYellow": "#b58900",
      "titleBar.activeBackground": "#002C39"
    },
    "name": "solarized-dark",
    "semanticHighlighting": true,
    "tokenColors": [
      {
        "settings": {
          "foreground": "#839496"
        }
      },
      {
        "scope": [
          "meta.embedded",
          "source.groovy.embedded",
          "string meta.image.inline.markdown",
          "variable.legacy.builtin.python"
        ],
        "settings": {
          "foreground": "#839496"
        }
      },
      {
        "scope": "comment",
        "settings": {
          "fontStyle": "italic",
          "foreground": "#586E75"
        }
      },
      {
        "scope": "string",
        "settings": {
          "foreground": "#2AA198"
        }
      },
      {
        "scope": "string.regexp",
        "settings": {
          "foreground": "#DC322F"
        }
      },
      {
        "scope": "constant.numeric",
        "settings": {
          "foreground": "#D33682"
        }
      },
      {
        "scope": [
          "variable.language",
          "variable.other"
        ],
        "settings": {
          "foreground": "#268BD2"
        }
      },
      {
        "scope": "keyword",
        "settings": {
          "foreground": "#859900"
        }
      },
      {
        "scope": "storage",
        "settings": {
          "fontStyle": "bold",
          "foreground": "#93A1A1"
        }
      },
      {
        "scope": [
          "entity.name.class",
          "entity.name.type",
          "entity.name.namespace",
          "entity.name.scope-resolution"
        ],
        "settings": {
          "fontStyle": "",
          "foreground": "#CB4B16"
        }
      },
      {
        "scope": "entity.name.function",
        "settings": {
          "foreground": "#268BD2"
        }
      },
      {
        "scope": "punctuation.definition.variable",
        "settings": {
          "foreground": "#859900"
        }
      },
      {
        "scope": [
          "punctuation.section.embedded.begin",
          "punctuation.section.embedded.end"
        ],
        "settings": {
          "foreground": "#DC322F"
        }
      },
      {
        "scope": [
          "constant.language",
          "meta.preprocessor"
        ],
        "settings": {
          "foreground": "#B58900"
        }
      },
      {
        "scope": [
          "support.function.construct",
          "keyword.other.new"
        ],
        "settings": {
          "foreground": "#CB4B16"
        }
      },
      {
        "scope": [
          "constant.character",
          "constant.other"
        ],
        "settings": {
          "foreground": "#CB4B16"
        }
      },
      {
        "scope": [
          "entity.other.inherited-class",
          "punctuation.separator.namespace.ruby"
        ],
        "settings": {
          "foreground": "#6C71C4"
        }
      },
      {
        "scope": "variable.parameter",
        "settings": {}
      },
      {
        "scope": "entity.name.tag",
        "settings": {
          "foreground": "#268BD2"
        }
      },
      {
        "scope": "punctuation.definition.tag",
        "settings": {
          "foreground": "#586E75"
        }
      },
      {
        "scope": "entity.other.attribute-name",
        "settings": {
          "foreground": "#93A1A1"
        }
      },
      {
        "scope": "support.function",
        "settings": {
          "foreground": "#268BD2"
        }
      },
      {
        "scope": "punctuation.separator.continuation",
        "settings": {
          "foreground": "#DC322F"
        }
      },
      {
        "scope": [
          "support.constant",
          "support.variable"
        ],
        "settings": {}
      },
      {
        "scope": [
          "support.type",
          "support.class"
        ],
        "settings": {
          "foreground": "#859900"
        }
      },
      {
        "scope": "support.type.exception",
        "settings": {
          "foreground": "#CB4B16"
        }
      },
      {
        "scope": "support.other.variable",
        "settings": {}
      },
      {
        "scope": "invalid",
        "settings": {
          "foreground": "#DC322F"
        }
      },
      {
        "scope": [
          "meta.diff",
          "meta.diff.header"
        ],
        "settings": {
          "fontStyle": "italic",
          "foreground": "#268BD2"
        }
      },
      {
        "scope": "markup.deleted",
        "settings": {
          "fontStyle": "",
          "foreground": "#DC322F"
        }
      },
      {
        "scope": "markup.changed",
        "settings": {
          "fontStyle": "",
          "foreground": "#CB4B16"
        }
      },
      {
        "scope": "markup.inserted",
        "settings": {
          "foreground": "#859900"
        }
      },
      {
        "scope": "markup.quote",
        "settings": {
          "foreground": "#859900"
        }
      },
      {
        "scope": "markup.list",
        "settings": {
          "foreground": "#B58900"
        }
      },
      {
        "scope": [
          "markup.bold",
          "markup.italic"
        ],
        "settings": {
          "foreground": "#D33682"
        }
      },
      {
        "scope": "markup.bold",
        "settings": {
          "fontStyle": "bold"
        }
      },
      {
        "scope": "markup.italic",
        "settings": {
          "fontStyle": "italic"
        }
      },
      {
        "scope": "markup.strikethrough",
        "settings": {
          "fontStyle": "strikethrough"
        }
      },
      {
        "scope": "markup.inline.raw",
        "settings": {
          "fontStyle": "",
          "foreground": "#2AA198"
        }
      },
      {
        "scope": "markup.heading",
        "settings": {
          "fontStyle": "bold",
          "foreground": "#268BD2"
        }
      },
      {
        "scope": "markup.heading.setext",
        "settings": {
          "fontStyle": "",
          "foreground": "#268BD2"
        }
      }
    ],
    "type": "dark"
  },
  "temple-dark": {
    "bg": "#02120c",
    "colors": {
      "activityBar.activeBorder": "#e4f222",
      "activityBar.background": "#1d2d0f",
      "activityBarBadge.background": "#e4f222",
      "button.background": "#e4f222",
      "editor.background": "#02120c",
      "editor.foreground": "#c7e6da",
      "editorCursor.foreground": "#e4f222",
      "editorGroupHeader.tabsBackground": "#1d2d0f",
      "focusBorder": "#e4f222",
      "foreground": "#c7e6da",
      "panel.background": "#1d2d0f",
      "sideBar.background": "#1d2d0f",
      "sideBar.foreground": "#c7e6da",
      "sideBarTitle.foreground": "#c7e6da",
      "textLink.foreground": "#e4f222"
    },
    "fg": "#c7e6da",
    "name": "temple-dark",
    "tokenColors": [
      {
        "scope": [
          "comment",
          "punctuation.definition.comment"
        ],
        "settings": {
          "foreground": "#394d46"
        }
      },
      {
        "scope": [
          "string",
          "constant.other.symbol",
          "entity.name.function",
          "support.function",
          "variable.function",
          "meta.function-call"
        ],
        "settings": {
          "foreground": "#e4f222"
        }
      },
      {
        "scope": [
          "keyword",
          "keyword.control",
          "storage",
          "storage.type",
          "storage.modifier",
          "constant.numeric",
          "constant.language.boolean"
        ],
        "settings": {
          "foreground": "#e4f222"
        }
      },
      {
        "scope": [
          "entity.name.type",
          "entity.other.inherited-class",
          "support.class",
          "support.type"
        ],
        "settings": {
          "foreground": "#859419"
        }
      },
      {
        "scope": [
          "keyword.operator",
          "entity.other.attribute-name"
        ],
        "settings": {
          "foreground": "#788617"
        }
      },
      {
        "scope": [
          "punctuation",
          "punctuation.bracket",
          "punctuation.separator",
          "punctuation.definition.list.begin"
        ],
        "settings": {
          "foreground": "#4f5e13"
        }
      },
      {
        "scope": [
          "variable",
          "variable.other.readwrite",
          "variable.parameter",
          "variable.other.object",
          "variable.language",
          "variable.language.this",
          "variable.language.self",
          "string",
          "string.quoted",
          "variable.other.property",
          "meta.object-literal.key",
          "entity.name.label",
          "meta.annotation",
          "markup.raw"
        ],
        "settings": {
          "foreground": "#c7e6da"
        }
      }
    ],
    "type": "dark"
  },
} as unknown as Readonly<Record<string, ThemeRegistration>>
