// Generated by scripts/generate-codex-themes.ts from xcode-dark-4bF_FmQv.js.
// Do not edit this file manually.
import type { ThemeRegistration } from 'shiki'

const theme = {
  "chromeTheme": {
    "accent": "#5482ff",
    "fonts": {
      "code": "\"SFMono-Medium\""
    },
    "ink": "#ffffffd9",
    "surface": "#1f1f24"
  },
  "colors": {
    "activityBar.activeBorder": "#5482ff",
    "activityBar.background": "#1f1f24",
    "activityBarBadge.background": "#5482ff",
    "button.background": "#5482ff",
    "editor.background": "#1f1f24",
    "editor.foreground": "#ffffffd9",
    "editor.lineHighlightBackground": "#23252b",
    "editor.selectionBackground": "#515b70",
    "editorCursor.foreground": "#5482ff",
    "editorGroupHeader.tabsBackground": "#1f1f24",
    "editorWhitespace.foreground": "#424d5b",
    "focusBorder": "#5482ff",
    "foreground": "#ffffffd9",
    "panel.background": "#1f1f24",
    "sideBar.background": "#1f1f24",
    "sideBar.foreground": "#ffffffd9",
    "sideBarTitle.foreground": "#ffffffd9",
    "textLink.foreground": "#5482ff"
  },
  "name": "xcode-dark",
  "tokenColors": [
    {
      "scope": [
        "comment",
        "punctuation.definition.comment"
      ],
      "settings": {
        "foreground": "#6c7986"
      }
    },
    {
      "scope": [
        "string",
        "constant.other.symbol"
      ],
      "settings": {
        "foreground": "#fc6a5d"
      }
    },
    {
      "scope": [
        "keyword",
        "keyword.control",
        "storage",
        "storage.type",
        "storage.modifier"
      ],
      "settings": {
        "foreground": "#fc5fa3"
      }
    },
    {
      "scope": [
        "constant.numeric",
        "constant.language",
        "constant.character.escape"
      ],
      "settings": {
        "foreground": "#d0bf69"
      }
    },
    {
      "scope": [
        "entity.name.type",
        "entity.name.class",
        "support.type",
        "support.class"
      ],
      "settings": {
        "foreground": "#5dd8ff"
      }
    },
    {
      "scope": [
        "support.function",
        "entity.name.function",
        "meta.function-call",
        "variable.function"
      ],
      "settings": {
        "foreground": "#67b7a4"
      }
    },
    {
      "scope": [
        "variable",
        "identifier",
        "meta.definition.variable",
        "support.variable.property"
      ],
      "settings": {
        "foreground": "#67b7a4"
      }
    },
    {
      "scope": [
        "markup.underline.link",
        "markup.underline.link.markdown"
      ],
      "settings": {
        "foreground": "#5482ff"
      }
    }
  ],
  "type": "dark"
} as unknown as ThemeRegistration

export default theme
export const codexThemeSlug = "xcode-dark"
