// Generated by scripts/generate-codex-themes.ts from xcode-light-DldObiX0.js.
// Do not edit this file manually.
import type { ThemeRegistration } from 'shiki'

const theme = {
  "chromeTheme": {
    "accent": "#0e0eff",
    "fonts": {
      "code": "\"SFMono-Regular\""
    },
    "ink": "#000000d9",
    "surface": "#ffffff"
  },
  "colors": {
    "activityBar.activeBorder": "#0e0eff",
    "activityBar.background": "#ffffff",
    "activityBarBadge.background": "#0e0eff",
    "button.background": "#0e0eff",
    "editor.background": "#ffffff",
    "editor.foreground": "#000000d9",
    "editor.lineHighlightBackground": "#e8f2ff",
    "editor.selectionBackground": "#a4cdff",
    "editorCursor.foreground": "#0e0eff",
    "editorGroupHeader.tabsBackground": "#ffffff",
    "editorWhitespace.foreground": "#cccccc",
    "focusBorder": "#0e0eff",
    "foreground": "#000000d9",
    "panel.background": "#ffffff",
    "sideBar.background": "#ffffff",
    "sideBar.foreground": "#000000d9",
    "sideBarTitle.foreground": "#000000d9",
    "textLink.foreground": "#0e0eff"
  },
  "name": "xcode-light",
  "tokenColors": [
    {
      "scope": [
        "comment",
        "punctuation.definition.comment"
      ],
      "settings": {
        "foreground": "#5d6c79"
      }
    },
    {
      "scope": [
        "string",
        "constant.other.symbol"
      ],
      "settings": {
        "foreground": "#c41a16"
      }
    },
    {
      "scope": [
        "keyword",
        "keyword.control",
        "storage",
        "storage.type",
        "storage.modifier"
      ],
      "settings": {
        "foreground": "#9b2393"
      }
    },
    {
      "scope": [
        "constant.numeric",
        "constant.language",
        "constant.character.escape"
      ],
      "settings": {
        "foreground": "#1c00cf"
      }
    },
    {
      "scope": [
        "entity.name.type",
        "entity.name.class",
        "support.type",
        "support.class"
      ],
      "settings": {
        "foreground": "#0b4f79"
      }
    },
    {
      "scope": [
        "support.function",
        "entity.name.function",
        "meta.function-call",
        "variable.function"
      ],
      "settings": {
        "foreground": "#326d74"
      }
    },
    {
      "scope": [
        "variable",
        "identifier",
        "meta.definition.variable",
        "support.variable.property"
      ],
      "settings": {
        "foreground": "#326d74"
      }
    },
    {
      "scope": [
        "markup.underline.link",
        "markup.underline.link.markdown"
      ],
      "settings": {
        "foreground": "#0e0eff"
      }
    }
  ],
  "type": "light"
} as unknown as ThemeRegistration

export default theme
export const codexThemeSlug = "xcode-light"
