[package]
name = "codepilotx-arg0"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "codepilotx_arg0"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
codepilotx-apply-patch = { workspace = true }
codepilotx-exec-server = { workspace = true }
codepilotx-install-context = { workspace = true }
codepilotx-linux-sandbox = { workspace = true }
codepilotx-sandboxing = { workspace = true }
codepilotx-shell-escalation = { workspace = true }
codepilotx-utils-absolute-path = { workspace = true }
codepilotx-utils-home-dir = { workspace = true }
dotenvy = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread"] }

[target.'cfg(windows)'.dependencies]
codepilotx-windows-sandbox = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
