// This file is generated by scripts/generate-shiki-theme-seeds.ts.
// Do not edit it manually.

export type ShikiThemeSeed = {
  id: string
  label: string
  variant: 'light' | 'dark'
  surface: string
  ink: string
  accent: string
  diffAdded: string
  diffRemoved: string
  skill: string
}

export const SHIKI_THEME_SEEDS = [
  {
    "id": "andromeeda",
    "label": "Andromeeda",
    "variant": "dark",
    "surface": "#23262e",
    "ink": "#d5ced9",
    "accent": "#00b0ff",
    "diffAdded": "#96e072",
    "diffRemoved": "#ee5d43",
    "skill": "#ff00aa"
  },
  {
    "id": "aurora-x",
    "label": "Aurora X",
    "variant": "dark",
    "surface": "#07090f",
    "ink": "#576daf",
    "accent": "#86a5ff",
    "diffAdded": "#64d389",
    "diffRemoved": "#dd5074",
    "skill": "#ad7bf9"
  },
  {
    "id": "ayu-dark",
    "label": "Ayu Dark",
    "variant": "dark",
    "surface": "#10141c",
    "ink": "#bfbdb6",
    "accent": "#e6b450",
    "diffAdded": "#70bf56",
    "diffRemoved": "#f26d78",
    "skill": "#d0a1ff"
  },
  {
    "id": "ayu-light",
    "label": "Ayu Light",
    "variant": "light",
    "surface": "#fcfcfc",
    "ink": "#5c6166",
    "accent": "#f29718",
    "diffAdded": "#6cbf43",
    "diffRemoved": "#ff7383",
    "skill": "#a176cb"
  },
  {
    "id": "ayu-mirage",
    "label": "Ayu Mirage",
    "variant": "dark",
    "surface": "#242936",
    "ink": "#cccac2",
    "accent": "#ffcc66",
    "diffAdded": "#87d96c",
    "diffRemoved": "#f27983",
    "skill": "#ddbbff"
  },
  {
    "id": "catppuccin-frappe",
    "label": "Catppuccin Frappé",
    "variant": "dark",
    "surface": "#303446",
    "ink": "#c6d0f5",
    "accent": "#ca9ee6",
    "diffAdded": "#a6d189",
    "diffRemoved": "#e78284",
    "skill": "#ca9ee6"
  },
  {
    "id": "catppuccin-latte",
    "label": "Catppuccin Latte",
    "variant": "light",
    "surface": "#eff1f5",
    "ink": "#4c4f69",
    "accent": "#8839ef",
    "diffAdded": "#40a02b",
    "diffRemoved": "#d20f39",
    "skill": "#8839ef"
  },
  {
    "id": "catppuccin-macchiato",
    "label": "Catppuccin Macchiato",
    "variant": "dark",
    "surface": "#24273a",
    "ink": "#cad3f5",
    "accent": "#c6a0f6",
    "diffAdded": "#a6da95",
    "diffRemoved": "#ed8796",
    "skill": "#c6a0f6"
  },
  {
    "id": "catppuccin-mocha",
    "label": "Catppuccin Mocha",
    "variant": "dark",
    "surface": "#1e1e2e",
    "ink": "#cdd6f4",
    "accent": "#cba6f7",
    "diffAdded": "#a6e3a1",
    "diffRemoved": "#f38ba8",
    "skill": "#cba6f7"
  },
  {
    "id": "dark-plus",
    "label": "Dark Plus",
    "variant": "dark",
    "surface": "#1e1e1e",
    "ink": "#d4d4d4",
    "accent": "#007acc",
    "diffAdded": "#40c977",
    "diffRemoved": "#fa423e",
    "skill": "#ad7bf9"
  },
  {
    "id": "dracula",
    "label": "Dracula Theme",
    "variant": "dark",
    "surface": "#282a36",
    "ink": "#f8f8f2",
    "accent": "#ff79c6",
    "diffAdded": "#50fa7b",
    "diffRemoved": "#ff5555",
    "skill": "#ff79c6"
  },
  {
    "id": "dracula-soft",
    "label": "Dracula Theme Soft",
    "variant": "dark",
    "surface": "#282a36",
    "ink": "#f6f6f4",
    "accent": "#f286c4",
    "diffAdded": "#62e884",
    "diffRemoved": "#ee6666",
    "skill": "#f286c4"
  },
  {
    "id": "everforest-dark",
    "label": "Everforest Dark",
    "variant": "dark",
    "surface": "#2d353b",
    "ink": "#d3c6aa",
    "accent": "#a7c080",
    "diffAdded": "#a7c080",
    "diffRemoved": "#e67e80",
    "skill": "#d699b6"
  },
  {
    "id": "everforest-light",
    "label": "Everforest Light",
    "variant": "light",
    "surface": "#fdf6e3",
    "ink": "#5c6a72",
    "accent": "#93b259",
    "diffAdded": "#8da101",
    "diffRemoved": "#f85552",
    "skill": "#df69ba"
  },
  {
    "id": "github-dark",
    "label": "GitHub Dark",
    "variant": "dark",
    "surface": "#24292e",
    "ink": "#e1e4e8",
    "accent": "#0366d6",
    "diffAdded": "#34d058",
    "diffRemoved": "#ea4a5a",
    "skill": "#b392f0"
  },
  {
    "id": "github-dark-default",
    "label": "GitHub Dark Default",
    "variant": "dark",
    "surface": "#0d1117",
    "ink": "#e6edf3",
    "accent": "#1f6feb",
    "diffAdded": "#3fb950",
    "diffRemoved": "#f85149",
    "skill": "#bc8cff"
  },
  {
    "id": "github-dark-dimmed",
    "label": "GitHub Dark Dimmed",
    "variant": "dark",
    "surface": "#22272e",
    "ink": "#adbac7",
    "accent": "#316dca",
    "diffAdded": "#57ab5a",
    "diffRemoved": "#e5534b",
    "skill": "#b083f0"
  },
  {
    "id": "github-dark-high-contrast",
    "label": "GitHub Dark High Contrast",
    "variant": "dark",
    "surface": "#0a0c10",
    "ink": "#f0f3f6",
    "accent": "#409eff",
    "diffAdded": "#26cd4d",
    "diffRemoved": "#ff6a69",
    "skill": "#cb9eff"
  },
  {
    "id": "github-light",
    "label": "GitHub Light",
    "variant": "light",
    "surface": "#ffffff",
    "ink": "#24292e",
    "accent": "#2188ff",
    "diffAdded": "#28a745",
    "diffRemoved": "#d73a49",
    "skill": "#5a32a3"
  },
  {
    "id": "github-light-default",
    "label": "GitHub Light Default",
    "variant": "light",
    "surface": "#ffffff",
    "ink": "#1f2328",
    "accent": "#0969da",
    "diffAdded": "#1a7f37",
    "diffRemoved": "#cf222e",
    "skill": "#8250df"
  },
  {
    "id": "github-light-high-contrast",
    "label": "GitHub Light High Contrast",
    "variant": "light",
    "surface": "#ffffff",
    "ink": "#0e1116",
    "accent": "#0349b4",
    "diffAdded": "#055d20",
    "diffRemoved": "#a0111f",
    "skill": "#622cbc"
  },
  {
    "id": "gruvbox-dark-hard",
    "label": "Gruvbox Dark Hard",
    "variant": "dark",
    "surface": "#1d2021",
    "ink": "#ebdbb2",
    "accent": "#458588",
    "diffAdded": "#ebdbb2",
    "diffRemoved": "#cc241d",
    "skill": "#b16286"
  },
  {
    "id": "gruvbox-dark-medium",
    "label": "Gruvbox Dark Medium",
    "variant": "dark",
    "surface": "#282828",
    "ink": "#ebdbb2",
    "accent": "#458588",
    "diffAdded": "#ebdbb2",
    "diffRemoved": "#cc241d",
    "skill": "#b16286"
  },
  {
    "id": "gruvbox-dark-soft",
    "label": "Gruvbox Dark Soft",
    "variant": "dark",
    "surface": "#32302f",
    "ink": "#ebdbb2",
    "accent": "#458588",
    "diffAdded": "#ebdbb2",
    "diffRemoved": "#cc241d",
    "skill": "#b16286"
  },
  {
    "id": "gruvbox-light-hard",
    "label": "Gruvbox Light Hard",
    "variant": "light",
    "surface": "#f9f5d7",
    "ink": "#3c3836",
    "accent": "#458588",
    "diffAdded": "#3c3836",
    "diffRemoved": "#cc241d",
    "skill": "#b16286"
  },
  {
    "id": "gruvbox-light-medium",
    "label": "Gruvbox Light Medium",
    "variant": "light",
    "surface": "#fbf1c7",
    "ink": "#3c3836",
    "accent": "#458588",
    "diffAdded": "#3c3836",
    "diffRemoved": "#cc241d",
    "skill": "#b16286"
  },
  {
    "id": "gruvbox-light-soft",
    "label": "Gruvbox Light Soft",
    "variant": "light",
    "surface": "#f2e5bc",
    "ink": "#3c3836",
    "accent": "#458588",
    "diffAdded": "#3c3836",
    "diffRemoved": "#cc241d",
    "skill": "#b16286"
  },
  {
    "id": "horizon",
    "label": "Horizon",
    "variant": "dark",
    "surface": "#1c1e26",
    "ink": "#d5d8da",
    "accent": "#e95378",
    "diffAdded": "#27d797",
    "diffRemoved": "#f43e5c",
    "skill": "#ee64ac"
  },
  {
    "id": "horizon-bright",
    "label": "Horizon Bright",
    "variant": "light",
    "surface": "#fdf0ed",
    "ink": "#06060c",
    "accent": "#e84a72",
    "diffAdded": "#1eb980",
    "diffRemoved": "#f43e5c",
    "skill": "#ee64ac"
  },
  {
    "id": "houston",
    "label": "Houston",
    "variant": "dark",
    "surface": "#17191e",
    "ink": "#eef0f9",
    "accent": "#4bf3c8",
    "diffAdded": "#4bf3c8",
    "diffRemoved": "#f4587e",
    "skill": "#ad5dca"
  },
  {
    "id": "kanagawa-dragon",
    "label": "Kanagawa Dragon",
    "variant": "dark",
    "surface": "#181616",
    "ink": "#c5c9c5",
    "accent": "#658594",
    "diffAdded": "#8a9a7b",
    "diffRemoved": "#c4746e",
    "skill": "#a292a3"
  },
  {
    "id": "kanagawa-lotus",
    "label": "Kanagawa Lotus",
    "variant": "light",
    "surface": "#f2ecbc",
    "ink": "#545464",
    "accent": "#5a7785",
    "diffAdded": "#6f894e",
    "diffRemoved": "#c84053",
    "skill": "#b35b79"
  },
  {
    "id": "kanagawa-wave",
    "label": "Kanagawa Wave",
    "variant": "dark",
    "surface": "#1f1f28",
    "ink": "#dcd7ba",
    "accent": "#658594",
    "diffAdded": "#76946a",
    "diffRemoved": "#c34043",
    "skill": "#957fb8"
  },
  {
    "id": "laserwave",
    "label": "LaserWave",
    "variant": "dark",
    "surface": "#27212e",
    "ink": "#ffffff",
    "accent": "#eb64b9",
    "diffAdded": "#40b4c4",
    "diffRemoved": "#b381c5",
    "skill": "#b381c5"
  },
  {
    "id": "light-plus",
    "label": "Light Plus",
    "variant": "light",
    "surface": "#ffffff",
    "ink": "#000000",
    "accent": "#007acc",
    "diffAdded": "#00a240",
    "diffRemoved": "#ba2623",
    "skill": "#924ff7"
  },
  {
    "id": "material-theme",
    "label": "Material Theme",
    "variant": "dark",
    "surface": "#263238",
    "ink": "#eeffff",
    "accent": "#80cbc4",
    "diffAdded": "#c3e88d",
    "diffRemoved": "#f07178",
    "skill": "#c792ea"
  },
  {
    "id": "material-theme-darker",
    "label": "Material Theme Darker",
    "variant": "dark",
    "surface": "#212121",
    "ink": "#eeffff",
    "accent": "#80cbc4",
    "diffAdded": "#c3e88d",
    "diffRemoved": "#f07178",
    "skill": "#c792ea"
  },
  {
    "id": "material-theme-lighter",
    "label": "Material Theme Lighter",
    "variant": "light",
    "surface": "#fafafa",
    "ink": "#90a4ae",
    "accent": "#80cbc4",
    "diffAdded": "#91b859",
    "diffRemoved": "#e53935",
    "skill": "#9c3eda"
  },
  {
    "id": "material-theme-ocean",
    "label": "Material Theme Ocean",
    "variant": "dark",
    "surface": "#0f111a",
    "ink": "#babed8",
    "accent": "#80cbc4",
    "diffAdded": "#c3e88d",
    "diffRemoved": "#f07178",
    "skill": "#c792ea"
  },
  {
    "id": "material-theme-palenight",
    "label": "Material Theme Palenight",
    "variant": "dark",
    "surface": "#292d3e",
    "ink": "#babed8",
    "accent": "#80cbc4",
    "diffAdded": "#c3e88d",
    "diffRemoved": "#f07178",
    "skill": "#c792ea"
  },
  {
    "id": "min-dark",
    "label": "Min Dark",
    "variant": "dark",
    "surface": "#1f1f1f",
    "ink": "#888888",
    "accent": "#383838",
    "diffAdded": "#40c977",
    "diffRemoved": "#fa423e",
    "skill": "#ad7bf9"
  },
  {
    "id": "min-light",
    "label": "Min Light",
    "variant": "light",
    "surface": "#ffffff",
    "ink": "#212121",
    "accent": "#616161",
    "diffAdded": "#77cc00",
    "diffRemoved": "#d32f2f",
    "skill": "#9966cc"
  },
  {
    "id": "monokai",
    "label": "Monokai",
    "variant": "dark",
    "surface": "#272822",
    "ink": "#f8f8f2",
    "accent": "#99947c",
    "diffAdded": "#86b42b",
    "diffRemoved": "#c4265e",
    "skill": "#8c6bc8"
  },
  {
    "id": "night-owl",
    "label": "Night Owl",
    "variant": "dark",
    "surface": "#011627",
    "ink": "#d6deeb",
    "accent": "#44596b",
    "diffAdded": "#c5e478",
    "diffRemoved": "#ef5350",
    "skill": "#c792ea"
  },
  {
    "id": "night-owl-light",
    "label": "Night Owl Light",
    "variant": "light",
    "surface": "#fbfbfb",
    "ink": "#403f53",
    "accent": "#90a7b2",
    "diffAdded": "#08916a",
    "diffRemoved": "#de3d3b",
    "skill": "#d6438a"
  },
  {
    "id": "nord",
    "label": "Nord",
    "variant": "dark",
    "surface": "#2e3440",
    "ink": "#d8dee9",
    "accent": "#88c0d0",
    "diffAdded": "#a3be8c",
    "diffRemoved": "#bf616a",
    "skill": "#b48ead"
  },
  {
    "id": "one-dark-pro",
    "label": "One Dark Pro",
    "variant": "dark",
    "surface": "#282c34",
    "ink": "#abb2bf",
    "accent": "#4d78cc",
    "diffAdded": "#8cc265",
    "diffRemoved": "#e05561",
    "skill": "#c162de"
  },
  {
    "id": "one-light",
    "label": "One Light",
    "variant": "light",
    "surface": "#fafafa",
    "ink": "#383a42",
    "accent": "#526fff",
    "diffAdded": "#00a240",
    "diffRemoved": "#ba2623",
    "skill": "#924ff7"
  },
  {
    "id": "plastic",
    "label": "Plastic",
    "variant": "dark",
    "surface": "#21252b",
    "ink": "#a9b2c3",
    "accent": "#e06c75",
    "diffAdded": "#98c379",
    "diffRemoved": "#e06c75",
    "skill": "#b57edc"
  },
  {
    "id": "poimandres",
    "label": "Poimandres",
    "variant": "dark",
    "surface": "#1b1e28",
    "ink": "#a6accd",
    "accent": "#add7ff",
    "diffAdded": "#5fb3a1",
    "diffRemoved": "#d0679d",
    "skill": "#f087bd"
  },
  {
    "id": "red",
    "label": "Red",
    "variant": "dark",
    "surface": "#390000",
    "ink": "#f8f8f8",
    "accent": "#970000",
    "diffAdded": "#40c977",
    "diffRemoved": "#fa423e",
    "skill": "#ad7bf9"
  },
  {
    "id": "rose-pine",
    "label": "Rosé Pine",
    "variant": "dark",
    "surface": "#191724",
    "ink": "#e0def4",
    "accent": "#ebbcba",
    "diffAdded": "#9ccfd8",
    "diffRemoved": "#908caa",
    "skill": "#c4a7e7"
  },
  {
    "id": "rose-pine-dawn",
    "label": "Rosé Pine Dawn",
    "variant": "light",
    "surface": "#faf4ed",
    "ink": "#575279",
    "accent": "#d7827e",
    "diffAdded": "#56949f",
    "diffRemoved": "#797593",
    "skill": "#907aa9"
  },
  {
    "id": "rose-pine-moon",
    "label": "Rosé Pine Moon",
    "variant": "dark",
    "surface": "#232136",
    "ink": "#e0def4",
    "accent": "#ea9a97",
    "diffAdded": "#9ccfd8",
    "diffRemoved": "#908caa",
    "skill": "#c4a7e7"
  },
  {
    "id": "slack-dark",
    "label": "Slack Dark",
    "variant": "dark",
    "surface": "#222222",
    "ink": "#e6e6e6",
    "accent": "#1d978d",
    "diffAdded": "#ecb22e",
    "diffRemoved": "#ffffff",
    "skill": "#ad7bf9"
  },
  {
    "id": "slack-ochin",
    "label": "Slack Ochin",
    "variant": "light",
    "surface": "#ffffff",
    "ink": "#000000",
    "accent": "#8ae773",
    "diffAdded": "#ecb22e",
    "diffRemoved": "#ffffff",
    "skill": "#7c4dff"
  },
  {
    "id": "snazzy-light",
    "label": "Snazzy Light",
    "variant": "light",
    "surface": "#fafbfc",
    "ink": "#565869",
    "accent": "#09a1ed",
    "diffAdded": "#2dae58",
    "diffRemoved": "#ff5c57",
    "skill": "#f767bb"
  },
  {
    "id": "solarized-dark",
    "label": "Solarized Dark",
    "variant": "dark",
    "surface": "#002b36",
    "ink": "#839496",
    "accent": "#d30102",
    "diffAdded": "#859900",
    "diffRemoved": "#dc322f",
    "skill": "#d33682"
  },
  {
    "id": "solarized-light",
    "label": "Solarized Light",
    "variant": "light",
    "surface": "#fdf6e3",
    "ink": "#657b83",
    "accent": "#b58900",
    "diffAdded": "#859900",
    "diffRemoved": "#dc322f",
    "skill": "#d33682"
  },
  {
    "id": "synthwave-84",
    "label": "Synthwave '84",
    "variant": "dark",
    "surface": "#262335",
    "ink": "#ffffff",
    "accent": "#f97e72",
    "diffAdded": "#72f1b8",
    "diffRemoved": "#fe4450",
    "skill": "#ff7edb"
  },
  {
    "id": "tokyo-night",
    "label": "Tokyo Night",
    "variant": "dark",
    "surface": "#1a1b26",
    "ink": "#a9b1d6",
    "accent": "#3d59a1",
    "diffAdded": "#449dab",
    "diffRemoved": "#914c54",
    "skill": "#9d7cd8"
  },
  {
    "id": "vesper",
    "label": "Vesper",
    "variant": "dark",
    "surface": "#101010",
    "ink": "#ffffff",
    "accent": "#ffc799",
    "diffAdded": "#40c977",
    "diffRemoved": "#fa423e",
    "skill": "#ad7bf9"
  },
  {
    "id": "vitesse-black",
    "label": "Vitesse Black",
    "variant": "dark",
    "surface": "#000000",
    "ink": "#dbd7ca",
    "accent": "#bfbaaa",
    "diffAdded": "#4d9375",
    "diffRemoved": "#cb7676",
    "skill": "#d9739f"
  },
  {
    "id": "vitesse-dark",
    "label": "Vitesse Dark",
    "variant": "dark",
    "surface": "#121212",
    "ink": "#dbd7ca",
    "accent": "#bfbaaa",
    "diffAdded": "#4d9375",
    "diffRemoved": "#cb7676",
    "skill": "#d9739f"
  },
  {
    "id": "vitesse-light",
    "label": "Vitesse Light",
    "variant": "light",
    "surface": "#ffffff",
    "ink": "#393a34",
    "accent": "#1c6b48",
    "diffAdded": "#1e754f",
    "diffRemoved": "#ab5959",
    "skill": "#a13865"
  }
] as const satisfies readonly ShikiThemeSeed[]
