[package]
edition.workspace = true
license.workspace = true
name = "codepilotx-utils-output-truncation"
version.workspace = true

[lints]
workspace = true

[dependencies]
codepilotx-protocol = { workspace = true }
codepilotx-utils-string = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }

[lib]
doctest = false
