// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "./AbsolutePathBuf";

export type InitializeResponse = { userAgent: string,
/**
 * Canonical: absolute path to the server's CodePilotX home directory.
 */
codepilotxHome: AbsolutePathBuf,
/**
 * Legacy alias: absolute path to the server's CodePilotX home directory.
 * Kept for backward compatibility with clients expecting `codexHome`.
 */
codexHome: AbsolutePathBuf,
/**
 * Platform family for the running app-server target, for example
 * `"unix"` or `"windows"`.
 */
platformFamily: string,
/**
 * Operating system for the running app-server target, for example
 * `"macos"`, `"linux"`, or `"windows"`.
 */
platformOs: string, };
