[package]
edition.workspace = true
license.workspace = true
name = "codepilotx-extension-api"
version.workspace = true

[lib]
name = "codepilotx_extension_api"
path = "src/lib.rs"
test = false
doctest = false

[lints]
workspace = true

[dependencies]
codepilotx-config = { workspace = true }
codepilotx-context-fragments = { workspace = true }
codepilotx-protocol = { workspace = true }
codepilotx-tools = { workspace = true }
codepilotx-utils-absolute-path = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
