[package]
name = "codepilotx-chatgpt"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive"] }
codepilotx-app-server-protocol = { workspace = true }
codepilotx-connectors = { workspace = true }
codepilotx-core = { workspace = true }
codepilotx-git-utils = { workspace = true }
codepilotx-login = { workspace = true }
codepilotx-model-provider = { workspace = true }
codepilotx-plugin = { workspace = true }
codepilotx-utils-cli = { workspace = true }
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["full"] }

[dev-dependencies]
codepilotx-utils-cargo-bin = { workspace = true }
pretty_assertions = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }

[lib]
doctest = false
