[package]
edition.workspace = true
license.workspace = true
name = "codepilotx-cloud-tasks"
version.workspace = true

[lib]
name = "codepilotx_cloud_tasks"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
clap = { workspace = true, features = ["derive"] }
codepilotx-client = { workspace = true }
codepilotx-cloud-tasks-client = { workspace = true }
# TODO: codex-cloud-tasks-mock-client should be in dev-dependencies.
codepilotx-cloud-tasks-mock-client = { workspace = true }
codepilotx-core = { workspace = true }
codepilotx-git-utils = { workspace = true }
codepilotx-login = { path = "../login" }
codepilotx-model-provider = { workspace = true }
codepilotx-tui = { workspace = true }
codepilotx-utils-cli = { workspace = true }
crossterm = { workspace = true, features = ["event-stream"] }
owo-colors = { workspace = true, features = ["supports-colors"] }
ratatui = { workspace = true }
reqwest = { workspace = true, features = ["json"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
supports-color = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tokio-stream = { workspace = true }
tracing = { workspace = true, features = ["log"] }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
unicode-width = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
