// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GithubProfileLanguage } from "./GithubProfileLanguage";

export type GithubProfileRepository = { id: string, name: string, fullName: string, url: string, description: string | null, isPrivate: boolean, isFork: boolean, primaryLanguage: GithubProfileLanguage | null, stargazerCount: number, forkCount: number, updatedAt: string, };
