// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GithubProfileLanguage } from "./GithubProfileLanguage";

export type GithubProfileRepository = { id: string, name: string, full_name: string, url: string, description: string | null, is_private: boolean, is_fork: boolean, primary_language: GithubProfileLanguage | null, stargazer_count: bigint, fork_count: bigint, updated_at: string, };
