// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GithubUserStatus } from "./GithubUserStatus";

export type GithubProfileUser = { login: string, id: bigint, name: string | null, avatar_url: string | null, html_url: string, bio: string | null, company: string | null, location: string | null, website_url: string | null, email: string | null, followers: bigint, following: bigint, repository_count: bigint, starred_repository_count: bigint, status: GithubUserStatus | null, };
