// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GithubContributionWeek } from "./GithubContributionWeek";

export type GithubContributions = { total_contributions: bigint, total_commit_contributions: bigint, total_issue_contributions: bigint, total_pull_request_contributions: bigint, total_pull_request_review_contributions: bigint, restricted_contributions_count: bigint, weeks: Array<GithubContributionWeek>, };
