// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GithubContributions } from "./GithubContributions";
import type { GithubProfileOrganization } from "./GithubProfileOrganization";
import type { GithubProfileRepository } from "./GithubProfileRepository";
import type { GithubProfileUser } from "./GithubProfileUser";

export type GithubProfileOverview = { user: GithubProfileUser, organizations: Array<GithubProfileOrganization>, pinnedRepositories: Array<GithubProfileRepository>, popularRepositories: Array<GithubProfileRepository>, contributions: GithubContributions, };
