// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";
import type { GithubContributions } from "./GithubContributions";
import type { GithubProfileRepository } from "./GithubProfileRepository";
import type { GithubProfileUser } from "./GithubProfileUser";

export type GithubProfileOverview = { user: GithubProfileUser, organizations: Array<JsonValue>, pinned_repositories: Array<GithubProfileRepository>, popular_repositories: Array<GithubProfileRepository>, contributions: GithubContributions, };
