// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GithubContributionWeek } from "./GithubContributionWeek";

export type GithubContributions = { totalContributions: number, totalCommitContributions: number, totalIssueContributions: number, totalPullRequestContributions: number, totalPullRequestReviewContributions: number, restrictedContributionsCount: number, weeks: Array<GithubContributionWeek>, };
