// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GithubUserStatus } from "./GithubUserStatus";

export type GithubProfileUser = { login: string, id: number, name: string | null, avatarUrl: string | null, htmlUrl: string, bio: string | null, company: string | null, location: string | null, websiteUrl: string | null, email: string | null, followers: number, following: number, repositoryCount: number, starredRepositoryCount: number, status: GithubUserStatus | null, };
