// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GithubUserStatus = { emoji: string | null, message: string | null, indicates_limited_availability: boolean, expires_at: string | null, };
