// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProviderAuthStatusSetParams = { provider_id: string, emoji: string, message: string, limited_availability: boolean, expires_at: string | null, };
