// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProviderBalanceInfo = { currency: string, total_balance: string, granted_balance: string, topped_up_balance: string, };
