// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderBalanceInfo } from "./ProviderBalanceInfo";

export type ProviderBalanceResponse = { is_available: boolean, balances: Array<ProviderBalanceInfo>, error: string | null, };
