// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProviderAuthStartLoginParams = { provider_id: string,
/**
 * GitHub OAuth App client ID (required for `github-repositories`).
 */
client_id: string | null, };
