// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderAuthPollStatus } from "../ProviderAuthPollStatus";
import type { ProviderAuthReadStatusResponse } from "./ProviderAuthReadStatusResponse";

export type ProviderAuthPollLoginResponse = { status: ProviderAuthPollStatus, auth: ProviderAuthReadStatusResponse | null, };
