// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProviderRepoInfo = { id: number, name: string, fullName: string, description: string | null, private: boolean, fork: boolean, archived: boolean, disabled: boolean, htmlUrl: string, cloneUrl: string, sshUrl: string, defaultBranch: string, language: string | null, stargazersCount: number, updatedAt: string, pushedAt: string | null, };
