// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageDetail } from "../ImageDetail";
import type { TextElement } from "./TextElement";

export type UserInput = { "type": "text", text: string,
/**
 * UI-defined spans within `text` used to render or persist special elements.
 */
text_elements: Array<TextElement>, } | { "type": "image", detail?: ImageDetail, url: string, } | { "type": "localImage", detail?: ImageDetail, path: string, } | { "type": "skill", name: string, path: string, } | { "type": "mention", name: string, path: string, } | { "type": "document", data: string, media_type: string, name: string, } | { "type": "audio", data: string, media_type: string, name: string, } | { "type": "video", data: string, media_type: string, name: string, } | { "type": "file", data: string, media_type: string, name: string, } | { "type": "textFile", text: string, name: string, media_type: string, };
