import { bundledThemesInfo } from 'shiki'
import { resolve } from 'node:path'

type ThemeVariant = 'light' | 'dark'

type ThemeSeed = {
  id: string
  label: string
  variant: ThemeVariant
  surface: string
  ink: string
  accent: string
  diffAdded: string
  diffRemoved: string
  skill: string
}

type ThemeRegistration = {
  colors?: Record<string, string>
  tokenColors?: Array<{ settings?: { foreground?: string } }>
}

type ThemeModule = {
  default: ThemeRegistration
}

const outputPath = resolve(import.meta.dir, '../shared/shikiThemeSeeds.ts')
const checkOnly = process.argv.includes('--check')

const seeds = await Promise.all(
  bundledThemesInfo.map(async info => {
    const theme = ((await info.import()) as ThemeModule).default
    return createThemeSeed(info.id, info.displayName, info.type, theme)
  }),
)

const output = renderModule(seeds)
const current = await Bun.file(outputPath).text().catch(() => '')

if (checkOnly) {
  if (current !== output) {
    console.error('Shiki theme seeds are out of date.')
    process.exit(1)
  }
} else if (current !== output) {
  await Bun.write(outputPath, output)
  console.log(`Generated ${seeds.length} Shiki theme seeds.`)
}

function createThemeSeed(
  id: string,
  label: string,
  variant: ThemeVariant,
  theme: ThemeRegistration,
): ThemeSeed {
  const colors = theme.colors ?? {}
  const fallback = variant === 'dark'
    ? {
        surface: '#181818',
        ink: '#ffffff',
        accent: '#339cff',
        diffAdded: '#40c977',
        diffRemoved: '#fa423e',
        skill: '#ad7bf9',
      }
    : {
        surface: '#ffffff',
        ink: '#1a1c1f',
        accent: '#0285ff',
        diffAdded: '#00a240',
        diffRemoved: '#ba2623',
        skill: '#924ff7',
      }

  const surface =
    firstColor(colors, [
      'editor.background',
      'sideBar.background',
      'panel.background',
      'activityBar.background',
    ]) ?? fallback.surface
  const ink =
    firstColor(colors, [
      'editor.foreground',
      'foreground',
      'sideBar.foreground',
      'sideBarTitle.foreground',
    ]) ??
    firstTokenColor(theme) ??
    fallback.ink

  return {
    id,
    label,
    variant,
    surface,
    ink,
    accent:
      firstDistinctColor(
        colors,
        [
          'activityBarBadge.background',
          'textLink.foreground',
          'editorCursor.foreground',
          'focusBorder',
          'button.background',
          'activityBar.activeBorder',
        ],
        surface,
        ink,
      ) ?? fallback.accent,
    diffAdded:
      firstColor(colors, [
        'gitDecoration.addedResourceForeground',
        'gitDecoration.untrackedResourceForeground',
        'terminal.ansiGreen',
        'terminal.ansiBrightGreen',
      ]) ?? fallback.diffAdded,
    diffRemoved:
      firstColor(colors, [
        'gitDecoration.deletedResourceForeground',
        'terminal.ansiRed',
        'terminal.ansiBrightRed',
      ]) ?? fallback.diffRemoved,
    skill:
      firstColor(colors, [
        'charts.purple',
        'terminal.ansiMagenta',
        'terminal.ansiBrightMagenta',
      ]) ?? fallback.skill,
  }
}

function firstColor(
  colors: Record<string, string>,
  names: readonly string[],
): string | undefined {
  for (const name of names) {
    const color = normalizeColor(colors[name])
    if (color) return color
  }
  return undefined
}

function firstDistinctColor(
  colors: Record<string, string>,
  names: readonly string[],
  ...excluded: string[]
): string | undefined {
  for (const name of names) {
    const color = normalizeColor(colors[name])
    if (color && !excluded.some(value => colorsAreNear(color, value))) {
      return color
    }
  }
  return undefined
}

function firstTokenColor(theme: ThemeRegistration): string | undefined {
  for (const token of theme.tokenColors ?? []) {
    const color = normalizeColor(token.settings?.foreground)
    if (color) return color
  }
  return undefined
}

function normalizeColor(value: string | undefined): string | undefined {
  if (!value) return undefined
  const match = /^#([\da-f]{3}|[\da-f]{6})([\da-f]{2})?$/i.exec(value.trim())
  if (!match) return undefined
  const alpha = match[2] ? Number.parseInt(match[2], 16) / 255 : 1
  if (alpha < 0.45) return undefined
  const hex = match[1]
  return `#${
    hex.length === 3
      ? [...hex].map(character => character.repeat(2)).join('')
      : hex
  }`.toLowerCase()
}

function colorsAreNear(left: string, right: string): boolean {
  const a = parseColor(left)
  const b = parseColor(right)
  return Math.hypot(a[0] - b[0], a[1] - b[1], a[2] - b[2]) < 42
}

function parseColor(value: string): [number, number, number] {
  return [
    Number.parseInt(value.slice(1, 3), 16),
    Number.parseInt(value.slice(3, 5), 16),
    Number.parseInt(value.slice(5, 7), 16),
  ]
}

function renderModule(themeSeeds: readonly ThemeSeed[]): string {
  return `// This file is generated by scripts/generate-shiki-theme-seeds.ts.
// Do not edit it manually.

export type ShikiThemeSeed = {
  id: string
  label: string
  variant: 'light' | 'dark'
  surface: string
  ink: string
  accent: string
  diffAdded: string
  diffRemoved: string
  skill: string
}

export const SHIKI_THEME_SEEDS = ${JSON.stringify(themeSeeds, null, 2)} as const satisfies readonly ShikiThemeSeed[]
`
}
