[package]
edition.workspace = true
license.workspace = true
name = "codepilotx-guardian"
version.workspace = true

[lib]
name = "codepilotx_guardian"
path = "src/lib.rs"
test = false
doctest = false

[lints]
workspace = true

[dependencies]
codepilotx-core = { workspace = true }
codepilotx-extension-api = { workspace = true }
codepilotx-protocol = { workspace = true }
